### ISSUE TITLE
GIVbacks Process & Testing

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#103]
Hey @mohammadranjbarz !

I'm writing a testing guide for the GIVeconomy and want to understand the GIVbacks process clearly. How does it work on the backend?

Do we have to run a query to see the donations to verified projects within specific dates, and then manually get the eligible GIVback recipients list of addresses from there? Or are we able to just pull that list of addresses and pass to rGIV more directly?

After we have the list of addresses, we need to use the rGIV DAO to allocate GIV to those addresses.

For testing, I'm thinking that we should:
1. Set the "round dates" (maybe we make it 1 week for testing, or 4 days)
2. Ask testers to donate on next.giveth.io to verified projects
3. Get the list of addresses and donation amounts
4. Test allocating GIV for GIVbacks from rGIV DAO

Does that make sense?

**Comment by mohammadranjbarz** [comment]
Hey Lauren 
Yeah you are right , this is our calculation:
1. Get donations from givethio and giveth trace
2. Filte within specific dates
3. Group them by fromAddress
4. Aggregate givethio and giveth trace donors
5. Sort it by total donations amount

I don't know how rGIV works, so I don't know we can do it directly or not (although I suppose we do it manually at least  first rounds, to see what happens)

And for test scenario that you said, I think it's pretty good and necessary

**Comment by laurenluz** [comment]
Thanks @mohammadranjbarz so for testing, we will:
- Define a "round" will be from x date to y date
- Ask testers to donate to verified projects on Giveth next during those dates
- Testers to make sure donations appear in project donations
- Devs will pull data from database to make sure it matches the GIVbacks endpoint result

@divine-comedian from our discussion today, I understand that normally to allocate GIVbacks, the agent needs to create a Vote in the rGIV DAO and it needs to pass to get tokens to distribute. Can you sync w Mohammad and see what makes the most sense for our allocation? If there's a way to get the address list in the backend, etc... Maybe we can discuss in tomorrow's call.

**Comment by laurenluz** [comment]
related to #71

**Comment by laurenluz** [comment]
@aminlatifi to show @MohammadPCh how to pay himself GIVbacks as the distributor and then we can determine if the numbers are working on the frontend

**Comment by aminlatifi** [comment]
> @aminlatifi to show @MohammadPCh how to pay himself GIVbacks as the distributor and then we can determine if the numbers are working on the frontend

Done

**Comment by laurenluz** [comment]
Mitch took data from mohammad and send GIVbacks with rGIV DAO... used the send GIVbacks function in the token distro, but no one is seeing GIVbacks on the frontend.

oops! used the old token distro 😅 

need to make the agent a distributor... 
Mitch will make DAO with a shorter vote duration
will excude purple list
after amin deploys the new token distro, will add the agent to the new rGIV DAO

**Comment by divine-comedian** [comment]
new test dao - https://aragon.1hive.org/#/giveconomytest/

Agent addresss for distributor - 0xc365772a1df6880970db5c42a0aa2f24e18810fc

**Comment by laurenluz** [comment]
ok nice, so when @aminlatifi does the new test deployment and the new token distro tomorrow we can add the agent

**Comment by aminlatifi** [comment]
Assigned 2M 
https://blockscout.com/xdai/mainnet/tx/0xeee6f7f42ba9ec73a590632b5b86725516c3fc5a4a09555b62cf5e24b54a0d19/logs

**Comment by divine-comedian** [comment]
okay! I tested the full GIVbacks process - collecting the data from the function call - creating the vote with evm-crispr with the GIVbacks data, passing the vote and disbursing GIV from the tokenDistro via Agent -

I can see my GIVbacks update on the GIVeconomy UI from the verified donations I made during the selected period 

here is the full vote with logs 
https://blockscout.com/xdai/mainnet/tx/0x6bfe3a6f51167a7650eb3b72374bbb49c299602c3c804aa20867cd13764e7f7e/logs

**Comment by divine-comedian** [comment]
here is the full script - 
```
connect 0x921126905e732c94196cf2CA03c3a6C3769bEd44 token-manager voting
act 0xc365772a1df6880970db5c42a0aa2f24e18810fc 0x4be013Ee4Cdda158338EC99e64c8c832147bc4cc sendGIVbacks(address[],uint256[]) [0xe611a720778a5f6723d6b4866f84828504657181,0x981e7512e87d2f7228d3f03b65950eb6a1b21bac,0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c,0xb22981ba3fe1de2325935c91a3b717168fb86714,0x10f5d45854e038071485ac9e402308cf80d2d2fe,0xed8db37778804a913670d9367aaf4f043aad938b,0x4318cc449b1cbe6d64dd82e16abe58c79e076c2b,0xae7f11378daba3757e9d7691be04285938be35b5,0x57f908c42f5a0e5dbbd3c35a137cc242cf89add6,0x9c5c8cc5db1c54a4d4f9866d3fc561cfd9e5b67d,0x90a29e9f7f7639f725b76bb3ba833fe5d234b771,0x6eab8f9b2724b04aed6e7e68f4c1b6158e47e12d,0xc46c67bb7e84490d7ebdd0b8ecdaca68cf3823f4,0x59e83f9c2d71c310b0419d295b4395014a235490,0x59ae7f21d18b2f5fdc7a99c4fd6dd9e67cec0bc9,0x35213d5c02fead91722bfd0cfc3e49055a440252,0x0b3820f9e8252f9b5b4f8d804b017ce9464446c1,0xf23ea0b5f14afcbe532a1df273f7b233ebe41c78,0x317bbc1927be411cd05615d2ffdf8d320c6c4052,0x826976d7c600d45fb8287ca1d7c76fc8eb732030,0x2bf034eccebc8cd60dab9c249b6c2996dcb7d8ec,0x45233ff6bbc10f0eb41f430561ac97d78ddfb4cd,0x6d97d65adff6771b31671443a6b9512104312d3d,0x10a84b835c5df26f2a380b3e00bcc84a66cd2d34,0x8f48094a12c8f99d616ae8f3305d5ec73cbaa6b6,0x2ea846dc38c6b6451909f1e7ff2bf613a96dc1f3,0xa4d506434445bb7303ea34a07bc38484cdc64a95,0x7c5361f5bb5e2bb123c95e69bed331f3b0b8f094,0xc83810a3581c63bf71756bdbbc971077ecff6e65,0x049569adb8a1e8a9349e9f1111c7b7993a4612eb,0x00d18ca9782be1caef611017c2fbc1a39779a57c,0x2d0895e23bb48d7af5d036e106a6e124c8280955,0x947540ce2990c70c683ab72c920b62967ac93ae2,0xc687611f5b0fcc6e8e531111a8820a1041e55679,0x068b698a8b1f068000a93dabd48a21f0fe20f19a,0x7710e7e881333fd3396ca5966bed6e72746b612d,0x0a180de4cc4463ddcd4ec1adb6512831ac34d86e,0x2fe95ba46d36e6bbc8d3bbc6bf3f18c85c91f3af,0x18de5e2ad69e9bbaa9e2ff7ebdec4f217414be22,0x5dbc9bfaa9bff81ef5497bc3749b47bf3b1e34b6,0xbf11820343accdd217bbbd986f78b2af765bada9,0x11feffab82a4308dd99df99c8c035453a8d2eb44,0xa485c5de3cd391fb12ec946f384dec0935f90624,0x5deea3a1c250f789cbe2542f0c1529e355fffc1a,0x56a170f86f1ac5276d6ece95e2ed4f26a02413b8,0x254ecc313ea52638b1fbf18e29f6b8ddf114b0ab,0x2188c8ff538e34934ca64d3ef9eac5a8096cdb33,0x1e975f53956d644868f3ea25690b1bbeda658565,0x5b0ab02cba6e27ff1f4e1faa740525eaa21a2d7c,0x1cbacf412316a61f76acec44c414f01b4c999552,0x645027d472ff00544a416aa99eafe0d8058285f9,0xc067d4fd13e2a4ed46f645f1d38fb81eb752eda4,0x08771e3dc8536ddbdbaf295d94c9dacf10a0d665,0xd11e3f2bc9d12001aa73ac9b1e0395cbbffc7618,0xd4a8ad632c3bd51de7e9f2e113c174f2778ff4b9,0x0acde556e9383de923d05fe5afd5502d5f56bcf6,0xa85dfe11e506d69e9db3b29defbdf36e6d3cc07e,0x6a1044f41bfc9084abb634d27f26f2d60e8eeaf8,0x6247503137691136a03a3a6f0b455e5ace1224df,0xfd550bdba6f8df8d194daa09b27c518f3b41ea6d,0x85d8d12c54234294bf47c50115f705f737e0bd47,0xb050f896146e6b08382c20b5f8dffdfba6c3b19f,0x9a1e9d9771eeffa679ec6414fde1424a5b6f5146,0x5ad677967629bbe44976aecfb6b51b7fedaf2686,0x08ffd6bea5d2bda828df108289373e8a989b56d3,0x1aecce0ed802907c5a8988f00f1f5be037abb141,0x96739a1598fde02cf86644d97ebd952cb0fd7f5d,0xb6647181dd1440e37cc3f177b9d11fbdcaa3955c,0xe8e03701f332e29f3d3365c62a5f7bd4ffcc26ee,0x2e6d66a813ddcf324f16db6f00887f27732c20cb,0x7168085be34e58e19003793a67c7810652dc3e82,0xda3542f8196ee4271ab698c3b47fbc7782228b50,0xc21a7164354565ef352b00143dac4af9341efdcd,0x9ac706f061dc5fb6b98d8f5bdd8e197439653e2c,0xacac7890c42218a2e639cf336d08061cc06eb881,0x29e877d881134c24ac70176fa67b1c0c2b8ce111,0xedc72512b061b43892031ad103a54eee02d4806b,0xc85c252f525b75cfbddcdfbebe8c0b40207dcea5,0xb06aed0fab4802dc7b78852f9cdd7e17a1924444,0x8418e7a194cfddc9ff3b85125347e1e71e5e0292,0xe1a5a3cf5a8b365964970798d268ed79667ef911,0xf6e067b863a838c19b9e71eeb9cd45965770e879,0x2b31a18b862c7405845c93f1973d059d0e98b2d4,0x0910f214b82310895be1055eeb378178d2bfcea8,0xa6ca1ab68c48e22b26acf705bff1292d028c850e,0x4e6aa601aa1d81a9f04e6264ec88cf963448c389,0xc875a15956b4a47c8e85791d9891577eec762bc2,0xa34ee10341cd021fb451eaf3f93fe2e55ffa993b,0xede563e445c9288f325c6a8faa350d730b7009df,0x99e5ee528c0a76d0fd55e379eb49d236a5e7dabf,0xbb4848201915534cbd58465f2318749ceb9b2b8e,0x3bc730eb9a9ec329425bb88b1d3b2ce18f15a5b9,0x73f2ba1e61abd66257db87ba8539c356ba140235,0xeb7cc7f7fc8e9c29388754611fcb3f791bdaefff,0x72d68829baacaacfc0ae746d770b44cec4e3047a,0xdfe9930e7f858aaefabb088e541c29e78f2cff09,0x1c1bd8c213ecf004ace7866e12abc405a19b3ae3,0xa7ed40bb516d24cdbb334e92f09e9a8367205a55,0xaa75a750802e55a236728bfd5bf19678cc059faf,0x5b14c2bc2f5ac4ee7820692546bf03d6183683be,0xa334b9da3e1b8d31795b983e2f0f74065d51d5cb,0x6bad0ceb7052e2e53cc307eb80a2e0523a3f69cb,0x7b3812add36df2bf0bf49fc63ebb4fbeec65b15b,0xfa4b47d26a8ec5b50c2d118c1d20058e7210512c,0x832a0504e4bd82cace1da85c9c66f81e1b7d36d3,0x2f5b5b85495274b6b8c65f4a7eefe88f2837d794,0xc2ca4ee4c8c79796e8beea362f657f5004a9d1ca] [15381639999999999000000,8068240000000000000000,8000239999999999000000,3725260000000000000000,3156449999999999700000,2282860000000000000000,1811940000000000100000,1687500000000000000000,1687500000000000000000,1559579999999999900000,1275000000000000000000,458360000000000000000,442500000000000000000,391420000000000000000,390390000000000000000,315250000000000000000,254570000000000000000,187500000000000000000,187500000000000000000,176250000000000000000,168260000000000000000,151840000000000000000,150000000000000000000,150000000000000000000,146250000000000000000,131250000000000000000,112500000000000000000,97500000000000000000,80840000000000000000,76340000000000000000,75000000000000000000,75000000000000000000,48170000000000000000,37500000000000000000,37500000000000000000,22980000000000000000,18750000000000000000,18750000000000000000,18750000000000000000,18750000000000000000,18750000000000000000,15000000000000000000,14250000000000000000,13800000000000000000,13500000000000000000,12000000000000000000,11250000000000000000,11250000000000000000,9750000000000000000,9380000000000000000,7500000000000000000,6750000000000000000,6640000000000000000,6600000000000000000,6380000000000000000,6380000000000000000,6380000000000000000,6380000000000000000,6190000000000000000,6190000000000000000,6150000000000000000,6150000000000000000,6070000000000000000,6000000000000000000,5930000000000000000,5810000000000000000,5810000000000000000,5810000000000000000,5660000000000000000,5630000000000000000,5630000000000000000,5630000000000000000,5630000000000000000,5250000000000000000,5060000000000000000,4990000000000000000,4990000000000000000,4990000000000000000,4880000000000000000,4880000000000000000,4880000000000000000,4500000000000000000,4460000000000000000,4130000000000000000,4130000000000000000,4130000000000000000,4130000000000000000,4130000000000000000,4130000000000000000,3970000000000000000,3960000000000000000,3940000000000000000,3780000000000000000,3750000000000000000,3750000000000000000,3750000000000000000,1880000000000000000,1880000000000000000,1880000000000000000,1880000000000000000,1120000000000000100,750000000000000000,560000000000000060,380000000000000000,190000000000000000,40000000000000000,10000000000000000]
```

**Comment by laurenluz** [comment]
can run another test on the test DAO w DRGIV3

**Comment by divine-comedian** [comment]
here's a spreadsheet generated by the givbacks script that we can use to analyze some sample data before running the actual function

https://docs.google.com/spreadsheets/d/1MTviWUK1ztU5YfsrT8YrKL0X4VL9zs5GjLGmFPEThFI/edit?usp=sharing

**Comment by mohammadranjbarz** [comment]
> here's a spreadsheet generated by the givbacks script that we can use to analyze some sample data before running the actual function
> 
> https://docs.google.com/spreadsheets/d/1MTviWUK1ztU5YfsrT8YrKL0X4VL9zs5GjLGmFPEThFI/edit?usp=sharing

And it's not accurate, because the GIV donations of first day don't have price, so they are not in this list
( We should add price for them manually)
