### ISSUE TITLE
GIVdrop: Design Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#104]
Need to update the calculators and add disclaimed to GIVdrop design flow

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=420%3A44377

**Comment by laurenluz** [comment]
- remove calculators to reduce scope
- make sure to keep APR & important info!
- improve "next" & "back" arrows to make them more visible

**Comment by markoprljic** [comment]
I believe all of the revisions are done.
