### ISSUE TITLE
How to deal with token distro sending all allocated tokens (From everywhere) to the address when they claim from a specific part

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#109]
Related to #108

Right now, when a use claims from GIVbacks, liquid GIVstream portion, GIVgarden rewards, or rewards from any individual pool... they amount that goes to their wallet in a single tx is the part they are trying to claim + the liquid GIVbacks portion + the liquid GIVstream portion.

We need to decide if:
- we add more popups and change UI to represent this better
- we try to modify the smart contracts to suit our current desings
- we try to implement a backend solution to separate parts

**Comment by laurenluz** [comment]
@markoprljic I think we're going to need to add more popups like this one throughout the entire GIVeconomy UI... 

![image](https://user-images.githubusercontent.com/75490971/140079829-24fca088-3619-4041-8ed2-1d01787a7be4.png)

**Comment by markoprljic** [comment]
I think claiming ALL in one tx is better and it's better to have this communicated across GIVeconomy rather than modifying the SC's to separate these. 

@laurenluz Did you leave comments in Figma on the places where these new modals need to be shown?

**Comment by laurenluz** [comment]
yeah totally agree - that's what we were concluding as well in the call. To just go ahead and have the user claim all - showing them the breakout in the popup. I'll go into the figma now and make comments
