### ISSUE TITLE
GIVgarden Test Deployment Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#112]
A few fixes needed for this page:

- [x] Make "OPEN GARDENS" (both places) link to https://honey-pot-o49n5fgrn-1hive.vercel.app/#/garden/0x79c52e1a74d01cf030f3cbbbbf84b01476c9ac93
- [x] "OPEN GARDENS" should say "OPEN GIVGARDEN"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5b9df054-7351-43d2-8b39-572ba5b027a2)
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/352cef8f-4c69-443d-89b1-37affd537856)

- [x] Connect "harvest" box to correct numbers from backend/smart contracts:
- [x] the big number "257.9055" claimable amount should be the "claimable" rewards earned from the 100% GIV staking pool on xDai
- [x] the "9.588 GIV/week" should be the "streaming" amount earned from the 100% GIV staking pool on xDai. This is the vested tokens that are going to add to the user's GIVstream after they harvest @mohammadranjbarz @aminlatifi 

Harvest box:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/dae89b12-e216-46db-83ba-699784f49831)

100% GIV staking pool on xDai:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/18763030-f3cd-4a42-9698-f340aecb9f41)

@MohammadPCh can you help w this on the frontend? And coordinate w @mohammadranjbarz & @aminlatifi to get the correct data

**Comment by MohammadPCh** [comment]
hey @Lauren,
I'm working on them. the will fix soon.

**Comment by laurenluz** [comment]
Hey @MohammadPCh the updates look good, but when I click "harvest" nothing is happening... is that because we are waiting on the popup to be implemented?

Also... we need to consider the case in which the user is not connected to xDai....in that case, they won't have anything to claim here. Maybe this should have the rewards box just say "switch network" and when the user clicks they get the prompt in metamask to switch network? what do you think @markoprljic ?

![image](https://user-images.githubusercontent.com/75490971/144137012-75329145-c47d-43d1-b45f-1ff6819fcefd.png)

**Comment by mosaeedi** [comment]
![Default](https://user-images.githubusercontent.com/13708322/144429517-2e9372e6-a656-4646-9224-b911a2d64e4b.png)


When the user is not on xDAI network, we can change the xDAI icon on top of the component to look like disabled, and add the question mark.
Users can hover on the question mark to see the tooltip...

![Tooltip](https://user-images.githubusercontent.com/13708322/144429539-37ef5781-e1ef-4b16-8dae-83f10ac1f9b9.png)

They can switch networks by clicking on the link inside the tooltip or using the main button at the bottom of the component.

_Note: The Harvest should be disabled? right?_

**Comment by mosaeedi** [comment]
@markoprljic

**Comment by mosaeedi** [comment]
oh got it

**Comment by mosaeedi** [comment]
![Screen Shot 2021-12-02 at 9 09 35 PM](https://user-images.githubusercontent.com/13708322/144474605-ab496df9-dcbb-4301-93a9-7c217708f0f2.png)

**Comment by markoprljic** [comment]
Yes

**Comment by laurenluz** [comment]
@mosaeedi  thank you!! can you send a link to this in the figma for @MohammadPCh ?
