### ISSUE TITLE
GIVstream Test Deployment Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#115]
- [x] the background is overlapping the opening text @MohammadPCh 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/59f5169e-7e1e-4b8a-81ce-a46e1d77e7c0)

- [x] GIVstream progress bar should go up with time... to it takes 5 years for the entire progress bar to be filled. The % should go up accordingly... and the time remaining should go down

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b7e76be3-9c77-4856-ba59-e2ea63319d60)

- [x] The GIVstream flowrate should be the `vested tokens` / `time remaining for GIVstream` @mohammadranjbarz @aminlatifi 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3b0e517a-a286-4351-8ec4-aefc66ccbd33)

- [x] the GIVstream claimable rewards should be `liberated tokens from the token distro` - `amount allocated from GIVbacks`

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/82cacc7b-ddd7-413c-82c3-8b2a4f51effd)

- [x] This is a typo... "GIVstrem" should be "GIVstream"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/36b6d240-f3e5-4a87-a1f1-656236b6647d)

- [x] This button should say "LEARN MORE" and link to our documentation. That documentation is not live yet, so I don't have the link.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/104001fc-d6d4-429c-8666-4a078b282985)

- [x] This button should say "INCREASE YOUR GIVSTREAM" and link to the "Increase your GIVstream part lower on the page. Or, if that's weird... we can just get rid of this button entirely.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0266425e-d776-416f-a897-e3d2685a17d3)

- [x] History table needs to be developed, as per #110

**Comment by GriffGreen** [comment]
@MohammadPCh the Flowrate will be the total number of tokens times

0.003461538462

So if the person earns 1000 tokens from the Distro then some % will be claimable... but that doesnt matter they will get a stream of 3.461538462 GIV/week no matter what the claimable amount is.

See math here: https://docs.google.com/spreadsheets/d/1GAlGc0PHU5_UArZh5mr94z4n2TWy2GOikc80VrYeZcw/edit?usp=sharing

**Comment by laurenluz** [comment]
@MohammadPCh 

Cutting the History table from scope, so the only fixes required should be the highlight parts below. We're also missing the harvest modal popup (should only show GIVstream  + GIVbacks in the modal)
![image](https://user-images.githubusercontent.com/75490971/144535655-18b871a4-fa88-416a-9265-57aea36b8feb.png)

Reference: #141 #142
