### ISSUE TITLE
Harvest GIV rewards popup

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#116]
Need to finish the design for these popups. I made comments in the figma explaining them @markoprljic - lmk if you have questions

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c5267408-deeb-4ae8-aadc-ab9a3c3029d6)

**Comment by markoprljic** [comment]
Going to work on this next @laurenluz

**Comment by markoprljic** [comment]
All done.
