### ISSUE TITLE
Create Audit report to share w Gemini

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#118]
Smart contract audit report, once finished

**Comment by laurenluz** [comment]
it would be great if we could have Jesus and Edu offer an audit report - Griff to ask Jesus in the call

audit report will be good for gemini & for our community

**Comment by laurenluz** [comment]
We have the full system, but we need it to be turned into a report to share with Gemini - contact Adria or Edu - @paxthemax is on it!

**Comment by laurenluz** [comment]
@paxthemax to cat herd

**Comment by paxthemax** [comment]
Auditor responded, he will prepare the audit report. ETA TBD
