### ISSUE TITLE
Make sure extra univ3 pool rewards carry over to next cycle

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#119]
With the univ3 pool... if people are staking NFTs out of range, they don't earn rewards, but the fact that they are staking means that there are less rewards going to others...

so at the end of the 26 week round, we will have extra rewards for that pool that we need to do something with. I think we should have it just add to the next round's rewards for the univ3 pool... or we extend the rewards for that pool.

@aminlatifi

**Comment by aminlatifi** [comment]
At staking program creation on Uniswap we defined multiple parameters: start time, end time, reward token, amount, and refundee. The refundee is the wallet address that will receive the leftover after the program is finished.

**Comment by GriffGreen** [comment]
I don't think we have to worry about this because of our custom token solution and the choice to have a high assignment on the token distros

**Comment by GriffGreen** [comment]
Can we close this @aminlatifi ?

**Comment by aminlatifi** [comment]
> Can we close this @aminlatifi ?

Yeah
