### ISSUE TITLE
GIVgarden harvest box - dollar value

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#122]
This is the USD value equivalent to the liquid/claimable GIV rewards earned from the GIVgarden rewards contract

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/60e87a10-0a4c-4596-a42b-17854ae488bd)

**Comment by aminlatifi** [comment]
@mohammadranjbarz for the GIV price we should get GIV/ETH rate and ETH/USDT rate from pools of uniswap or honeyswap and then deduce the GIV/USDT rate

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
I did something for kovan network but for xdai I had problem, because I couldn't find ABI for this contract
`0x8c77ba1d90c57d584aeed57bc9b55258b8be3438`
