### ISSUE TITLE
GIVgarden harvest box - streaming amount

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#123]
This is the streaming amount of GIV earned from the GIVgarden rewards (wrapping GIV / staking on xDai). Basically the amount of vested tokens the user has earned divided by the amount of time remining on for the GIVstream.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1f4d85c6-ed4c-470a-94d8-a152a3ccd8d1)

**Comment by laurenluz** [comment]
Note: should go to zero after the user harvests (and that GIVstream amount is added to the history table on the GIVstream page)

**Comment by mohammadranjbarz** [comment]
Now we have 
```
{
  "data": {
    "tokenDistroContractInfos": [
      {
        "cliffTime": "1635007800",
        "duration": "11262857",
        "id": "0x95c76aeadf98dbd5ef6e2acd8308e563302af2e3",
        "initialAmount": "1500000000000000000000000",
        "lockedAmount": "13500000000000000000000000",
        "startTime": "1635007800",
        "totalTokens": "15000000000000000000000000"
      }
    ]
  }
}
```
@laurenluz  @aminlatifi 
but I and @MohammadPCh  don't know it's enough for calculating stream or we need something more
