### ISSUE TITLE
GIVfarm - Total Claimable rewards - dollar value

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#125]
This is the dollar value equivalent of #124 (only the liquid amount - not the vested/streaming amount)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7c264c4d-3009-468d-942f-c819dba07d40)

**Comment by mohammadranjbarz** [comment]
We have the parameters on Kovan, you can call as it mentioned here
https://github.com/Giveth/giv-token-subgraph#test
@MohammadPCh 
please let me know if you need more data, or if you have problem with query
