### ISSUE TITLE
GIVfarm - Update cards "Sushiswap" + "GIVgarden Staking" + "Staking"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#148]
The first card should be "Honeyswap"

The center card should be "SushiSwap"

The last card should be "GIVgarden Staking"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fa72a88c-db6a-4088-80cd-5fdfbb3091e0)

**Comment by laurenluz** [comment]
Also on mainnet, this card should be "Staking" (not GIVstream)

![image](https://user-images.githubusercontent.com/75490971/144143599-0309c5cb-b725-4fc3-aac2-09c140dff9ce.png)

**Comment by willyogo** [comment]
@divine-comedian can you also plz add some padding below the cards while you're in here?

![2021-12-08 08 51 32](https://user-images.githubusercontent.com/26232238/145239391-8ee74e9d-ec0b-4fc6-8078-1a9bcc57e748.gif)

**Comment by WhyldWanderer** [comment]
Staking card: 
When I click stake on the card, the modal comes up but the terminology is changed to "wrap"

![image](https://user-images.githubusercontent.com/74267818/145289935-0bd235b6-9878-44ce-9c18-50b7f4f6e1bb.png)

Should be changed to "stake" so its not confusing

**Comment by divine-comedian** [comment]
the single-asset staking uses the same label for mainnet and xDAI - I would suggest changing to both say `Staking`

**Comment by divine-comedian** [comment]
@MohammadPCh  Is it possible to make the single-asset farm on xDAI have a different title than the than the one on Ethereum mainnet (Kovan)

![image](https://user-images.githubusercontent.com/67759413/145602622-fd7422a8-0c8a-47f2-8428-2129a15428b0.png)

**Comment by laurenluz** [comment]
@MohammadPCh The titles should be as follow:

- [ ] 100% GIV pool on xDai should be called "GIVgarden Staking"
- [ ] 100% GIV pool on Ethereum should still be called "Staking"
