### ISSUE TITLE
Frontend APR details modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#150]
This needs to be dev'd up...

When you click the calculator:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0504649e-5075-4189-8f54-a9218fee1786)

You get this modal:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a1ff80e3-0c15-4dac-bfa8-dc68b0e573bb)

Design: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19%3A17761

**Comment by laurenluz** [comment]
I'm thinknig we should make the calculator button a "?" (on the card next to APR)

and then when the user clicks it, they get a popup that JUST says the important messgae... no calculator. What do you think @markoprljic ?

ok to cut scope and make the calculator fast follow?

**Comment by markoprljic** [comment]
Responded in Figma

**Comment by laurenluz** [comment]
These are the remaining tasks here:

- [ ] Remove calculator image next to APR (looks like QR code thing) from *all* GIVfarm cards
- [ ]  Make the 🌟 next to the % clickable
- [ ] when the user clicks, they get this modal. Add an "X" to the corner so they can close it
![image](https://user-images.githubusercontent.com/75490971/145478181-cad0f0d7-2326-4eaa-8450-8c7e4b3a2afe.png)
- [ ] the earnings breakdown numbers need to be updated in the frontend... the claimable immediately is 10% on the launch day and increasing continuously until it becomes 100% after 5 years.... the  increasing your GIVstream is `100% - claimable %`

- [ ] "What is a GIVstream" leads them to this popup (a second popup):

![image](https://user-images.githubusercontent.com/75490971/145478453-15feda60-0bc0-40d6-8749-95b7e1d594b4.png)

@MohammadPCh please help to implement these - lmk if you have questions.

**Comment by MohammadPCh** [comment]
Done :)

**Comment by laurenluz** [comment]
@MohammadPCh testing this one, when I click the "?" I just get a greyed out screen and don't see the "important" message"

![image](https://user-images.githubusercontent.com/75490971/145821390-490676ae-b02d-461d-bcf0-fd005ffd0254.png)

**Comment by MohammadPCh** [comment]
@laurenluz could you please help me to reproduce it?
because it's working for me.

**Comment by MohammadPCh** [comment]
@laurenluz  Found the problem and i think it's fixed.
