### ISSUE TITLE
"The GIVeconomy is here" banner design

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#158]
@markoprljic we need a nice banner to announce the GIVeconomy on the DApp at launch

I'll write some text for it. The basics will be:

"The GIVeconomy is here"
(some subtext)

Button: Claim Your GIVdrop

**Comment by markoprljic** [comment]
@laurenluz This is work for Catarina. Moving forward she and @rodricastillo9013 can do these tasks. I asked Amin to invite her to Github. In the meantime I will post this issue on the design channel in Discord for her awareness.

**Comment by laurenluz** [comment]
Great

**Comment by playingleela** [comment]
hey everyone! Im in github now ((: I will work on this, thank you!

**Comment by playingleela** [comment]
![Twitter post - GIVeconomy des  #158](https://user-images.githubusercontent.com/94190369/145054634-f14f8fb6-5c8d-4e1d-94a6-971c20e95398.jpg)
![GIVeconomy Banner des  #158 (1)](https://user-images.githubusercontent.com/94190369/145054654-a7e723b9-2d5f-4aee-909d-50337c4289d3.jpg)
Here it is @laurenluz @markoprljic 
@laurenluz let me know if you need any changes ((:

**Comment by laurenluz** [comment]
Thanks @playingleela. Can you please update the text and add the following:

- Subtext: "Rewarding & empowering those who GIV"
- Add Button w/ text: "Check your GIVdrop"

Also, the purpose of this is to shill the GIVeconomy from our homepage as a banner and get people to claim their GIV from "The GIVdrop" - so can you include some of the GIV tokens in the design?

![image](https://user-images.githubusercontent.com/75490971/145081203-f8f39395-5abf-4b65-9882-24155c15783f.png)

https://www.figma.com/file/bV3f7aLHK2pIs7tlzLGVgH/Giveth-Branding?node-id=1130%3A18182

For context, this will be on our homepage after launch... like the gitcoin banner right now on https://giveth.io/ :
![image](https://user-images.githubusercontent.com/75490971/145081357-f800c8a0-c7eb-4ec8-818c-4aff52a47f7d.png)

**Comment by playingleela** [comment]
![Twitter post - GIVeconomy des  #158 (3)](https://user-images.githubusercontent.com/94190369/145090818-87435c7f-3f08-40ab-ae40-4f9196b5fb0c.jpg)
![Twitter post - GIVeconomy des  #158 (2)](https://user-images.githubusercontent.com/94190369/145090836-ee22a2ec-0fd5-4cd0-a985-313503706ccf.jpg)
![Twitter post 2 - GIVeconomy des  #158 (1)](https://user-images.githubusercontent.com/94190369/145091804-b81b0040-509f-4d40-9090-d100d1e7b01f.jpg)
)
![GIVeconomy Banner 2 des  #158 (1)](https://user-images.githubusercontent.com/94190369/145091965-8dc5a392-9981-4869-971d-c04771b6e123.jpg)
I did one more option @laurenluz let me know what you prefer and I will do it in the right size as this banner of gitcoin ((: right now its is twitter size and website header

**Comment by laurenluz** [comment]
They look great @playingleela ! Look the background. Just I think some miscommunication on the text...

The big text should still be "The GIVeconomy is here"
subtext: "Rewarding & empowering those who give"
Button "Check your GIVdrop"

Also sorry, I made a typo before. I meant "give" not "GIV" in the subtext 😄 I've been typing "GIV" too much 👀 

I like the tokens falling in the first example, but also really like the colours and the contrast in the second example. Maybe you can combine the best of both together?

**Comment by playingleela** [comment]
heyy @laurenluz ops my mistake! sure, I will fix it and send back to you ((:

**Comment by playingleela** [comment]
![GIVeconomy Banner 2 des  #158 (2)](https://user-images.githubusercontent.com/94190369/145200125-3319b10f-ee53-4890-bb36-9a26121976d5.jpg
![Twitter post 2 - GIVeconomy des  #158 (2)](https://user-images.githubusercontent.com/94190369/145200142-3f15c85b-2423-4e45-b764-817a6d71ef58.jpg)
)

**Comment by playingleela** [comment]
![GIVeconomy Banner 2 des  #158 (2)](https://user-images.githubusercontent.com/94190369/145200181-08427d69-f02f-48d5-8f4c-0203f5595072.jpg)

**Comment by playingleela** [comment]
here it is @laurenluz let me know if its what you meant ((: or if it needs any changes. The first one is for twitter post, the second is a website header and I will confirm now what is the size of this gitcoin banner so I can adapt to it

**Comment by markoprljic** [comment]
@playingleela you'd need to remove the giveth logo from the website header version because there's already logo in the main navigation.
Disregard the gitcoin banner size.

**Comment by playingleela** [comment]
thank you!! @markoprljic 
![GIVeconomy Banner 2 des  #158 (3)](https://user-images.githubusercontent.com/94190369/145208881-a1c03e2c-9e5a-4a18-8a49-b20d4838a3e4.jpg)
here it is

**Comment by laurenluz** [comment]
Looks awesome Catarina! Just quickly discussed w Marko... can you make the "Check your GIVdrop" text a little more prominent somewhere... then we will make the entire banner clickable & lead the user to the claim GIVdrop page

@playingleela

**Comment by playingleela** [comment]
![Twitter post 2 - GIVeconomy des  #158 (4)](https://user-images.githubusercontent.com/94190369/145236119-2dfe62d0-3b4f-44a4-9647-3f68081b3738.jpg)
![GIVeconomy Banner 2 des  #158 (5)](https://user-images.githubusercontent.com/94190369/145236179-6e2df831-0c74-4dc4-9140-7ab33058130c.jpg)
something like this @laurenluz ?

**Comment by playingleela** [comment]
the website header in the right size (:
![Header - GIVeconomy](https://user-images.githubusercontent.com/94190369/145238221-67f9fb93-de6a-4de3-9ee0-8b7e01c73b07.jpg)

**Comment by laurenluz** [comment]
Looks good to me! what do you think @markoprljic?

**Comment by laurenluz** [comment]
@playingleela can you add a link to this in the figma? then we can pass the issue to devs

**Comment by playingleela** [comment]
hey @laurenluz what is the URL that will be connected to it?

**Comment by markoprljic** [comment]
@playingleela @laurenluz I put the original button and slightly aligned the text on the banner.

![Image 2021-12-09 at 9 27 08 am](https://user-images.githubusercontent.com/5704285/145360921-17689e5b-6053-40fb-a1a7-c44876e6b241.jpg)

**Comment by laurenluz** [comment]
Looks good to me! @markoprljic what do you think?

**Comment by markoprljic** [comment]
Yes.

**Comment by laurenluz** [comment]
Weird. Sorry github didn't show me your comment before. Thanks to both of you!

**Comment by markoprljic** [comment]
@laurenluz Let's wait for @rodricastillo9013 to upload his proposal because he had something that is more aligned with our brand style.

**Comment by rodricastillo9013** [comment]
Hello, I share these designs based on what was asked of me! I await your feedback! Thank you
![GIVeconomy Banner](https://user-images.githubusercontent.com/61791380/145440320-2e33e158-7ccf-4c5e-9614-f692e1ff7338.png)
![GIVeconomy Banner-1](https://user-images.githubusercontent.com/61791380/145440328-4409f707-dcff-46c6-bd4f-9ef5de03a0cf.png)

**Comment by markoprljic** [comment]
I'd approve the first one. It is more consistent with our brand style. fyi @laurenluz

**Comment by laurenluz** [comment]
Sorry, which one?? This one?

![image](https://user-images.githubusercontent.com/75490971/145504949-d522e7ce-6d84-4405-b0e8-b0f02860d336.png)

**Comment by markoprljic** [comment]
Yes
