### ISSUE TITLE
GIVdrop should have awareness if the address already claimed

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#159]
This address was eligible to claim, but I already claimed. It shouldn't say "You missed the GIVdrop" (as below). This should say "You already claimed" as per the figma: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=741%3A62550

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/2b9b934e-e2f0-47fc-a21b-d4775a65b36b)

**Comment by pkretzschmar** [comment]
@laurenluz done!
