### ISSUE TITLE
When I staked my sushi LP tokens for GIV/WETH, my rewards were negative!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#161]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ac8c9a94-80d0-45ef-9d21-80f0a396be54)

**Comment by aminlatifi** [comment]
That's because your machine clock is behind and that causes your current time to be before the last update time of unipool. So the time difference (current time - last update time) is negative and reward rate is multiplied to that negative number!

**Comment by laurenluz** [comment]
just harvested from my GIVstream and the value went negative again

![image](https://user-images.githubusercontent.com/75490971/145821067-8bf290c0-6b7c-48f0-992a-4d19c520b528.png)

@aminlatifi

**Comment by laurenluz** [comment]
@aminlatifi it seems that the claimable and streaming amounts on the cards in the GIVfarm don't go into the negative, but on the GIVstream, it still does

**Comment by aminlatifi** [comment]
> @aminlatifi it seems that the claimable and streaming amounts on the cards in the GIVfarm don't go into the negative, but on the GIVstream, it still does

@laurenluz I pushed an improvement. Can you test it again?

**Comment by WhyldWanderer** [comment]
My GIVstream rewards are also showing negative
![image](https://user-images.githubusercontent.com/74267818/146040133-15241a43-986d-499b-86bb-e615884270d6.png)
