### ISSUE TITLE
GIVeconomy Overview Text Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#162]
- [x] This should say "The GIVeconomy empowers our collective of projects, donors, builders, and community members to build the Future of Giving." ....

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e6aa7127-bb59-4d9d-9230-25e356d6e989)

- [x] This should say "Giveth is rewarding and empowering those who give to projects, to society, and to the world!"....

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/30e0f30d-5cc2-4237-99cf-82f426366f04)

- [x] This should say "Claim your GIVdrop" ....

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/55d9b9b5-ada8-4509-ba61-be983c644658)

- [x] This should say "Claim your GIVdrop" ....

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c8b37931-7e78-4001-85c0-339c38669909)

**Comment by laurenluz** [comment]
- [ ] Should say "See farms"
![image](https://user-images.githubusercontent.com/75490971/145068482-213f8bdb-d61e-4dce-bc29-c62ccba040aa.png)

**Comment by WhyldWanderer** [comment]
Just a suggestion: We should steer away from using redundant wording. 

Maybe the main text should say "The GIVeconomy **enables** our collective of projects, donors, builders, and community members to build the Future of Giving." Instead of using "empowers" twice in the text.
