### ISSUE TITLE
GIVgarden - prompt user to switch to xdai if they are connected to the wrong network

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#167]
![Screen Shot 2021-12-02 at 9 09 35 PM](https://user-images.githubusercontent.com/13708322/144474605-ab496df9-dcbb-4301-93a9-7c217708f0f2.png)

_Originally posted by @mosaeedi in https://github.com/Giveth/GIVeconomy/issues/112#issuecomment-984850116_

**Comment by laurenluz** [comment]
@MohammadPCh this should be here:

![image](https://user-images.githubusercontent.com/75490971/145071414-bc024c4b-4ff0-45d3-b636-92cf26d48759.png)

if they user is on any other network than xDai

**Comment by mosaeedi** [comment]
@MohammadPCh 
[Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=2531%3A80592)

**Comment by laurenluz** [comment]
@mendesfabio I see that this is like this:
![image](https://user-images.githubusercontent.com/75490971/145465667-8fa64949-95b9-407e-a8de-3c459dda134e.png)

but that box should actually be here:

![image](https://user-images.githubusercontent.com/75490971/145465755-8f77c105-cbbc-46b9-b9d5-2cb24e3d5e06.png)

We want the user to be able to read all the content, but not see rewards unless they are connected to xdai
