### ISSUE TITLE
Harvest Modal Fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#168]
There should be a title here that says "Claimable from GIVstream". And let's remove the "?" tooltip

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/00bbde2d-e900-4e74-9fab-c2d689670252)

**Comment by laurenluz** [comment]
Also let's change the title to "Your Reward" for all the popups to make things simple

![image](https://user-images.githubusercontent.com/75490971/145076932-545ca1aa-d453-4b2b-bb78-af7c52d50d2e.png)

**Comment by laurenluz** [comment]
@MohammadPCh to make things consistent everywhere... for all harvest modals (GIVfarm, GIVgarden, GIVstream)... I noticed that for GIVfarm, they're called Your Reward, for GIVstream they're called GIVstream rewards... I think we just make it "Your Reward". So, for all:

- [ ] Title should be "Your Reward" with no icon
- [ ] Text at the bottom should say "When you harvest GIV rewards, all liquid GIV allocated to you in the token distro gets sent to your wallet."


![image](https://user-images.githubusercontent.com/75490971/145501446-a2660735-aa00-4a37-9eef-eef898097f5e.png)

**Comment by MohammadPCh** [comment]
Donw :)
