### ISSUE TITLE
GIVdrop: Merkle drop list

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#17]

**Comment by laurenluz** [comment]
After the distro is done an audited, we need to take the final numbers from the spreadsheet and make them into a Merkle tree. Apparantly @aminlatifi knows how!

**Comment by laurenluz** [comment]
just integrated last strategic partners... but will probably keep tweaking until the end with extra people who are helping.

decided not to do the combined addresses... so they have to claim with each address separately.

we have buffer to last minute add people as they support

**Comment by laurenluz** [comment]
algene and hannah as adding in missing addresses

**Comment by laurenluz** [comment]
@GriffGreen make sure you add our partners to the GIVdrop: https://giveth.io/partnerships
