### ISSUE TITLE
GIVdrop Change Wallet - clicking metamask doesn't give me another popup

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#170]
Wanted to change the connected wallet, so I changed in metamask and hit "change wallet". I got this popup and then when I click metamask, nothing happens.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f35e3885-99e4-4e68-b31d-9cfb2bede61d)

**Comment by pkretzschmar** [comment]
@laurenluz done!
