### ISSUE TITLE
GIVdrop - if the user "missed the GIVdrop" or already claimed - text fix

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#171]
The highlighted part should say "Explore anyway" and the arrow should bring them to the next page (right now it is not clickable)

@pkretzschmar 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a223b1ce-f40d-46cd-89dc-354eca0d31c7)

**Comment by pkretzschmar** [comment]
@laurenluz done!
