### ISSUE TITLE
GIVdrop frontend fixes - GIVfarm page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#172]
- [ ] should be a space in the "up to x% APR"
- [ ] add text above the APR card that says "If you stake for 1 month:"
- [ ] Remove title "GIV Staking"
- [ ] the APR on the calculator should be the highest APR in the GIVfarm
- [ ] the claimable amount should be calculated the APR & assuming the user is staking their inputted GIV amount for 1 month
- [ ] streaming amount also assumes the user has been staking for 1 month
- [ ] when click "Max" it should auto fill the box with the maximum GIV amount

@pkretzschmar @aminlatifi 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/352d3b57-36c3-4bf2-8896-4a21abdd4cd5)

**Comment by laurenluz** [comment]
Also let's hide the "calculator" icon & the "?" icon

![image](https://user-images.githubusercontent.com/75490971/145108049-82d434c2-0fea-4521-af63-61bfd3c90118.png)

**Comment by laurenluz** [comment]
@aminlatifi @pkretzschmar not sure between the two of you who can take this on

**Comment by pkretzschmar** [comment]
@laurenluz done!
