### ISSUE TITLE
GIVdrop frontend fixes - This needs to be a calculator like the GIVfarm page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#173]
Need to represent both the claimable and the streaming amount, so this should be the same as #172 but with the APR from the 100% GIVstaking pool.

It should also say "If you wrap GIV for 1 month:"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/b12e27c1-0cde-4948-b02b-42e017a59474)

**Comment by laurenluz** [comment]
This is what's missing:

![image](https://user-images.githubusercontent.com/75490971/145113993-39fa1114-e7ce-4c78-bb18-8323f9fd3752.png)

**Comment by pkretzschmar** [comment]
@laurenluz done!
