### ISSUE TITLE
GIVdrop frontend fixes - GIVbacks page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#174]
- [ ] The subtext should be "Donate to verified projects to get GIV with GIVbacks. The project gets 100% of your donation, and you get GIV back from Giveth!"
- [ ] This rewards section also needs to show the stream, I'm suggesting we use the same table from the GIVfarm page... change "APR" to "GIVbacks %" and have it set to be 75%
- [ ] the claimable and streaming amounts will be 75% of the donation amount split up to account for the claimable portion and the GIVstream part. @aminlatifi does this make sense to you?

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/821ccd93-32a4-4357-94b3-838cf9b59d5c)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fe46e66b-102d-45cc-8878-d6cd97512f7b)

**Comment by pkretzschmar** [comment]
@laurenluz done!
