### ISSUE TITLE
GIVdrop frontend fixes - GIVstream page

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#175]
The flowrate amount should be the user's initial GIVstream amount... so 90% of their total initially allocation / number of weeks in 5 years

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8ecaafb9-f8fa-4914-b3ea-a4fa8a607cc6)

**Comment by laurenluz** [comment]
@pkretzschmar these values are working in the GIVstream page of the deployment: https://liquidity-mining-dapp.vercel.app/

If you have any questions, for sure @MohammadPCh or @aminlatifi can help

**Comment by pkretzschmar** [comment]
@laurenluz done!
