### ISSUE TITLE
GIVeconomy Overview - Bring to top of page when a new section is selected.

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#176]
Each time I click one of these sections, it should bring me to the top of the page.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/dbdb75db-94fc-475e-aab4-40e8247e76dd)

**Comment by laurenluz** [comment]
you mean like... if you're on the GIVgarden page already and you click it, it should send you to the top of the GIVgarden page? or? @WhyldWanderer

**Comment by WhyldWanderer** [comment]
I mean like.. if Im on the GIVgarden page and I click the GIVbacks button, it should start me at the top of the GIVbacks page and not somewhere halfway down the page. Does that make sense?
