### ISSUE TITLE
GIVdrop: Make more responsive... not for mobile but at least for different brower sizes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#177]
@MohammadPCh & @mosaeedi need to sync of GIVdrop and ensure that it works for different screen sizes

**Comment by laurenluz** [comment]
@MohammadPCh 

We need to make the GIVdrop claim somewhat responsive. Not for mobile, but at least we need it to work on different screen sizes without getting cut off. Right now, things look crammed when you adjust your browser window smaler, and the navigation arrow gets cut off.

- Please watch from 1:35 to 2:40 https://youtu.be/g7TGEXJNAtM?t=95
- Please look at this picture from #265 

![image](https://user-images.githubusercontent.com/75490971/146274578-100a39e2-07e9-42fa-bc3e-c4ea65dd777a.png)

Can you help?

**Comment by MohammadPCh** [comment]
@laurenluz,
I will work on it today, I hope @mosaeedi and @markoprljic have idea about the design in smaller screens.
otherwise I can fix it in my way :smile:

**Comment by laurenluz** [comment]
Don't worry about making it work for mobile... just smaller windows.

And we don't worry about waiting on designs... we need to have this working and tested and complete by Monday so there's not so much time.

If @markoprljic has time to sync w you today, great, but if not, please go ahead how you see fit :)

**Comment by markoprljic** [comment]
@mosaeedi is working on it. Will be done.

**Comment by mosaeedi** [comment]
Updated.

**Comment by GriffGreen** [comment]
Nice!

**Comment by divine-comedian** [comment]
looks to be much more responsive - the smaller versions (mobile) still needs some work but I can see in the comments that this will be for later.. 

the only issue I found was on the claim/stake page - you could remove some of the bottom margin from the header element when the screen is less than 1150px wide 
![image](https://user-images.githubusercontent.com/67759413/146992117-b40abbfa-c755-4803-8ba4-0728f9768d1a.png)

**Comment by laurenluz** [comment]
boom
![image](https://user-images.githubusercontent.com/75490971/147291222-9cd9518d-22a0-43e1-8e7e-5a0c82425751.png)
