### ISSUE TITLE
GIVdrop claim page - Mouse curser should change when hovering over "check" button

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#183]
When I claim my GIV drop, I first connect my wallet and then when I go to click "check" the mouse should change to let me know that this is a clickable button.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/2fd2e448-e820-43b5-9add-1565fc2599fa)

**Comment by laurenluz** [comment]
fixed already
