### ISSUE TITLE
GIVdrop claim flow - "govern" & "donate" section text alignment

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#187]
On the "govern" section of the GIVdrop claim flow, if I type in a large number the text starts to overlap with the design elements.

![image](https://user-images.githubusercontent.com/74267818/145238065-1723889a-e049-4b24-9102-dbcb1504ac57.png)

**Comment by WhyldWanderer** [comment]
This also happens on the "donate" section
![image](https://user-images.githubusercontent.com/74267818/145239481-8a811189-2bda-4eda-935c-004fb645b2ce.png)

**Comment by laurenluz** [comment]
wow crazy. also, fixed in the new deployment
