### ISSUE TITLE
Text fixes - GIVdrop claim flow - "donate" section 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#188]
Donors can donate any type of currency to get GIVbacks right? This text is confusing..

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/f4ea3d05-578c-4625-bbca-1ae02418c44a)

It should say "Donate to get GIVbacks!"
And the subtext should say "Give to verified projects on Giveth to earn more GIV."
Or something like that.

**Comment by laurenluz** [comment]
this is changed in the new design already
