### ISSUE TITLE
Text fixes - GIVdrop claim flow "Stream" section

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#189]
Text should say "Welcome to **the** ever-expanding GIViverse. A GIVstream of 16.4 GIV/day will be streamed continuously until September 21, 2026. Increase your flowrate by earning more GIV!"

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/47868444-dc3a-4566-883d-8ea257e0e820)

**Comment by WhyldWanderer** [comment]
Also, I think this was meant for the "donate" section. Do we have text already written for the "stream" section?

![image](https://user-images.githubusercontent.com/74267818/145240510-9c0817b6-1508-444f-ab81-0978b627797f.png)

**Comment by laurenluz** [comment]
Yeah 😕 this is again because you were looking at the old version. you can see the new one here: https://develop-liquidity-mining-dapp-h289r25p4-givethio.vercel.app/claim

Fixes are still in progress!
