### ISSUE TITLE
GIVdrop claim - "Congratulations" page after claiming

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#191]
After I successfully claimed my GIVdrop, the screen remained the same. There should be something to let the user know that their claim was successful... maybe confetti and a message that says "Congratulations! You have successfully claimed your GIVdrop!" and provide a link to the GIVeconomy overview page so that users can start using their GIV tokens.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/7e5ab637-ac47-4588-beb0-eaefadec89b9)

**Comment by laurenluz** [comment]
Thanks Ashley - there is one! It just needed some fixes.

@pkretzschmar please implement

![image](https://user-images.githubusercontent.com/75490971/145483247-6cdfa9ff-b062-41f6-ba20-ad73c7717f00.png)


https://www.figma.com/file/IqRt6vng4NNgeT50FUu1Py/GIVEconomy-(Lauren%2C-Willy-%26-Griff)?node-id=7061%3A18197

Link for "Explore the GIVeconomy" should be the GIVeconomy overview page: https://liquidity-mining-dapp.vercel.app/ (this will have to update though, after launching to the production version)

"Join our discord": http://discord.giveth.io/

"Share on Twitter" should lead them to make a tweet:

> The #GIVeconomy is here! Excited to be part of the Future of Giving with $GIV & @givethio 💝  #blockchain4good #defi4good #givethlove #givdrop
>
> https://liquidity-mining-dapp.vercel.app/

But yeah also that link in the tweet will need to change...

**Comment by pkretzschmar** [comment]
@laurenluz done!
