### ISSUE TITLE
Text Fixes - "What is a GIVstream" Modal 

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#192]
The text here is confusing:
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/dc913b31-cb1c-43a8-a78b-e344437043f0)

Should say "When you claim your GIVdrop or harvest GIV rewards, a portion of your GIV is sent directly to your wallet and the rest are added to your GIVstream flowrate. As time passes and the GIVstream flows, a larger portion of the total GIV you earn is sent directly to you. The GIVstream flows until December 24, 2026 at which point the GIVeconomy will be in full power!"

**Comment by laurenluz** [comment]
good fixes Ashley - I can show you how to submit a PR for these
