### ISSUE TITLE
Staking in the Uniswap farm pop-up fix

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#194]
Once I have successfully staked my NFT in the ETH/GIV uniswap v3 pool, I get a blank pop-up.
![image](https://user-images.githubusercontent.com/74267818/145304940-fc07f71e-d4f5-47db-8df4-dd6263f2c518.png)

When I stake into the other pools successfully, I get this pop-up.
![image](https://user-images.githubusercontent.com/74267818/145304973-15405917-b76f-4da3-b9e2-10a75896891d.png)

All pop-ups should be uniform and have a confirmation message like "transaction confirmed" or something. Its kinda weird to just have a blank pop-up.

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/146022088-efbbe3c5-9edf-4155-809b-f7c7dc2ec765.png)
