### ISSUE TITLE
GIVeconomy - GIVbacks round description text fixes

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#195]
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/d3221ace-4aab-49e0-8863-4a2698c80fab)

Text should say "Each GIVbacks round lasts 2 weeks. After the End Date, the GIV allocated to that round is distributed to Givers who donated to verified projects during the round. Projects must apply for verification at least 1 week prior to the Start Date in order to be included in the round."

**Comment by laurenluz** [comment]
Great fixes - I'll show you how to make a PR and you can make the change :)
