### ISSUE TITLE
GIVfarm - Missing txHash on Etherscan link 

### ISSUE THREAD

**Issue by mendesfabio** [Giveth/GIVeconomy#196]
![image](https://user-images.githubusercontent.com/43360747/145391939-5e2037e8-5801-482d-9e49-92dc437b2feb.png)

**Comment by laurenluz** [comment]
@mendesfabio did you fix this?

**Comment by laurenluz** [comment]
for me it is working now

**Comment by mendesfabio** [comment]
@laurenluz I didn't and it's still not working for me.. where it worked for you?

**Comment by laurenluz** [comment]
it's working for me when I claim from GIV staking and from the GIV/ETH balacer pool 🤔

**Comment by mendesfabio** [comment]
oh yeah it seems to be working on claiming but not on staking
