### ISSUE TITLE
Links in "What is GIVstream?" modal are broken

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#197]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/9a0a7025-e6c4-4137-8b20-eae0131a2c8c)

**Comment by laurenluz** [comment]
- [ ] View your GIVstream should go: https://liquidity-mining-dapp.vercel.app/givstream
- [ ] remove "read more"
- [ ] make "View Your GIVstream" center-aligned

**Comment by laurenluz** [comment]
related to #192 & #209

**Comment by laurenluz** [comment]
This is working properly on all the other pages except the GIVstream page 

On the GIVstream page... the "View your GIVstream" button should just close the popup so the user can see their GIVstream again.

On all other pages, it's correct... linking to the GIVstream page

![image](https://user-images.githubusercontent.com/75490971/145645474-14a63c51-ab04-44f4-b48d-f9bcafd63839.png)
