### ISSUE TITLE
Implement new header to match giveth.io

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#198]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/94fdc94f-dcb7-4808-aab6-6b290ecabbbd)

If the user was on a wrong chain, it wont show up in header and the app don't have any switch network button.

**Comment by laurenluz** [comment]
I think this can be resolved by implementing the same work @RamRamez has done in: https://github.com/Giveth/giveth-next/pull/452
