### ISSUE TITLE
Staked Number in GIVfarm is wrong comparing what we have in Gardens

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#205]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/3971a195-056c-4f05-9ba0-59b236d0c01c)

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/9bccc6b0-b405-4f48-991c-419acbac71d9)

**Comment by laurenluz** [comment]
For me it is the same... @MoeNick did you give it a minute for the UI to update after staking?

![image](https://user-images.githubusercontent.com/75490971/145461438-ca20d022-4a88-4cbd-bf75-94d8447ed49b.png)

![image](https://user-images.githubusercontent.com/75490971/145461469-1e575841-fdfa-494c-8012-c7da09138d4e.png)

**Comment by MoeNick** [comment]
It solved after @aminlatifi latest release I think. but lemme test it again

**Comment by MoeNick** [comment]
It is fixed I think. But what is the rounding logic? I put some decimals to see if there is a deferent, and it was I think. 

![image](https://user-images.githubusercontent.com/80677512/145463374-c05bcf3c-c7c9-413f-a940-af8e152cb2e1.png)

![image](https://user-images.githubusercontent.com/80677512/145463407-b35992f4-9e69-460d-bae0-33385c1d57c8.png)
