### ISSUE TITLE
Final GIVgarden deployment - Ask Fabri to change rewards page link

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#206]
Pictures are Taken in same time: 

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/06d3744f-e6f1-49b5-924f-48f46cd862db)

![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/0aaa636e-3d0e-455d-92fa-b22aceb846ce)

**Comment by laurenluz** [comment]
When you click "Claim" in the garden, it should link you to: https://liquidity-mining-dapp.vercel.app/garden (right now the link is not up to date: #108)

The "earned" amount should match the "GIVgarden rewards" claimable amount

![image](https://user-images.githubusercontent.com/75490971/145456777-6d628d15-304e-48c6-925d-00cc231b8f7f.png)

![image](https://user-images.githubusercontent.com/75490971/145456934-9fb7c1f7-722d-401d-b099-14085d11591b.png)

I think the numbers are working correctly (my computer is just behind...), but we need to update the link in the garden.

**Comment by laurenluz** [comment]
When we deploy the new Test Garden, Fabri will put in the correct link to send the user from "claim" to our "GIVgarden" hub. Changing this issue's title so we remember to ask him to change it.

**Comment by MoeNick** [comment]
I did not claimed, my problem was something else.

**Comment by laurenluz** [comment]
from your screenshots @MoeNick you are comparing "GIVfarm rewards" with "GIVgarden rewards. these numbers should not be the same, so from my understanding your issue was more about the UI being confusing
