### ISSUE TITLE
GIVstream: None of these links are working

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#207]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/0a1b725a-fa28-4fd4-8d34-d8d0c0ecd45c)

**Comment by GriffGreen** [comment]
Same...

**Comment by laurenluz** [comment]
GIVE AND EARN should go to: https://giveth.io/projects

SEE OPEN PROPSALS should go to our garden... this is the current link, but it will have to be changed when we launch the new garden: https://gardens-staging.1hive.org/#/xdai/garden/0x2050eabe84409e480ad1062001fdb6dfbc836192

STAKE AND EARN: should go to the GIVfarm page... this is the current link, but it will have to be changed when we launch the real deployment: https://liquidity-mining-dapp.vercel.app/givfarm
