### ISSUE TITLE
GIVstream: in pop up explainer we should correct the date to December 24th 2026

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#209]
<img width="229" alt="Screen Shot 2021-12-09 at 10 19 00 AM" src="https://user-images.githubusercontent.com/14945613/145434419-945a9346-61dd-47e6-be1a-633891a0cf80.png">

**Comment by laurenluz** [comment]
https://github.com/Giveth/liquidity-mining-dapp/pull/17

https://github.com/Giveth/liquidity-mining-dapp/pull/16
