### ISSUE TITLE
GIVeconomy Overview - None of these links are working

### ISSUE THREAD

**Issue by freshelle** [Giveth/GIVeconomy#211]
![image](https://user-images.githubusercontent.com/86718721/145439031-35b0b3b0-f20c-4db0-81d1-ce9d9bcd6a4b.png)

**Comment by laurenluz** [comment]
Related to #207 

"Donate to projects" should go to: https://giveth.io/projects

"See proposals": should go to our garden... this is the current link, but it will have to be changed when we launch the new garden: https://gardens-staging.1hive.org/#/xdai/garden/0x2050eabe84409e480ad1062001fdb6dfbc836192

"Add liquidity and Earn": should go to the GIVfarm page... this is the current link, but it will have to be changed when we launch the real deployment: https://liquidity-mining-dapp.vercel.app/givfarm
