### ISSUE TITLE
Add to Tx confirmed popups: "it make take a few minutes for the UI to update"

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/GIVeconomy#212]
Had to reload the page to get it to update. 
I think it's important that it updates a bit faster, people could get desperate and click multiple times claim and keep getting the gas cost on their wallet taken.

**Comment by laurenluz** [comment]
Can we add to all "Transaction confirmed" popups:

"It may take a few minutes for the UI to update"

@mendesfabio - make it subtext between "transaction confirmed" and "view on blockscout"

![image](https://user-images.githubusercontent.com/75490971/145476518-6281c7d4-4293-443a-9f93-4d4c4bb85a8d.png)
