### ISSUE TITLE
Clicking wallet Balance in top corner should not open a metamask transaction!

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#213]
There's this number with the GIV symbol - not clear what it is. 

![image](https://user-images.githubusercontent.com/67759413/145442633-8b6a7ab3-3821-471d-ac65-7005cb7cbef1.png)

when I click it it opens a metamask transaction - I have no context what it's trying to do so it seems kinda spooky that it instantly tries to make a transaction - because I'm familiar with MM I can see it's trying to claim but for unfamiliar users it could be confusing

I would suggest removing the metamask transaction and add a hover tootip  "GIV currently in wallet" so it makes more sense.

**Comment by laurenluz** [comment]
@mendesfabio 

Love Mitch's suggestions here. Two tasks:
- [ ] remove metamask tx... this shouldn't happen... this is not supposed to be for claiming anything.
- [ ] add tooltip hover that says "GIV currently in wallet"

**Comment by laurenluz** [comment]
FYI some details of the header will have to change to match giveth.io. This issue is still applicable though.

@RamRamez is working on the new header: https://github.com/Giveth/giveth-next/pull/452

Related to #198

**Comment by laurenluz** [comment]
@mendesfabio the tx is still happening when I click the wallet balance in the top corner 😕

**Comment by mendesfabio** [comment]
@laurenluz could you hard refresh and try it again? it's not happening here

**Comment by laurenluz** [comment]
super weird... it is still happening for me... and for griff too
![image](https://user-images.githubusercontent.com/75490971/145661271-81695991-5f3f-4236-be4b-568a5039b1db.png)

**Comment by laurenluz** [comment]
After a hard refresh and a clean cache
