### ISSUE TITLE
Test GIVbacks for Trace campaigns

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#214]
- [x] archive TRACE campaigns according to this spreadsheet: 
Yellow = Archive
Green = Verified and eligible for GIVbacks https://docs.google.com/spreadsheets/d/1rtOYGUaxXUZIk4nhaVcyZqiPWoxiRfuaQG821xl3duA/edit?usp=sharing
(you may need to request access)

- [ ] Test GIVbacks functionality for listed verified campaigns

**Comment by mohammadranjbarz** [comment]
> * [x]  archive TRACE campaigns according to this spreadsheet:
>   Yellow = Archive
>   Green = Verified and eligible for GIVbacks https://docs.google.com/spreadsheets/d/1rtOYGUaxXUZIk4nhaVcyZqiPWoxiRfuaQG821xl3duA/edit?usp=sharing
>   (you may need to request access)
> * [ ]  Test GIVbacks functionality for listed verified campaigns

First item got done in https://github.com/Giveth/giveth-next/issues/493

We will test the second one
