### ISSUE TITLE
Create "Purple List" for GIVbacks program

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#215]
We need to create a list of addresses that are not eligible to receive GIVbacks

I have collected all addresses used for fund management from projects that have applied for verification on giveth.io.

I have collected some of the wallet addresses used for campaign fund management on TRACE.

What is the plan for creating this list and how can I help to provide the information that Ive already collected?

I have a spreadsheet that I can share as long as people are careful not to make changes or share it publicly anywhere.....

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer 
Can you share this spreadsheet with me?
mranjbar.z2993@gmail.com

**Comment by mohammadranjbarz** [comment]
It has been done https://github.com/Giveth/givback-calculation/commit/97fdbf2bb5d4eb032538ad0894859437ce96bb6f
and now it's deployed on https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback
