### ISSUE TITLE
GIVfarm: Rounding on numbers

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#217]
what is the rounding logic? I put some decimals to see if there is a deferent, and it was I think. 

![image](https://user-images.githubusercontent.com/80677512/145463374-c05bcf3c-c7c9-413f-a940-af8e152cb2e1.png)

![image](https://user-images.githubusercontent.com/80677512/145463407-b35992f4-9e69-460d-bae0-33385c1d57c8.png)

_Originally posted by @MoeNick in https://github.com/Giveth/GIVeconomy/issues/205#issuecomment-990168300_

**Comment by laurenluz** [comment]
looks good to me! in the garden they're rounding to whole numbers

did you experience some issue? @MoeNick
