### ISSUE TITLE
Let me know what is going to happen after I click on GIV button on the top. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#219]
As a user I click on that GIV on the header and I see my wallet needs a transfer confirmation. 
Seems it's harvesting. 
A modal or a notification to a user may help.

**Comment by laurenluz** [comment]
yeah this is totally not supposed to happen, will close this in favour of #213 so we can keep the discussion in one place.

I don't want to add the rewards menu... it's too much extra devving before launch. We can make the rewards menu fast follow since it is already in the design
