### ISSUE TITLE
GIVgardens: Test Gardens on xDAI

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#22]

**Comment by DonnaOftadeh** [comment]
Currently the xdai on rinkeby hasn't launched yet, and in the link below there is neither a Giveth garden added nor a button to create garden! Donna should figure it out:

https://gardens-xdai.1hive.org/

**Comment by laurenluz** [comment]
Our GIVgarden on xDai is here https://honey-pot-o49n5fgrn-1hive.vercel.app/#/garden/0x79c52e1a74d01cf030f3cbbbbf84b01476c9ac93

**Comment by laurenluz** [comment]
Lauren to deploy new garden
