### ISSUE TITLE
Comment out ALL $ values

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#222]
I'm tellin' yah. this is going to be *way too much work* to test and fix.

Right now, the text colour is also too similar to the background colour to see it.

Please comment out *all* USD value equivalent EVERYWHERE.

We can all them in as fast follow

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f32f2c4a-7f90-44ed-b170-ec198d973d06)

**Comment by MohammadPCh** [comment]
@laurenluz  I think all prices are hidden now. Does any price remain?

**Comment by laurenluz** [comment]
looks great!!
