### ISSUE TITLE
It took a REALLY long time after I switch network for my rewards to appear the first time

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#225]
It took about 45 seconds.... I switched from mainet to xdai and everything said 0 for like 30-45seconds... then the UI updated with my numebers.

Now, since it's loaded, it's switching & showing the correct numbers much faster, but this was too long... I think this is either a bug or some kind server overload...

**Comment by laurenluz** [comment]
@aminlatifi then I tried claiming from GIVgarden staking, then ETH/GIV on sushi quickly... one after the other..

then it glitched and everything went to 0 for like 30s

![image](https://user-images.githubusercontent.com/75490971/145592745-ffb3f909-1387-449e-992b-81ccb109b78e.png)

**Comment by laurenluz** [comment]
After I unstaked too... from the middle pool on kovan, it took a really long time to update... just said I had zero everything

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/57a044c8-a022-4cd0-b409-d23b7926ba0c)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a9d91a6e-30fa-469b-bc95-83a713fb1ee2)

**Comment by aminlatifi** [comment]
> After I unstaked too... from the middle pool on kovan, it took a really long time to update... just said I had zero everything
> 
> ![image.png](https://camo.githubusercontent.com/791b4e809baa6af12bdd3ecf5b8ee0cf3e72a3c7ae4e3228727a974af536ca50/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566646661633136613538353233613836366464623638642f35376130343463382d613032322d346364302d623430392d643233623739323662613063)
> 
> ![image.png](https://camo.githubusercontent.com/177c11253351af836cabff062f1886c804a1057c998374b960f2d95c04150cc6/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566646661633136613538353233613836366464623638642f61396439316136652d333066612d343639622d626339352d383361373133666231656532)

It's strange. Do you have tx hash of the one you unstaked by?

**Comment by aminlatifi** [comment]
@laurenluz I refactored the code and made updating numbers faster than before. Can yo you test it again?
