### ISSUE TITLE
GIVgarden staking in our GIVfarm inconsistent wording...

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#229]
On the card it says "stake" "unstake"

Then when you click to stake... you have to "approve", then "stake" then it says "wrap pending"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/de856f78-6ae8-4213-ba43-0aa54725454c)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/97e9c577-ddb0-4eed-9a6d-11b9781c962b)

This is confusing for sure....

**Comment by divine-comedian** [comment]
I can change this to say STAKING...

**Comment by laurenluz** [comment]
@divine-comedian I made you an owner of Giveth so you should have more power now

Yeah, please change it to stay "Stake Pending"

![image](https://user-images.githubusercontent.com/75490971/145652501-7783907e-fe21-43f2-a1c8-a8d60d4088dd.png)

**Comment by divine-comedian** [comment]
nice! should be updated in the latest commit on `develop`
