### ISSUE TITLE
GIVdrop preview testing issues

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#233]
- [x] Stake Page APR should be the largest from the GIVfarms
- [x] Claimable and streaming values are not calculating correctly

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4a4919c9-bba1-4062-806e-7a98c8a5b82b)

- [x] Govern Page should say "If you wrap for 1 month:"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9bd3fa3e-b2b6-4eca-a82b-359fedecdce8)

- [x] Donate Page should not say "If you stake for 1 month:"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a849cb1a-7e79-478e-8ec6-3b22d2eca854)

- [x] Remove "?"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/7f19812a-6d36-4476-9c1b-1fd641bd2f0e)

- [x] Add GIV to Metamask button isn't working

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/472c75c7-d251-4f39-bfca-ab6c6dbfe0b1)

**Comment by laurenluz** [comment]
- [ ] Join the GIVeconomy should link to: https://liquidity-mining-dapp.vercel.app/
![image](https://user-images.githubusercontent.com/75490971/145653089-280b7ed4-a32c-4764-93cc-2b620f206ec6.png)

**Comment by laurenluz** [comment]
- [ ] Donate page Max button isn't working
![image](https://user-images.githubusercontent.com/75490971/145654893-bfbae039-a08f-46c7-8b88-853aed1468f4.png)

**Comment by pkretzschmar** [comment]
@laurenluz done!
