### ISSUE TITLE
If I'm trying to claim for an address with a wallet I'm not connected to, I should get an error message

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#234]
If I check the eligibility for an address that had a drop... but I'm not connected to that wallet address... when I click "Claim 2500 GIV tokens" a popup should say:

"Please connect to the eligible wallet address on xDai: `THE ADDRESS THE PERSON PUT IN ON THE FIRST PAGE`"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/d269c66f-0f2a-4089-83a9-81e8fb47da4f)

**Comment by pkretzschmar** [comment]
@laurenluz done!
