### ISSUE TITLE
Add tooltip to GIVgarden staking card

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#235]
Tooltip should be when you hover over "GIVgarden Staking" (at the top... text fix pending #148)

"Earn rewards on 100% GIV here by wrapping your tokens. Wrapped tokens can be used to vote on proposals in the GIVgarden"

Maybe we mention that you get gGIV... maybe we link to more info....

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ed4ed440-f2f4-4dc6-9a12-549a9a43b6dd)

**Comment by laurenluz** [comment]
"by staking in this pool, you can vote in the GIVgarden"

**Comment by divine-comedian** [comment]
mostly done just need to update some design assets in the `ui-design-system`

**Comment by divine-comedian** [comment]
pending in PR https://github.com/Giveth/liquidity-mining-dapp/pull/99

**Comment by laurenluz** [comment]
looks good.
