### ISSUE TITLE
GIVdrop - if the user missed the GIVdrop or already claimed, they should not be able to explore the pages (many fixes)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#236]
## If they missed the GIVdrop

- [x] Remove "Explore anyway" and yellow arrow
- [x] Change subtext to "But there are more ways to get GIV! Try another address or donate to verified projects to get **GIV back**.
- [x] Make "GIV back" bolded and link it to https://liquidity-mining-dapp.vercel.app/givbacks

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e0e3cefb-1a89-47c6-97dd-1b1c22b1a7db)

## If they already claimed

- [x] Remove "Explore anyway" and yellow arrow
- [x] Link "Join the GIVeconomy" to https://liquidity-mining-dapp.vercel.app/

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/781c2de7-a408-4a85-8441-6229c5afd74b)

## For both cases

- [x] Make all the other buttons at the top unclickable!

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/f85bbd95-8e37-4609-8cc4-66d8479d93d3)

**Comment by pkretzschmar** [comment]
@laurenluz done!
