### ISSUE TITLE
GIVdrop input field - I can't type "0.1" or ".1" or "2.1"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#238]
I should be able to type in decimals on each of the following pages input fields:
- [x] Stake
- [x] Govern
- [x] Donate

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/69ef053b-ea5b-48e7-a47c-eca54a4ea6f0)

**Comment by pkretzschmar** [comment]
@lauren done!
