### ISSUE TITLE
Deploy external test garden on xDai

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#24]
Implement external token by modifying Boboli garden, which inherited some unipool distributor functionalities, to handle our vesting system
 
[This is the boboli garden that may be used for giveth:](https://1hive.gitbook.io/gardens/garden-creators/create-a-garden/create-a-garden-with-scripts/create-boboli-garden)
Create Boboli Garden

(https://1hive.gitbook.io/gardens/garden-creators/byot-garden-wrapping-incentive)

**Comment by laurenluz** [comment]
For context, we were previously going to use an "internal garden" that uses its own token. Now we will use an external token (created on ethereum), so we need an "external garden" where, all tokens used in the garden must be "wrapped".

@aminlatifi is working on reploying a token on Rinkeby that matches the output of the xdai bridge so we can use it as the token in the garden.

@0xGabi is a great person to support on this

**Comment by aminlatifi** [comment]
Our minime token has issue, we may use another token as we don't need minime capabilities any more. I will deploy a new token like the one which has minimal features and test again

**Comment by 0xGabi** [comment]
Cool, once @aminlatifi has the token deployed we can go ahead and create a new Boboli Garden. We are finishing the final details on the Onboarding so potentially you will be able to do it yourself from the UI.

**Comment by laurenluz** [comment]
we're doing this today!!

**Comment by aminlatifi** [comment]
I prepared the new GardenUnipool which should be compatible with Garden and have the feature of variable reward rate. We need to add tests to be more confident about correctness, and then replace the garden again.

**Comment by aminlatifi** [comment]
I updated the Garden Unipool and it seems ok :)
Only the Garden UI should consider the new Unipool address and the garden's one
