### ISSUE TITLE
When my wallet is not connected in GIVfarm it doesn't show the pools

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#243]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/145803464-891a6509-9f3a-4614-9fa6-c9437abf3806.png)

**Comment by laurenluz** [comment]
fixed now 
![image](https://user-images.githubusercontent.com/75490971/145916314-fd96c8c4-d0bf-463a-940e-95797a81b112.png)
