### ISSUE TITLE
APR modal should say "What is a GIVstream"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#250]
missing the "a"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/380a5a9e-573f-4848-8e79-b9e9c432d0c0)

**Comment by divine-comedian** [comment]
resolved in https://github.com/Giveth/liquidity-mining-dapp/commit/aa362efc1132e5d822bb2371792d107008041cb3
