### ISSUE TITLE
GIVfarm harvest most text fix "GIVfarm Rewards"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#251]
On all GIVfarm harvest modals should says "GIVfarm Rewards" as the title

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/fcf2583c-c76f-46ef-a18c-a0b6678286c9)

**Comment by divine-comedian** [comment]
resolved in https://github.com/Giveth/liquidity-mining-dapp/commit/aa362efc1132e5d822bb2371792d107008041cb3
