### ISSUE TITLE
Unstaking an NFT, I get an endless "waiting for confirmation"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#252]
it's been several minutes... also you can see that my unstake was successful underneath

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/949cfa06-782a-4026-9aaf-f9e2b94aa78d)

**Comment by laurenluz** [comment]
the staking worked fine, however

**Comment by WhyldWanderer** [comment]
This is happening to me also
![image](https://user-images.githubusercontent.com/74267818/146053211-445d2a96-2276-446f-a945-365a09691dd5.png)
