### ISSUE TITLE
Not getting a "Transaction submitted" or "transaction confirmed" after unstaking from any pool

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#253]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/402d39e9-12e8-4107-8dcf-e3b89743a1e1)

**Comment by laurenluz** [comment]
when I unstake from the 100% GIV staking pool, it is also not giving me the tx pending and confirmed popups

**Comment by laurenluz** [comment]
I want to see this everytime I unstake from any pool: 

![image](https://user-images.githubusercontent.com/75490971/146023937-8aecd077-0564-476f-bd89-9af53dccf222.png)


![image](https://user-images.githubusercontent.com/75490971/146023872-49cde79c-d8f1-495f-b577-2d0c49459be3.png)

**Comment by laurenluz** [comment]
@mendesfabio this still isn't working on https://liquidity-mining-dapp.vercel.app/givfarm

**Comment by divine-comedian** [comment]
tested unstaking from all farms on xdai and kovan - the transaction successful and transaction pending modals show up everytime! 
![image](https://user-images.githubusercontent.com/67759413/147131450-c745a043-2876-4315-aa8a-01fd5417212b.png) looks to be resolved!
