### ISSUE TITLE
NFT univ3 pool - transaction submitting and transaction pending modals need to be consistent with others

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#254]
## What it is now:
 
"I click stake" then while metamask popup is open I get this.... ![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/baf15522-1f52-408e-bfb5-341106239c1a)

which stays until I get this....
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/ad6bb9ec-e1ea-4c52-a44e-0411f0234530)

## What it should be:

When I click stake or unstake... this becomes "stake pending" or "unstake pending", I get the metamask popup...
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/448d56a6-a831-42a8-8119-fc508390aec1)

once I confirm in metamask... the tx is submitted and I get this... Note that the title should be GIV/ETH (not ETH/GIV)
![image](https://user-images.githubusercontent.com/75490971/146023937-8aecd077-0564-476f-bd89-9af53dccf222.png)

then when it goes through I get...
![image](https://user-images.githubusercontent.com/75490971/146023872-49cde79c-d8f1-495f-b577-2d0c49459be3.png)

**Comment by divine-comedian** [comment]
I noticed as well that the modal says the transaction is confirmed before the transaction actually confirms on metamask 

![image](https://user-images.githubusercontent.com/67759413/146050557-c2855f81-a437-43d3-af1d-c3938de0282b.png)

**Comment by laurenluz** [comment]
@mendesfabio this one also isn't working on the main deployment

**Comment by laurenluz** [comment]
## They're still bigger than the others:

![image](https://user-images.githubusercontent.com/75490971/146704379-01a283b2-6227-4287-89da-550039f3059e.png)

![image](https://user-images.githubusercontent.com/75490971/146704409-c782d3ef-ad9f-422f-a9c7-b81abf41279b.png)

## Can we make them like this?

![image](https://user-images.githubusercontent.com/75490971/146704453-af648061-7839-4a26-85a1-2a96e782a153.png)

![image](https://user-images.githubusercontent.com/75490971/146704496-26f27749-cd85-4498-88e6-822ed06c52d3.png)

**Comment by divine-comedian** [comment]
testing on staging 

when staking and unstaking my NFT I can see the state changes of the button and it says pending - however as mentioned in another issue the pending button is too wide .. 
![image](https://user-images.githubusercontent.com/67759413/146989188-83c9ffc7-5787-4d52-a3db-6979c4a68a43.png)

checking the size of the transaction pending and transaction successful modals they look to be brought in line to be consistent with the rest - 
![image](https://user-images.githubusercontent.com/67759413/146989283-ed7cef4b-cf15-4a56-8321-d4e3d836bae4.png)


just need to fix that button size @mendesfabio

**Comment by mendesfabio** [comment]
https://github.com/Giveth/liquidity-mining-dapp/pull/64 will fix this issue.

**Comment by divine-comedian** [comment]
@mendesfabio when this is merged please update so it can be tested

**Comment by laurenluz** [comment]
fixed!

![image](https://user-images.githubusercontent.com/75490971/147183375-6d49e891-de68-4d89-bb95-700bdc64ff8e.png)
