### ISSUE TITLE
GIVdrop - connect wallet button should detect if I have a GIVdrop available

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#257]
when I'm on the GIVdrop page and I click connect wallet I expect that it checks automatically if I have a pending GIVdrop - instead if just fills in the text box next to it, this is confusing because the text reads `connect wallet` **OR** `*check wallet address`

Ideally when I click connect wallet it would check automatically if that address has a GIVdrop instead of having to connect wallet then click `check` 
![image](https://user-images.githubusercontent.com/67759413/146048997-aa8c25c9-2bad-48be-82b1-099d6d86c6e2.png)

**Comment by pkretzschmar** [comment]
@laurenluz done!

**Comment by divine-comedian** [comment]
hey @pkretzschmar  testing on `develop` 

I still need to connect wallet and then click `check` - a two step process to check my GIVdrop eligibility 

ideally i can just click `connect wallet` and the modal updates informing of GIVdrop eligilbity **OR** I can check an address using the text field next to it - in either case it should be a one step process.

**Comment by pkretzschmar** [comment]
Did you tested on the deploy preview link? Because I just tested again, and its working as you asked, or kind of, because @laurenluz detected a bug on it.

**Comment by divine-comedian** [comment]
https://liquidity-mining-dapp.vercel.app/claim ?
