### ISSUE TITLE
I cant erase the zero in the calculators in the GIVdrop flow

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#258]
I am unable to erase the zero... 

![image](https://user-images.githubusercontent.com/74267818/146048412-fc429e94-6143-477c-b519-1b92fd91cc81.png)

I can only type additional numbers and the zero stays there..

![image](https://user-images.githubusercontent.com/74267818/146048675-932e9c56-d298-4edb-b136-b077a202e930.png)

**Comment by WhyldWanderer** [comment]
This is also happening on the govern and donate pages as well

**Comment by pkretzschmar** [comment]
@laurenluz done!
