### ISSUE TITLE
Calculator disclaimer message should be removed from the stream page of the GIVdrop claim flow

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#260]
The stream page does not have a calculator on it but it still has this message...
Maybe we should remove it from this page since there is not calculator.

![image](https://user-images.githubusercontent.com/74267818/146049444-59c2c733-2901-4272-8334-dbc70041f6e8.png)

**Comment by pkretzschmar** [comment]
@laurenluz done!
