### ISSUE TITLE
Default input values should be Max in the GIVdrop calculators instead of 0

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#262]
I'm very open to being wrong with this... maybe we want people to put numbers in the calculator?

I assume 20% of people will bother to play with the calculators

What should they see?

this is what they see now
![Screen Shot 2021-12-14 at 11 54 23 AM](https://user-images.githubusercontent.com/14945613/146053308-4d217154-b9fd-4ae6-8574-e87b3e5e89f9.png)

This is what they would see if the default was Max

![Screen Shot 2021-12-14 at 11 54 31 AM](https://user-images.githubusercontent.com/14945613/146053261-2a1f2352-6b5d-485f-a15f-e3039d247baa.png)

**Comment by laurenluz** [comment]
I think this is a great idea.

@pkretzschmar for all pages (stake, govern & donate) please have the default input amount be their maximum.

**Comment by pkretzschmar** [comment]
@laurenluz done!
