### ISSUE TITLE
Final Page on GIVdrop has a few issues

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#265]
<img width="1270" alt="Screen Shot 2021-12-14 at 12 22 48 PM" src="https://user-images.githubusercontent.com/14945613/146057364-17ee17e2-2894-4d9a-844c-8c451b71bab4.png">

- [ ] The box on the left thats like a previous screen shouldn't be visible at all... it would look better if it was gone
- [x] Getting an additional xx per week, this needs to be the stream amount
- [x] Make the Shirt White It looks weird in color... it could be sharper too
- [x] Each link needs to open in a new window... i clicked the twitter one and now i can't get back to that page!
- [x] Add Commas for both the numbers 
- [x] Add a hyperlink of "Claim from another address" underneath the GIVeconomy button that redirects to the front page
- [x] First line should say "You have successfully claimed x GIV" (not "GIV tokens").
- [x] Add metamask fox icon (so the user can add the token to their metamask) next to "You have successfully claimed x GIV" and make it trigger the "add to metamask" in their wallet.
- [x] Make sure subtext alignment looks good (after we delete the word "tokens").

**Comment by pkretzschmar** [comment]
@laurenluz @GriffGreen The first checkbox is a bit complicated, because involves dealing with the responsiveness of the app, and it can take a lot of time.

**Comment by laurenluz** [comment]
Nice!!!! Well this is great, I tested on the preview and everything else is good. forget about the first checkbox.
