### ISSUE TITLE
Users that change their address but don't connect it to the dapp get lost and stuck

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#267]
Its so hard! We get stuck.. if you dismiss the "Connect Wallet" page that metamask first pops up, then you end up with a different address connected than is live on your Metamask

![Screen Shot 2021-12-14 at 1 10 50 PM](https://user-images.githubusercontent.com/14945613/146063928-7766dbb8-3fb1-42bf-873a-83001aba60e1.png)

^^^ Addresses don't match

We have to be careful NOT to over dev on this... I think we can solve it with documentation on how to connect the wallet instead.

Have a Hyperlink text of "What if this address doesn't match the address in my wallet" (or something shorter)

That sends them to a page in the docs that tells them that they need to connect their wallet to the dapp.

It should also be considered a potential issue with the claim button... so if they click the claim button and it doesnt work, they should make sure that they are on xDai, and connected to the right wallet.. these are the only 2 reasons that button might not work.

**Comment by laurenluz** [comment]
@divine-comedian can you keep an eye on this one? if we need documentation, maybe that can be in the GIVdrop tutorial

**Comment by divine-comedian** [comment]
added in a small section to the GIVdrop claim tutorial https://hackmd.io/jRfk1T_ER76xFPtveA74Lg#If-you-get-stuck-in-the-GIVdrop-claim

when this goes live I can provide a direct link to the section in the docs

**Comment by divine-comedian** [comment]
@pkretzschmar  here's a link you can add directly on the page for users to learn more about troubleshooting getting stuck - https://docs.giveth.io/giveconomy/givdrop/#if-you-get-stuck-in-the-givdrop-claim

**Comment by laurenluz** [comment]
added this to #366 since Cherik was working on it already, moving to done since it's covered there
