### ISSUE TITLE
Couple small changes on the GIV Claim Button click page

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#268]
![Screen Shot 2021-12-14 at 1 23 50 PM](https://user-images.githubusercontent.com/14945613/146065637-0a681d60-6607-4a92-ac00-d03190f580f6.png)

- [x] "Claim your GIV tokens now!" should be "Claim your GIV now!"
- [x] "Claim x GIV tokens" should be "Claim x GIV"

**Comment by pkretzschmar** [comment]
@laurenluz done!
