### ISSUE TITLE
GIVdrop last page: Small text overlap

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#270]
![Screen Shot 2021-12-14 at 1 31 39 PM](https://user-images.githubusercontent.com/14945613/146066690-38fe0602-079f-4ac4-ba15-d853b42c8b50.png)
here:
![Screen Shot 2021-12-14 at 1 32 04 PM](https://user-images.githubusercontent.com/14945613/146066746-ecf91b1f-5067-4c7a-84a0-3937b50361ff.png)

**Comment by GriffGreen** [comment]
This happens only when the claim amount is over 100k... but when we add a comma it might make it worse... make sure it doesnt over lap when someone is claiming 1,000,000 with commas

Connected to #265

**Comment by pkretzschmar** [comment]
@laurenluz done!
