### ISSUE TITLE
Make the "Congratulations page" the page you get to if you re-connect an address that's already claimed

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#272]
There are a lot of buttons and cool things to do on the congratulations page... would be nice if the user could get there more easily again. Can we replace the current "you already claimed" with the congratulations page?

## What is is now:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/47c44c1a-ef5c-43d9-af47-ec55c66805bb)

## What I want it to be:

Same as this... but also with the fixes as per #265
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/080b3926-5e73-4093-9ed8-96a1dfa83068)

**Comment by pkretzschmar** [comment]
@laurenluz done!
