### ISSUE TITLE
GIVdrop: Add Harvest Modal to GIVdrop! (oops)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#274]
The user's GIVstream starts flowing from day 1, so if they're claiming a week after we do the GIVdrop, the amount that shows up in their wallet when they claim their GIVdrop will be more than just the GIVdrop... because their GIVstream was flowing...

we need to add this popup, the harvest modal from the app to the GIVdrop claim.. and we need the top section to be from the GIVdrop...

there may also be something from GIVbacks

there will definitely be something claimable from GIVstream

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cff86314-5fe6-4921-ab37-92f2596a4c06)

**Comment by laurenluz** [comment]
Hey @pkretzschmar just want to make this more clear...

Harvest model should have the following, the rows from top to bottom shall be:
- [ ] Title: GIVdrop
- [ ] box showing GIVdrop amount
- [ ] small text saying "you initial GIVstream flowrate"
- [ ] lightning bolt & the GIVstream flowrate that they get from the drop

then! do a check if they have GIVbacks to claim... if not, this part is not show. if so the next lines should say:

- [ ] Claimable from GIVbacks
- [ ] box with the claimable from GIVbacks amount
- [ ] "Added to your GIVstream flowrate"
- [ ] lightning both and the GIVstream flowrate amount coming from GIVbacks. 

Last, they should have something Claimable from GIVstream... so the last lines should be 
- [ ] Claimable from GIVstream
- [ ] box showing the GIVstream amount

Then the footer as shown with the "When you havest GIV disclaimer". harvest button and cancel button

FYI these "check if they have GIVbacks" things should already be in the code of the harvest modal, so you shouldn't have to do this extra work.

![image](https://user-images.githubusercontent.com/75490971/146272786-c0499064-1a24-4165-ae9d-7db323222bec.png)

**Comment by MohammadPCh** [comment]
Hey @laurenluz ,
we have a general component called HarvestAll modal (the modal you see in all harvests).
I try to write it generally.
I thinks the only thing we need is to add givedrop support to this modal.

**Comment by divine-comedian** [comment]
lauren tested! this is done!
