### ISSUE TITLE
Remove "in the token distro" from all harvest modals

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#275]
![image](https://user-images.githubusercontent.com/75490971/146077033-057003b6-a5f6-4ed2-a94c-be3f94879fb2.png)

**Comment by divine-comedian** [comment]
resolved! 
https://github.com/Giveth/liquidity-mining-dapp/commit/7d7af785ed20cad1ef5c8752cec905697f7a044d
