### ISSUE TITLE
GIVbacks rounds dates are incorrect in the subgraph

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#277]
Hey @mohammadranjbarz,

@marthendalnunes has been working on #247 and is fetching the round dates from the subgraph... they're not correct though.

We'll have GIVbacks round 1 start on December 24, 2021 at 9am (costa rica time) and end on January 7, 2022 at 8:59am (costa rica time)

Then round 2 starts on January 7, 2022 at 9am (costa rica time)

Can you please help Vitor investigate what the problem could be? the timezones look like they're working correctly but the dates are wrong.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0f9cf3b2-a1bf-4bed-9cbd-80b10e579232)

**Comment by mohammadranjbarz** [comment]
@marthendalnunes 
Could you give me what queries are you using for showing these data?

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
Do you know what's the issue?

@MohammadPCh  said they use `tokenDistroContractInfos` function from subgraph, and as I see the `startTime` from subgraph query is equal with the value that we get from smart contract directly, maybe we should use other parameters

![Screen Shot 1400-09-24 at 12 31 06](https://user-images.githubusercontent.com/9850545/146155880-a36872ef-3a8a-41a3-8c8c-53cb7fa0930e.png)


https://blockscout.com/xdai/mainnet/address/0x1aD46D40648639f84a396Fef32132888038c5aA8/read-proxy
![Screen Shot 1400-09-24 at 12 30 57](https://user-images.githubusercontent.com/9850545/146155872-0a174060-9b5c-4568-8e03-638827f49e7c.png)

**Comment by laurenluz** [comment]
ok @marthendalnunes so to summarize, we should use only the launch date & time from the subgraph and then just do an extra calculation to add 2 weeks and having the rounds tick up every 2 weeks.
