### ISSUE TITLE
GIVdrop (preview testing) - before I could connect my metamask, the GIVdrop told me "I missed the GIVdrop"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#278]
## what is happening

I tried connecting my wallet to "check my GIVdrop" (on an address that had already claimed)... and before metamask could connect to it (before I could sign the tx in the popup), it said "Your missed the GIVdrop!"

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/252873e9-f1e5-4cea-8d56-69e92da2824c)

when it actually connected, it then said (correctly)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c0199e07-e529-43fa-bde1-096e5454bafc)

## What should happen

When the tx is pending in metamask, I should just see the "connect wallet thing" with a "pending" modal on top

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/3d03ec23-b4c7-4d4a-b330-eaaab2073efe)

**Comment by pkretzschmar** [comment]
@laurenluz done!
