### ISSUE TITLE
Somehow we should make it clear that this is a Univ3 pool on uniswap

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#279]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e0beec2d-0ab1-470d-82ad-70fc783f076f)

**Comment by mendesfabio** [comment]
Adding 'V3' to the title solves the issue and IMO makes sense. Uniswap V2 and V3 are very different products.

**Comment by laurenluz** [comment]
Sounds good! can you do it?
