### ISSUE TITLE
GIVdrop - missing `X` or `go back` button to return to GIVeconomy overview

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#282]
in the GIVdrop page there is no way to exit the page and go back to the GIVeconomy overview - except hitting `go back` via the browser - maybe add an `X` to exit the GIVdrop flow and return to the GIVeconomy page? 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/090ab273-1cd3-4b90-acc0-3f5967776804)

**Comment by laurenluz** [comment]
Change button text to "GO TO GIVECONOMY"

**Comment by divine-comedian** [comment]
okay okay new one - 

I am a user who didn't get a GIVdrop - how do I get out of this page? 

![image](https://user-images.githubusercontent.com/67759413/146190727-db51efe0-abee-4f4f-992b-72f3194d552e.png)

Also can we change the copy on this - `Try another address or donate to verified projects to qualify for **GIVbacks**.

**Comment by laurenluz** [comment]
I'm cool with that copy change - can you do it?

The way you get out of the page is actualy by clicking "GIV back"... that sends you to the GIVbacks page. You don't like it? Not clear enough?

Open to suggestions

**Comment by laurenluz** [comment]
I think the x is weird.. will be hard to place effectively in a way that makes sense with the flow... but maybe we can add a small yellow text thing under the "Change wallet" button that says

"Go to GIVeconomy" and links to the overview page

**Comment by divine-comedian** [comment]
I don't think its intuitive enough - there should be a more clear way to go back to the overview page

**Comment by laurenluz** [comment]
You don't think "Go to GIVeconomy" is clear enough? Then let's do "Explore the GIVeconomy". 

the x doesn't make sense... the claim is a separate page, not a popup/modal covering the GIVeconomy. plus it doesn't really fit with the rest of the GIVdrop flow. the user could arrive at this page without first coming from the GIVeconomy page

**Comment by divine-comedian** [comment]
Nooo I mean in this specific case where the **user missed the GIVdrop this screen is what shows on the claim page** - 

![image](https://user-images.githubusercontent.com/67759413/146550200-936b9e3c-6080-4cbc-960c-13ac42b4d5a5.png)

the only way to proceed is by clicking `GIVbacks` which doesn't come off obviously as a button to go to another page - 
the only other option on the page is to `CHECK WALLET` - the user should have a button like in the case where they already claimed that will take them back to the overview page -

**Comment by laurenluz** [comment]
yeah.... I suggested this...

> I think the x is weird.. will be hard to place effectively in a way that makes sense with the flow... but maybe we can add a small yellow text thing under the "Change wallet" button that says
>
>"Go to GIVeconomy" and links to the overview page

**Comment by laurenluz** [comment]
To be more clear, the place where I circled here... let's add plain yellow text here that says "Go to GIVeconomy" and links to the overview page. 

![image](https://user-images.githubusercontent.com/75490971/146553037-d4c68c04-67aa-4cd6-a4bd-2399448148ab.png)

**Comment by divine-comedian** [comment]
okay awaiting this PR - https://github.com/Giveth/liquidity-mining-dapp/pull/48

**Comment by divine-comedian** [comment]
nice - we add in the little link so users have a way to go back in case they missed the GIVdrop - 
![image](https://user-images.githubusercontent.com/67759413/147147350-3e78bb80-61ff-4642-9aa4-70ceb73a5e05.png)

moving to done
