### ISSUE TITLE
GIVbacks page comms - make it more clear that Givers and getting governance rights

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#284]
Some of the text on this page should make that clear

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5f554270-5865-4352-86ed-6a60e45b5bfb)

**Comment by divine-comedian** [comment]
LIVE 
![image](https://user-images.githubusercontent.com/67759413/146398210-4b145ed7-f06a-45b1-92b9-3f7977cf9547.png)
