### ISSUE TITLE
GIVfarm: Add GIVdrop to harvest modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#288]
If the user hasn't claim their GIVdrop (maybe they don't know they have one!) and then go to claim GIVbacks.... the GIVdrop should show up as an entry on the harvest modal (because it will be going to their wallet)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/632dc953-6a95-4541-8b0f-816f7124cb7e)

**Comment by laurenluz** [comment]
related to #274

**Comment by laurenluz** [comment]
@MohammadPCh we can leave this one for later... it's not critical for launch. please prioritize #177

**Comment by MohammadPCh** [comment]
@laurenluz 
Yesterday I add a endpoint to check user has GIVdrop ot not.

**Comment by aminlatifi** [comment]
@laurenluz @MohammadPCh harvesting from a farm or claiming (stream released value or givback) don't make givDrop be claimed!

**Comment by MohammadPCh** [comment]
@aminlatifi @laurenluz  we can just show an alert in harvest modal when user has not claimed givdrop. when user clicked on it redirct her to claim page.

**Comment by aminlatifi** [comment]
> @aminlatifi @laurenluz we can just show an alert in harvest modal when user has not claimed GIVdrop. when user clicked on it redirect her to claim page.

Good idea, BTW I don't think anyone misses givdrop and meanwhile stakes GIV :)

**Comment by laurenluz** [comment]
Yeah good idea! Please go ahead w that @MohammadPCh 

Also @aminlatifi I think the most likely possible scenario where we could need this is when someone donates to a verified project, gets GIVbacks, receives and email saying to claim and only then realizes about the GIVdrop...

Not very likely, but if it happens, this addition will explain to the user what's happening

**Comment by MohammadPCh** [comment]
@laurenluz, Could you please give me UX writing for this alert?
