### ISSUE TITLE
GIVeconomy - logo beside the tab on the top should change to Giveth logo

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#295]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/146221191-9b71a2ca-d468-4057-a621-2af4380fdd2f.png)

**Comment by laurenluz** [comment]
@mendesfabio can we make that a Giveth logo?

![image](https://user-images.githubusercontent.com/75490971/146278665-ee72bdc2-ca4b-4c5b-bc59-86d9d1cc7bc2.png)

![LOGO_MARK_01_Blue](https://user-images.githubusercontent.com/75490971/146278708-792bd649-ee47-448f-9cdd-f4e7bbd817db.png)
