### ISSUE TITLE
GIVfarm - GIV/ETH pool - When enter the pool using koven network the view on etherscan link doesn't work

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#296]

**Comment by laurenluz** [comment]
what does this mean? when staking in the GIVfarm on kovan?

**Comment by DonnaOftadeh** [comment]
yep - when stake in ETH/GIV pool - when transaction is complete - on the pop up the "view on Etherscan" link doesn't work! for some unknown reason the screenshot hasn't been attached I attach it

**Comment by laurenluz** [comment]
it's been fixed
