### ISSUE TITLE
GIVfarm- Loading - should have GIV logo and a text showing the current process: staking, harvesting,....

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#297]

**Comment by DonnaOftadeh** [comment]
THis is on staking:
![image](https://user-images.githubusercontent.com/53400757/146223997-99228642-70a7-4253-b14c-5b49cb76ed29.png)
This is on harvesting:
![image](https://user-images.githubusercontent.com/53400757/146224294-9da7ce5d-d023-47aa-aa12-8d2eda60815b.png)

**Comment by laurenluz** [comment]
covered in #253 - the GIV logo animation is being worked on by Rodri
