### ISSUE TITLE
When staking GIV, it should just say "Available X GIV" not "GIV LP"

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#298]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/146226397-0fa69d69-73ec-4cb3-b1f8-d59bcdde589a.png)

**Comment by laurenluz** [comment]
@divine-comedian can you fix this on mainnet and xdai?

**Comment by divine-comedian** [comment]
resolved in https://github.com/Giveth/liquidity-mining-dapp/pull/44
