### ISSUE TITLE
Donated 50 Dai between two projects but got no givBacks.

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/GIVeconomy#301]
My wallet connected: 
![image](https://user-images.githubusercontent.com/92376054/146274855-97b70d31-ac57-4d77-8afb-120b6bc19e0e.png)

Actions taken to receive GivBacks
Carlos:
My wallet: 0x317bbc1927Be411CD05615d2Ffdf8d320C6C4052

Network: XDAI
1. Project: https://giveth.io/project/regenerating-sonora
- Unverified:
    - Donated 10 xDai twice: 
tx: 0xee0510337bbb104e8ca36acc67e9bd07a864ca7fbb1ca78eb6256eb0b1f5bb06
tx: 0x707f8de10255cdc6403de344f53f82e370d8f4b2cc654f9e3acc225f8acb4e5c
    - Donated 5 xDai three times:
tx: 0xcbf1dd2352400c178fd12451c1cc54a836c05e870c9203061a3986218ff16314
tx :0x7638c20b1a22cd073cd570dc73f3d25973620580a6f363876987c83f2fd33bf6
tx :0x6bfee8a5bae0bdae58ada43b99bc67959f20e673342debf60abc96c8c41706f7
- Verified:
    - Donated 1 xDai: 0xafc5b1ea11cb72a0eea8c320fd6da00de1a10591f7595fe0c8d2817deb5dd67d

2. Project: https://giveth.io/donate/free-solidity-development-course-in-farsi
Unverified:
 - Donated 5 xDai 
tx: 0xae21ad6d52f02af99e216a0890524d7dcff1906a6999d9b885d37edef2ff174d
Verified: 
 - Donated 1 xDai: 0x6ad767d72d25eb60ca91d4a3fe1ea1370560d58ac22b8cc8fbefd6f34cf5fa53
 - Donated 8 xDai: 0x192def3d15688f85007a56984d9ebb48d1e1e2de1724768f9d104eb0ad8c7d68

**Comment by laurenluz** [comment]
thanks for this awesome summary Carlos! it turns out we tried to distribute GIVbacks from an old token distro, so no one got them. you should get them another day... we're trying again. I will tag everyone :)
