### ISSUE TITLE
Remove "?" from harvest modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#304]
This "?" should be removed (the disclaimer is at the bottom)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/606d6666-0e2c-469a-8c30-be3c44acbf69)

**Comment by laurenluz** [comment]
waiting on @mohammadranjbarz or maybe @aminlatifi to distribute me some DRGIV from GIVbacks so I can actually test this

**Comment by mohammadranjbarz** [comment]
> waiting on @mohammadranjbarz or maybe @aminlatifi to distribute me some DRGIV from GIVbacks so I can actually test this

I think, I dont have access to sendGivbacks anymore and I dont know what the DRGIV is, so maybe Amin should teach how can I send it
