### ISSUE TITLE
fix Expected server HTML to contain a matching <button> in <a> error

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/GIVeconomy#307]
We have an error in console that should be resolved:
![Screenshot from 2021-12-16 12-10-11](https://user-images.githubusercontent.com/17097576/146337262-a4f328e6-22f8-4e2c-934b-4e6801dbfc9b.png)

**Comment by divine-comedian** [comment]
this is on the overview page - looks to be resolved! nice 
![image](https://user-images.githubusercontent.com/67759413/147135673-b936b697-7fc0-4439-8c78-d47eff75f726.png)
