### ISSUE TITLE
fix reward card change network when use wallet not connected

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/GIVeconomy#308]
When user wallet not connected we show him to switch his wallet to xDai or Mainnet. but they are not working because the wallet is not connected.
![Screenshot from 2021-12-16 12-12-39](https://user-images.githubusercontent.com/17097576/146337882-682f0347-e279-4d29-9774-129948535dd5.png)

**Comment by MohammadPCh** [comment]
@laurenluz @aminlatifi  when use click on them, they switch the network but they nothing changed!
So my suggestion before change the network check user wallet and if it's not connected we should ask him to connect wallet first.

**Comment by laurenluz** [comment]
Great idea

**Comment by laurenluz** [comment]
Nice, this is looking good.
