### ISSUE TITLE
New Deployment... GIVdrop add to metamask is adding the old token

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#314]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/139686ac-ae8c-49f2-a59b-e4ba60c476ce)

This should be DRGIV: 0x7aAde4907a8e2412BEACbE42E51aaeE5B6085f24
We need to make sure this "add to metamask" is adding the appropriate token from the disto

**Comment by divine-comedian** [comment]
the token address is subject to change! the address should be included in an env variable somewhere 
currently still deploying new tokens and contracts so will have to check on the latest test deployment which token to use - https://www.notion.so/giveth/Testing-Deployment-218c3f503a04421ba3f51e438f4d6acf

**Comment by laurenluz** [comment]
@pkretzschmar @divine-comedian can we move this done? is it using an env variable that is unique to that deployment? or does it still need to be manually updated?

**Comment by GriffGreen** [comment]
Its linking to the right token now
