### ISSUE TITLE
New GIVeconomy deployment - needs new links

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#317]
The "provide liquidity" links for both the GIV/HNY and GIV/ETH are still linked to the TESTGIV pool and not the DRGIV pool.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/66943928-3703-4095-8381-51218d2b4c4d)

The GIV/HNY pool should link to: https://app.honeyswap.org/#/add/0x7aAde4907a8e2412BEACbE42E51aaeE5B6085f24/0x69F79C9eA174d4659B18c7993c7EFbBbB58cF068

The GIV/ETH pool should link to: https://app.sushi.com/add/0x736a98655049433f79dCcF5e54b887E8890b63D1/0x7aAde4907a8e2412BEACbE42E51aaeE5B6085f24

**Comment by laurenluz** [comment]
@MohammadPCh do you think you could fix these to be the correct links before the test parties tomorrow? details are in the deployment notion

**Comment by laurenluz** [comment]
![image](https://user-images.githubusercontent.com/75490971/146565662-5666e71b-ccce-4194-8d3b-5f1f31f4fa85.png)
shoudl link to:

https://gardens-staging.1hive.org/#/xdai/garden/0xbf2d7d659e45bb0ded75d89eaf5f267fd1ce0ade

**Comment by laurenluz** [comment]
It would be good if we could have everything connected to the configuration so we don't need to manually update each link with the new deployment.

Can you please go through the GIVeconomy and make sure that all the links like "provide liquidity" are not hard-coded, but connected to the deployment configuration.
