### ISSUE TITLE
GIVdrop claim amount text fixes.

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#318]
Fix the smart contracts so i get 10x more pleeeez 

Well... or.. i guess we fix the front end :-/

<img width="796" alt="Screen Shot 2021-12-16 at 8 48 55 PM" src="https://user-images.githubusercontent.com/14945613/146481026-b62a97d1-09ea-419e-9e4a-20fa53d41ce5.png">

https://blockscout.com/xdai/mainnet/tx/0x500ffa5af0efe6ee5e5ec0bce1bf7ca61a1bf1d04106c38640bf4d4f7117c737

**Comment by laurenluz** [comment]
@pkretzschmar the frontend is off by a factor of 10. His claim amount should be 862,005.54

Also... some text fixes:

- [ ] please add commas
- [ ] GIVdrop should be accurate to 2 decimal places

**Comment by laurenluz** [comment]
@pkretzschmar I've asked Cherik to fix up the numbers, but if you can make these text fixes, would be great.
