### ISSUE TITLE
Test backend of GIVfarm end to end

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#32]

**Comment by DonnaOftadeh** [comment]
@aminlatifi dear Amin can you please set a quick hack sess with Mateo on what is already implemented and how he can test it ? please update this card as you progress :) and @aminlatifi can you please update the story points

**Comment by aminlatifi** [comment]
@DonnaOftadeh For sure, the UI/UX is minimal and is just for testing the smart contracts functionality. All the functionalities of farming, claiming and givdroping should work after this. To break down:

- GIV Drop
- Claiming streamed released money
- APR calculation
- Staking
- Unstaking
- Harvesting farm

The most important part is the APR, @mateodaza if you need any help on that please let me know
