### ISSUE TITLE
Add text to univ3 pool to make it explicitly 0.3%

### ISSUE THREAD

**Issue by Zeptimus** [Giveth/GIVeconomy#323]
![image](https://user-images.githubusercontent.com/74430951/146562507-0791c22e-5e04-4b70-9e66-852f834fbb0c.png)

![image](https://user-images.githubusercontent.com/74430951/146562647-b8ea1e11-a193-4d49-a397-2d0e3d24cb5b.png)

@laurenluz

**Comment by laurenluz** [comment]
It's because your NFT is in the 1% fee tier. It needs to be the 0.3% fee tier.

We should make this clear by adding the text "Uni V3 0.3% tier"

@divine-comedian

**Comment by divine-comedian** [comment]
resolved in pending PR - https://github.com/Giveth/liquidity-mining-dapp/pull/50
