### ISSUE TITLE
GIVgarden link is still linked to TestGIV instead of DRGIV

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#324]
This button should link to https://gardens-staging.1hive.org/#/xdai/garden/0xbf2d7d659e45bb0ded75d89eaf5f267fd1ce0ade
![image](https://user-images.githubusercontent.com/74267818/146565283-1c6499cc-4c34-43f2-8d4f-65f34781ec03.png)

It is still linked to the old TestGIV garden..

**Comment by WhyldWanderer** [comment]
Same with this button:
![image](https://user-images.githubusercontent.com/74267818/146568653-5c5b706a-b7b5-4f01-abcc-afe6f87b41a6.png)

**Comment by laurenluz** [comment]
This is the correct link: https://gardens-staging.1hive.org/#/xdai/garden/0xbf2d7d659e45bb0ded75d89eaf5f267fd1ce0ade
