### ISSUE TITLE
Testing: When doing claim GIVdrop tells me I have missed the drop

### ISSUE THREAD

**Issue by rpiesveloces** [Giveth/GIVeconomy#325]
My wallet: 0x1b858E7391C3feB82b3E28CaF0B1C882A87F1FFA
Link: https://liquidity-mining-dapp.vercel.app/
Click on Claim your GIVdrop.
Gives message: You missed the GIVdrop
But there are more ways to get GIV! Try another address or donate to verified projects to qualify for GIVbacks.

My balances (if it matters):

4.9986 xDai
699.995 DRGIV
0.994 TestHNY
0.999 TestWETH

**Comment by GriffGreen** [comment]
I will add you to the GIVdrop ;-) 0x1b858E7391C3feB82b3E28CaF0B1C882A87F1FFA

**Comment by GriffGreen** [comment]
Added and will collect the addresses of other Testers! Thank you! Great issue!
