### ISSUE TITLE
The link in the garden is still linked to the old token

### ISSUE THREAD

**Issue by nauzystan** [Giveth/GIVeconomy#327]
If I try to create a proposal, it asks me to deposit 5000 GIV tokens. When I click on Get Test GIVtokens, it takes me to Honeyswap I still have to swap my xDai tokens for it. So basically, the link to the new token should be added to the gardens page.

**Comment by laurenluz** [comment]
From the active garden: https://gardens-staging.1hive.org/#/xdai/garden/0xbf2d7d659e45bb0ded75d89eaf5f267fd1ce0ade/

Get DRGIV

![image](https://user-images.githubusercontent.com/75490971/146612676-bbf328fe-ccf5-4cd0-bd8c-f84a14ea5bf7.png)


Links to https://app.honeyswap.org/#/swap?outputCurrency=0x7aade4907a8e2412beacbe42e51aaee5b6085f24

as it should.

I think perhaps you were using the link from https://liquidity-mining-dapp.vercel.app/givgarden which is indeed wrong and covered in issue #327
