### ISSUE TITLE
GIVdrop - communications improvements on GIVbacks "Donate" page

### ISSUE THREAD

**Issue by liviade1** [Giveth/GIVeconomy#330]
do you donate GIV and get 75% back in GIV? Seems like there is info missing

**Comment by laurenluz** [comment]
This page is confusing to people! Some communications things to make it less confusing.... 

- [ ] (1) Subtext should be "Donate to verified projects to get GIV with GIVbacks. The project gets 100% of your donation, and you get rewarded by Giveth with GIV!"
- [ ] (2) This text should be "If you donate your GIVdrop"
- [ ] (3) Get rid of the 75% number (still use 75% to calculate the amounts, but don't show it in the UI). Change "Claimable" to "GIVbacks"... make this box smaller to fit
- [ ] (4) Add "?" next to "Your donation" - make this a tooltip! The tooltip should say "Note: Donations made in most tokens are eligible for GIVbacks."
- [ ] (5) Change the title to "Donate & get GIV back"

![image](https://user-images.githubusercontent.com/75490971/146605822-30990412-c2dc-4068-beb3-1a15d99a5208.png)

**Comment by divine-comedian** [comment]
pending in PR: https://github.com/Giveth/liquidity-mining-dapp/pull/52
