### ISSUE TITLE
UI update is slow when interacting with farms on xDAI

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#331]
When staking my GIV / HNY LP, Harvesting or Unstaking - the values takes at least a  full minute, usually longer, to update on the UI after the transaction is confirmed on the network. 

This means that my claimable, staked and unstaked LP amounts take a long time to update and as a user I'm confused if the transaction went through since it takes a long time for the numbers to update 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/04877af9-29b5-40f7-b165-913254dd5f13)

**Comment by aminlatifi** [comment]
subgraph (thegraph) nodes sometimes are a few minutes behind the latest block! that leads to events being processed late and consequently, our numbers will not be updated immediately. I and @mohammadranjbarz

**Comment by aminlatifi** [comment]
@divine-comedian I applied some changes in our subgraph and deployed the new version. That probably will solve the issue of tardiness.

**Comment by aminlatifi** [comment]
Thanks @mohammadranjbarz for following up the issue on thegraph discord.

**Comment by divine-comedian** [comment]
testing on staging - I went through and tested  unstaking, staking and harvesting on all farms on xDAI - everything was super fast in updating on the UI - within seconds from when the transaction was passed.

**Comment by aminlatifi** [comment]
> testing on staging - I went through and tested unstaking, staking and harvesting on all farms on xDAI - everything was super fast in updating on the UI - within seconds from when the transaction was passed.

Thanks @divine-comedian . So I close it and if it happens again we could reopen this issue.
