### ISSUE TITLE
GIVfarm: Harvest Modal in GIVfarm is giving me the wrong info "Claimable from GIVdrop"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#332]
I'm claiming in the GIVfarm... it says "Claimable from GIVdrop" at the top....

I haven't claimed my GIVdrop... so maybe this should be instead at the bottom.. and it should show the amount.....

@MohammadPCh please let's discuss this

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/624d94cb-36ff-4f32-af1c-0a899b0a2d47)

**Comment by divine-comedian** [comment]
testing this out on staging this is the current modal that shows up when I harvest rewards in the givfarm on xdai - 
![image](https://user-images.githubusercontent.com/67759413/146986921-fda2683c-6f61-446b-8f9e-a9583b0fd097.png)

this doesn't quite follow the commented photo in the issue - not sure what was decided in conversations out of this issue - 
@laurenluz  can you verify this is what you were expecting?

**Comment by laurenluz** [comment]
It looks right! The GIVdrop should only show up if you hadn't claimed yet.

I haven't claimed w my address yet so can test this to be sure later, but if you claimed already, that looks correct
