### ISSUE TITLE
GIVdrop - when I'm not connected the xDai network, it shows my GIVdrop, but the calculators are showing 0s

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#333]
There should either be something saying:
- "switch to xDai network", or
- the numbers on the calculators should be showing up.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/a8ca435b-a1b1-4471-82ad-1bae5d9d0e12)

**Comment by GriffGreen** [comment]
This was not intending to rely on xDai... this is why we wanted to avoid connecting the calculators to the actual Distro numbers @aminlatifi @pkretzschmar 

We have 2 options, 

- [ ] Revert back to just using a hard coded 10% for the GIVdrop (my preferred)
- [ ] Stop the user at the first calculator with a pop up that won't let them see the calculators until they switch to xdai

Let's do the fastest solution, @pkretzschmar which is faster?

**Comment by GriffGreen** [comment]
Sounded like Option 2 was the winner
