### ISSUE TITLE
Givdrop: TX  link after a successful claim not working (other parts of this issue are done :-D)

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#334]
Related to https://github.com/Giveth/liquidity-mining-dapp/pull/49

- [ ] The link is not working to blockscout... its not putting in the tx hash:
![Screen Shot 2021-12-17 at 11 19 49 AM](https://user-images.githubusercontent.com/14945613/146583284-32128a38-2219-44ff-b8ce-87bbf464b7c5.png)

https://blockscout.com/xdai/mainnet/tx/undefined

-------------Done-------------

- [x] Numbers are right basically but it should be that 10% is the GIVdrop, and Some amount is claimable for the stream, there should be 2 boxes with numbers of GIV. One from GIVdrop, one from GIVstream.

It is important that the Stream and the GIVdrop are DIFFERENT CONCEPTS! this is a Comms Requirement

<img width="491" alt="Screen Shot 2021-12-17 at 11 15 32 AM" src="https://user-images.githubusercontent.com/14945613/146582639-f0477bc7-9c3d-4513-8e1a-9e5dd19b1f55.png">

^^^ This should have a small amount claimable from the GIVstream as a second box
-----
- [x] After harvesting the transaction took a long time to confirm

<img width="487" alt="Screen Shot 2021-12-17 at 11 15 19 AM" src="https://user-images.githubusercontent.com/14945613/146582618-98b16fae-08b7-4b9f-859e-1ae1eeb7490f.png">

----------

**Comment by GriffGreen** [comment]
The long time was not able to be replicated so I checked it off

**Comment by GriffGreen** [comment]
adding this to the other issue, makes more sense for pedro to do it :-D

**Comment by divine-comedian** [comment]
I can't test this issue because my GIVdrop has already been claimed!

**Comment by WhyldWanderer** [comment]
I just claimed on deployment 6 and my blockscout link worked as expected.

**Comment by divine-comedian** [comment]
nice! moving to DONE
