### ISSUE TITLE
Unstaking and Staking in the Univ3 pool - the modals are big and different from all the other cards

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#336]
I would love if the whole GIVfarm would use the same design for the modals.

Right now, for the univ3 pool, it uses these big modals for the txs that aren't consistent w the other cards, so I'm outlining the flow. It should be basically the same for **Staking** and for **Unstaking** so I will just explain Unstaking... but please fix both.

## Unstaking

- [x] Unstake button should be pink if the NFT is available to unstake

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/07695ca9-b9bc-425b-8e70-38f7dbe60124)

- [ ] when I click "unstake",  you should stay on the same modal, but that button should look like this while the metamask popup asks me to confirm... maybe since the button is small we can just make it say "PENDING"
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/497567f2-f8ce-4e20-8936-450faaa47624)

- [x] after I confirm in metamask I should get this spinning wheel (the nice, small version from the other cards)...
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1224195c-7f83-49ac-97eb-8f66e1a8eea7)

- [x] when the tx succeeds, it should look like this:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1f63a4d7-c5f3-4eed-9853-43055354632b)

**Comment by divine-comedian** [comment]
this issue looks to be good except for the issue of the pending button being way too wide - this was mentioned in several other issues - 
![image](https://user-images.githubusercontent.com/67759413/146991147-bec84526-dd01-4c11-a039-279bd2c08926.png)
oops ... 
![image](https://user-images.githubusercontent.com/67759413/146991186-f57e5158-767c-4f42-8889-79d71c85ff96.png)

**Comment by laurenluz** [comment]
fixed 
![image](https://user-images.githubusercontent.com/75490971/147183320-ff06096b-8d94-4087-8f98-1413d6b73e94.png)
