### ISSUE TITLE
On GIVdrop page: Center "explore the GIVeconomy" button

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#338]
Instead of having it off to the side, can we center it below the other 3 buttons?
![Screen Shot 2021-12-17 at 2 38 12 PM](https://user-images.githubusercontent.com/14945613/146605019-8113ddc7-6081-46bf-8e82-378f76d3db3a.png)

It's great that it is slightly bigger than the other buttons :-D It just needs to be centered

**Comment by laurenluz** [comment]
yeah let's all the buttons/links!
