### ISSUE TITLE
GIVdrop - Change "How to use your GIV" to better, more appropriate titles

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#340]
My ideas... feel free to improve upon them @divine-comedian 

Donate to get GIV back
Govern in the GIVgarden
Ape in to the GIVfarm
Watch your GIVstream flow

**Comment by divine-comedian** [comment]
Okay I modified some of your suggestions and changed some of the subtext to match up and be more explanatory - 
![image](https://user-images.githubusercontent.com/67759413/146682253-dcabda2c-5cd2-4f80-96f6-73a9ef26755a.png)
![image](https://user-images.githubusercontent.com/67759413/146682274-cf6e6249-783f-4bf6-986e-19076b12d878.png)
![image](https://user-images.githubusercontent.com/67759413/146682294-a2c0fb41-eb02-4b8e-bd4a-7275bb95f4cd.png)
![image](https://user-images.githubusercontent.com/67759413/146682310-7fa43a03-82ee-4c34-8efc-6a76c02bf951.png)


none of this has been uploaded yet just in case we would like to make changes - happy to discuss

**Comment by laurenluz** [comment]
Nice changes!

1. GIVfarm is great
2. GIVgarden - let's make it "_Engage in Governance_" (take out "community" because it's not technically correct). Also, I think we should change the subtext... "_Participate in Giveth governance using the **GIVgarden**. Wrap GIV to vote on proposals and earn rewards._"
3. GIVbacks - Let's do "_Donate & get GIV back_"...Better than "to" because getting GIV shouldn't emphasized as the prime motivation for donating.
4. GIVstream - title is great. for the subtext... "_Welcome to the expanding GIViverse! The GIVstream offers continuous rewards for GIVeconomy participants so as the GIVeconomy grows, so does your GIV!_"

**Comment by divine-comedian** [comment]
okay - changes are pending https://github.com/Giveth/liquidity-mining-dapp/pull/62

**Comment by divine-comedian** [comment]
changes are in and live on staging! 

![image](https://user-images.githubusercontent.com/67759413/147136016-6147ab05-7185-41f7-8da9-2b602c6e6068.png)


moving to DONE
