### ISSUE TITLE
Test changing Tao & CV params in the garden

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#341]

**Comment by GriffGreen** [comment]
Would you say this is done?

**Comment by laurenluz** [comment]
I don't think we ever testing changing CV params in the garden

**Comment by laurenluz** [comment]
I think we should probably test changing all the params we want to change after launch....

**Comment by divine-comedian** [comment]
we tested changing the CV params in GIVgarden3 - we can test changing our Tao Voting parameters - I think its a good idea

**Comment by laurenluz** [comment]
can you facilitate it @divine-comedian ?

**Comment by divine-comedian** [comment]
aye aye capitaine

**Comment by divine-comedian** [comment]
I created three decision votes and alll of them passed but none of them are executable... I reached out to Gardens for support

**Comment by laurenluz** [comment]
jeepers! ok well thanks for checking!

**Comment by laurenluz** [comment]
any news from gardens? you can ask also in the GIVgarden deployment chat @divine-comedian

**Comment by divine-comedian** [comment]
Gabi reached out - testing adding in the new permissions for disputable-voting (they were missing) and then I will retry to run changing our decision voting settings

**Comment by divine-comedian** [comment]
the permissions updated successfully and I was able to change our Tao Voting settings - just need to confirm some of the algorithms used to calculate time in the disputable-voting app - I would call this issue done however
