### ISSUE TITLE
GIVbacks - we need these numbers to make sense / be changed after launch

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#342]
the GIVbacks rewards amount should be a static number... the amount they have liquid at the time of GIVbacks distribution.

the rest is "added to their GIVstream"... it shows the flowrate here.. but it is already added to their GIVstream

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/65539efc-76d7-494d-b222-62a5e6147121)

**Comment by aminlatifi** [comment]
It needs some new data from backend side. To be precise, the backend should fill another field which is givBack liquid part that is filled at the exact moment the tx has happened.

**Comment by laurenluz** [comment]
looked correct on staging! I just harvested, so can't put a screenshot
