### ISSUE TITLE
For new user GIVstream is a bit confusing, people doesn't know what it means and does it include all of GIVbacks, Drops and Farm or not! need a little bit more clarification

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#343]

**Comment by DonnaOftadeh** [comment]
@laurenluz

**Comment by laurenluz** [comment]
did the user click the "?" on the GIVstream? or follow the links to read more? was it still confusing after reading the documentation?

Would be good to get a bit more context

**Comment by laurenluz** [comment]
moving to done, if we get more feedback after launch we can make adjustments for comms
