### ISSUE TITLE
There should be a back arrow as well - the clicking on the top menu to brows interpages is not visible enough

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#344]

**Comment by DonnaOftadeh** [comment]
![image](https://user-images.githubusercontent.com/53400757/146631903-774b29ca-53aa-4445-99f7-64d60155697c.png)
the forward arrow should be visible completely as well

**Comment by DonnaOftadeh** [comment]
@laurenluz

**Comment by laurenluz** [comment]
@pkretzschmar can you add a "back" arrow onto the pages so the user can navigate more easily?

@DonnaOftadeh - the hidden arrow thing is due to GIVdrop responsiveness, which Cherik is working on

**Comment by divine-comedian** [comment]
the back arrows are in and are functional across all pages -
![image](https://user-images.githubusercontent.com/67759413/146987586-1762c344-9fc8-4ddf-a4e9-dc35900a218c.png)

 the givdrop design is much more responsive now and the arrow buttons are no longer clipped off by smaller screen resolutions
 
 looks to be resolved! moving to done, nice work guys!
