### ISSUE TITLE
GIVdrop - make a better handling of user inputs

### ISSUE THREAD

**Issue by mendesfabio** [Giveth/GIVeconomy#348]
There's not inputs handlings.

1. An user can navigate between Claim screens pressing Tab.

https://www.loom.com/share/cdb009687c434af0a7428b24c9280903

2. Number inputs accepts both comma and period as decimal separators. I worked on staking inputs and made it always period - even when user inputs a comma. Also, users can input here negative values and I'm not sure if they can input `.1` as requested before.

**Comment by divine-comedian** [comment]
testing on staging with brave browser and firefox

I can still navigate between pages using tab - this should be disabled no?
![image](https://user-images.githubusercontent.com/67759413/146989646-b65bf81e-7ff4-4bbb-8725-471fb8562153.png)

in the GIVdrop input fields I can put in negative values and decimals, I cannot use a comma, only periods are accepted
![image](https://user-images.githubusercontent.com/67759413/146990308-77de30c9-addf-445d-8f44-01e5cdfff849.png)

I don't quite understand what the intended outcome should be? why should I be able to put in negative values in the GIVdrop?

**Comment by mendesfabio** [comment]
WIP at https://github.com/Giveth/liquidity-mining-dapp/pull/64

**Comment by laurenluz** [comment]
changes were merged 10 hrs ago, looks to be ready to test

**Comment by GriffGreen** [comment]
I pressed tab and it sent me from the first page all the way to the last page... but in a very broken way

<img width="1376" alt="Screen Shot 2021-12-22 at 10 21 51 PM" src="https://user-images.githubusercontent.com/14945613/147187541-e808da28-49ce-46d6-aead-961107c12733.png">

Notice the is the "Govern" page according to the top and that the page is way off center.

**Comment by divine-comedian** [comment]
tested the number inputs on the GIVdrop pages - 
no more negative numbers! also when i try to enter a comma it inputs a period for the decimal places! just need to fix the tab issue Griff described above and this should be good to go!
