### ISSUE TITLE
Harvest modal is "too damn big"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#351]
@MohammadPCh I think you noticed this already right? when the user has GIVbacks, the harvest modal is too big in the screen... and I can't scroll around it.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/90c8d29d-5125-4360-b779-ac2de1d66e99)

https://imgflip.com/i/5ygtp2

**Comment by MohammadPCh** [comment]
@Lauren, I think we need a design for it, for example we ca decrease Padding and margins.
or maybe use 2 column for it.
I recommend not using scroll for modal.
