### ISSUE TITLE
Harvest modal - this title is wrong & confusing!!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#352]
It should not say "Claimable from GIVdrop" here at the top...

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8e6bd30a-a70f-4a23-bec1-44ae5953e20a)

**Comment by divine-comedian** [comment]
testing on staging - 

checking all of the harvest modals on kovan and xdai they seem to be updated and consistent - 
![image](https://user-images.githubusercontent.com/67759413/146990784-8e4cb2a0-b46f-41f5-a43b-f78b67dd725e.png)


the givdrop reference is removed as well as the output numbers from the givdrop and its related givstream - looks to be resolved!
