### ISSUE TITLE
GIVdrop "You have x to claim" text should be bold

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#355]
it's like this: ![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/9054d3c1-9f04-4667-aa6e-9d15258f6418)

it should be this: ![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1ee206f0-950d-4cd4-b741-23699b96d3a6)

**Comment by divine-comedian** [comment]
the text is now BOLD - testing on staging 

![image](https://user-images.githubusercontent.com/67759413/146986538-24ff10b0-a472-473e-9b61-549473ed41fe.png)
