### ISSUE TITLE
GIVdrop - donate, govern & stake pages all need a little help... not looking like the designs...

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#357]
- [x] Too much space at the top and too little at the bottom on all slides....
- [x] Govern page... elements look really crowded together....
- [x] Donate page: text should say "Donate & get GIV back" not GIVback
- [x] GIVbacks & streaming box has too much space at the bottom

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/cf1ccea2-6c23-4ae1-a06f-d6dd60bd11fb)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e3cd8c98-c024-4dcd-844a-4e3598b9746c)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/137bd555-afdb-48b0-97aa-378c95d8d4e5)

**Comment by laurenluz** [comment]
here's a link to the figma for reference... some of the details have changed, but the spacing looks way better on there: https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=741%3A61473

**Comment by MohammadPCh** [comment]
@laurenluz I think it's better to have a new design for GIVdrop. because the old design is useless. the old desingn is not based on design system also  most of texts, boxes and buttons changed. maybe @markoprljic  can help us.

**Comment by markoprljic** [comment]
What kind of help do you need precisely? @MohammadPCh

**Comment by MohammadPCh** [comment]
> What kind of help do you need precisely? @MohammadPCh

I think @laurenluz  should decide, but we didn't have design for  GIVdrop, old design is useless because many things changed.

**Comment by markoprljic** [comment]
I'm still a bit unclear, what to decide? What should be done by me given I provided the design revisions already?

**Comment by MohammadPCh** [comment]
> I'm still a bit unclear, what to decide? What should be done by me given I provided the design revisions already?

can I have the last version?
because what I have is completely different from the design.
this is our preview link:
https://develop-liquidity-mining-dapp-git-feature-fix-g-4b8351-givethio.vercel.app/

**Comment by markoprljic** [comment]
The latest version is in Figma and I'd expect this one to be deployed, unless there are objections and valid reasons not to use it.

**Comment by laurenluz** [comment]
Most recent deploy preview for testing: https://develop-liquidity-mining-dapp-git-feature-fix-c-b39907-givethio.vercel.app/claim

**Comment by GriffGreen** [comment]
need you looking over my shoulder to test this @laurenluz

**Comment by laurenluz** [comment]
they look great
