### ISSUE TITLE
GIVdrop - why are we imposing "GIV" and onto this token - this is a test token called DRGIV!!! Also, the logo being added needs to be updated

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#358]
Using the "add to metamask" in the GIVdrop.

The token I'm adding is DRGIV. It should be adding DRGIV... not DRGIV pretending it's GIV. **When importing the token we should use the default symbol from the contrac**t.

I like that we're adding the logo, but it should be this one: https://github.com/Giveth/giveth-design-assets/blob/master/02-logos/GIV%20Token/GIVToken_200x200.png

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/270cb5c0-ac01-41db-a78b-5661b3babf92)

**Comment by divine-comedian** [comment]
the token symbol and the ticker seem to be updated when I try to load it using the metamask link

![image](https://user-images.githubusercontent.com/67759413/146986362-44618387-f255-45fd-b6ea-c83201c4717d.png)

**Comment by pkretzschmar** [comment]
@divine-comedian This happens when the user try to add the token one time, but just closes the metamask, and click again. It kind of stacks

**Comment by divine-comedian** [comment]
yes you're right -  I did a fresh load and this is resolved - moving to DONE
