### ISSUE TITLE
GIVdrop - I did not claim this!! and I'm getting the congratulations screen

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#359]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/77673f1d-d6fd-43d2-a8cd-17d1684fbd39)

**Comment by divine-comedian** [comment]
@pkretzschmar  what's the best way to test this issue?

**Comment by pkretzschmar** [comment]
You have to go thought the entire claim process.

**Comment by divine-comedian** [comment]
@laurenluz -  I have already claimed  - you mentioned not having claimed yet - this is impossible to test without using a connected wallet that has received a GIVdrop

**Comment by WhyldWanderer** [comment]
I just claimed on Deployment 6... I only received the congratulations screen after claiming. The flow seems to be working correctly for me.
