### ISSUE TITLE
GIVfarm Front-end design implementation

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#36]

**Comment by laurenluz** [comment]
@MohammadPCh https://www.figma.com/file/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?node-id=7800%3A35486

This design is finalized too - let me know if you have any questions

**Comment by laurenluz** [comment]
Still needs to add Harvest functionality

@MohammadPCh did you know that there will be some updates on the GIVfarm design... just the one pool. Marko is going to add the NFT for the UniV3 pool
