### ISSUE TITLE
GIVfarm - harvest confirmed modal appears after cancelling transaction 

### ISSUE THREAD

**Issue by mendesfabio** [Giveth/GIVeconomy#360]
https://www.loom.com/share/8d0e3939bea6444fbd97b82dc814a46c

Also, the harvest button gets full width on pending state.

**Comment by laurenluz** [comment]
oooh nice attention to detail. tested and looks good!

![image](https://user-images.githubusercontent.com/75490971/147183656-8e4638f6-afcf-4674-b15b-292780878345.png)
