### ISSUE TITLE
GIVdrop - congratulations page should have SVG animations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#361]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/6f9582ec-5284-4d87-8254-a862d7facb94)

@markoprljic can answer any questions!

**Comment by markoprljic** [comment]
https://lottiefiles.com/68461-sparkle-burst
https://lottiefiles.com/85931-sparkle
https://lottiefiles.com/18881-blowing

 I added some animated SVG's here to make this success page juicy :)

The first two at the top should play only once. 
The one at the bottom next to the button should loop. 
I'd like to see how this feels like in the browser so please when you add that send me the link to preview. 
If it's too much we will remove some.

@MohammadPCh

**Comment by GriffGreen** [comment]
Animation work on the final page but not the page if you go back to claim with an address that already claimed
<img width="1067" alt="Screen Shot 2021-12-22 at 10 53 24 PM" src="https://user-images.githubusercontent.com/14945613/147189874-c6361059-3714-4c46-9819-d29a3d1d26bd.png">
.
