### ISSUE TITLE
GIVdrop - review GIVdrop and make any necessary design fixes

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#362]
@MohammadPCh & @markoprljic to coordinate on this

**Comment by markoprljic** [comment]
On final screen change Harvest to Claim.
Add SVG animations provided.

**Comment by GriffGreen** [comment]
Animation work on the final page but not the page if you go back to claim with an address that already claimed
<img width="1067" alt="Screen Shot 2021-12-22 at 10 53 24 PM" src="https://user-images.githubusercontent.com/14945613/147189874-c6361059-3714-4c46-9819-d29a3d1d26bd.png">
.
