### ISSUE TITLE
GIVdrop - on harvest modal, change the "Harvest" button text to say "Claim"

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#363]

**Comment by GriffGreen** [comment]
<img width="428" alt="Screen Shot 2021-12-22 at 10 42 05 PM" src="https://user-images.githubusercontent.com/14945613/147189017-76d4cb57-562f-45b9-a4c4-e136ef556f29.png">

Says claim... but also says 250 GIV... but then they get more than that, maybe it should just say CLAIM and leave out the 250?

**Comment by laurenluz** [comment]
@MohammadPCh please take out the GIVdrop amount from the button so it just says "claim"
