### ISSUE TITLE
remove check wallet feature from GIVdrop connect page & add clarifying text

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#366]
we made some changes to how a user can claim their GIVdrop in the smart contract - only connected users can claim a GIVdrop for their connected wallet. Because of this change it is kind of pointless for a user to check an address that they cannot connect to - they won't be able to claim the GIVdrop for that address anyway 

I'm suggesting to remove this input from the connect page 
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/0955654e-1f9a-45c4-8832-a2feef3b30a4)

If this is too much work we can leave it be, how hard is this? @MohammadPCh

**Comment by laurenluz** [comment]
@MohammadPCh some clarification:

- [ ] please keep the ability to see the address... just remove the ability for the user to input it manually. this way, after they connect wallet, they can see which address is connected and we don't make the design look weird.
- [ ] please add small text underneath the address field that says "What if this address doesn't match the address in my wallet?" and links to https://docs.giveth.io/giveconomy/givdrop/#if-you-get-stuck-in-the-givdrop-claim as per #267

**Comment by laurenluz** [comment]
working great
