### ISSUE TITLE
Links on congrats page dont work goes to 404

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#371]
![Screen Shot 2021-12-22 at 10.51.09 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/b558eccb-5376-448f-9244-3e5712dfcb41)![Screen Shot 2021-12-22 at 10.51.27 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/1e65f6b4-3f1c-414c-9928-77f0912d2ac1)

![Screen Shot 2021-12-22 at 10.51.43 PM.png](https://images.zenhubusercontent.com/597b3dc4f8b79f8376e1224b/64fce60d-0325-4569-9789-fb5f55483552)

**Comment by divine-comedian** [comment]
I can't seem to reproduce this issue Griff - all the links on the congrats page are linking externally so the slugs aren't showing up like in your screenshots

**Comment by divine-comedian** [comment]
looks to be resolved with deployment 7 - moving to DONE
