### ISSUE TITLE
GIVdrop - Add to metamask *should NOT* impose a symbol onto the token

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#372]
When you add to metamask the symbol should be read from the token contract...

I'm in deployment 6. This token is in my wallet already. It's DRGIV2. It SHOULD NOT call it DRGIV... I made this issue before, but I think perhaps I wasn't clear enough...

Please do not change the symbol now to impose "DRGIV2" *read the symbol from the token contract*. This alert in Metamask makes us look sketchy and scammy AND can be very confusing to the user.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/1d29914a-c27a-4367-a61a-f19bf29afc4e)

**Comment by laurenluz** [comment]
fyi though, adding the image as the logo is fine and great, so let's leave that.

**Comment by WhyldWanderer** [comment]
This is happening on Deployment 7 as well
![image](https://user-images.githubusercontent.com/74267818/147260054-3078f243-c6fb-48fb-bba0-e6b1b0a3e941.png)

**Comment by laurenluz** [comment]
@mendesfabio so what was the final thought here? we're going to update them manually before every deployment?
