### ISSUE TITLE
GIVdrop - claim page text fix

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#375]
Highlighted part should say "Let's Build the Future of Giving, together."

And let's make the button just say "claim"

![image](https://user-images.githubusercontent.com/75490971/147260652-110e8ad2-bf84-4270-a0d6-2e2f4dc97f9d.png)

**Comment by divine-comedian** [comment]
changes pending on https://github.com/Giveth/liquidity-mining-dapp/pull/73
