### ISSUE TITLE
GIVdrop - govern page title text font size is smaller than the other pages

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#376]
Let's bump up the font size on the "Govern" page so it doesn't look so weird after the "donate" page

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/e03cc9df-c73e-48d1-9fa0-d7b383a7e51b)

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c767903f-85d4-4483-95f8-6a9c835cd162)

**Comment by divine-comedian** [comment]
changes pending on https://github.com/Giveth/liquidity-mining-dapp/pull/73
