### ISSUE TITLE
GIVdrop Congratulations page - "claim from another address" not working

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#379]
I went through the GIVdrop claim flow on Deployment 7.
On the 'congatulations' page, the 'claim from another address' link is not working.

![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/86a49f97-a44a-4e95-9206-941444cc06f4)

@MoeNick says "If I connect a different wallet before clicking the link, it works"

I do not have this same experience... it doesnt work for me even if I switch wallets.

**Comment by laurenluz** [comment]
it works now
