### ISSUE TITLE
GIVeconomy Deployment 7 - Wrong garden linked

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#381]
When I go to GIVgarden fromt he GIVgarden page, It takes me to an old garden:
![image](https://user-images.githubusercontent.com/74267818/147263719-931e21e5-ff84-4d0e-9a84-dbed8a5b5b2d.png)

It directs me here: https://gardens-staging.1hive.org/#/xdai/garden/0xbf2d7d659e45bb0ded75d89eaf5f267fd1ce0ade

It should direct me to here: https://gardens-staging.1hive.org/#/xdai/garden/0x16388d99199a74810fc572049b3d4d657e7d5deb

**Comment by laurenluz** [comment]
it's correct now
