### ISSUE TITLE
GIVstream page - tool tip text is wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#383]
Text should be: "The rate at which you receive liquid GIV from your GIVstream"

@divine-comedian can you fix this? 

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0274b61b-8854-470d-81fa-ae42ca62ed3c)

**Comment by divine-comedian** [comment]
meging into develop - https://github.com/Giveth/liquidity-mining-dapp/commit/54391cbb4dd1d00c263fa862699a62b3df8c586a
