### ISSUE TITLE
Top up the xDAI token distro to what it would be if it had 920mil

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#384]
We are sending 910 mil to it

Then when the deployment is all working, it will get whatever tokens we didnt have to use... it will need probably around 100,000 tokens to be topped up.

**Comment by GriffGreen** [comment]
We need to send 23,789.872 GIV to the Token Distro from nrGIV.

I will make a forum post.

**Comment by laurenluz** [comment]
https://forum.giveth.io/t/toping-up-the-givstreams-smart-contract-with-giv/299

**Comment by GriffGreen** [comment]
Yep waiting for 5 day advice process

**Comment by laurenluz** [comment]
can just transfer, doens't need to call a function

**Comment by divine-comedian** [comment]
ready! https://aragon.1hive.org/#/nrgiv/0x749cccd03c00110cf76f4e009c6eaf59b5f2bd0e/vote/44/

**Comment by laurenluz** [comment]
Looks like we need to add permissions to enact this @divine-comedian - what's the status?

**Comment by divine-comedian** [comment]
waiting for this to pass - https://aragon.1hive.org/#/nrgiv/0x749cccd03c00110cf76f4e009c6eaf59b5f2bd0e/vote/46/

**Comment by laurenluz** [comment]
waiting for permissions

**Comment by divine-comedian** [comment]
new vote is made - https://aragon.1hive.org/#/nrgiv/0x749cccd03c00110cf76f4e009c6eaf59b5f2bd0e/vote/54/

I messed up the formatting on the original vote on top of not having the right permissions - this new vote should resolve the issue 

also when/if we install a finance app for managing the treasury these sorts of formatting errors should be come impossible.
