### ISSUE TITLE
Create Tao vote to update the Covenant in the Gardens

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#386]
We missed a link in the LIVE covenant.

We need to create a TAO proposal in the REAL DEAL garden to change this.

![image](https://user-images.githubusercontent.com/74267818/147286942-6c2168db-d6b6-4229-9120-1a11d20d7c77.png)

Here is the link that should be there: https://docs.giveth.io/whatisgiveth/governanceProcess

**Comment by laurenluz** [comment]
@laurenluz to send txt file to mitch

**Comment by divine-comedian** [comment]
just getting some syntax advice from sem then I will test the script on staging and if all goes well then run it on the real GIVgarden

**Comment by laurenluz** [comment]
so according to the gardens chat... this wasn't working... waiting on 1hive team to see if it can br resolved.

**Comment by divine-comedian** [comment]
new vote here- 
https://gardens-staging.1hive.org/#/xdai/garden/0x16388d99199a74810fc572049b3d4d657e7d5deb/vote/6

**Comment by divine-comedian** [comment]
The latest test vote passed! We're ready to update our covenant with any more changes and create the real vote on the GIVgarden

**Comment by laurenluz** [comment]
Nice!

So Before we do the real vote.... 
Just found out yesterday that gardens doesn't want to include a terms & conditions to the gardens UI... and suggested we add terms and conditions for proposals and challenges to the covenant.

Ivy is going to be working on this for the TEC and making changes to theirs. I think we should let them finish it, and fork the TEC version... then update it in one shot with the real Tao vote.

What do you think @divine-comedian ?

**Comment by divine-comedian** [comment]
I think we can do updates to the covenant piece-meal. If I understood the original intent was to fix this embarassing mistake we made that's currently in our covenant now. Unless you think it can be done early this week I think we can push to fix this earlier and push the rest later.

**Comment by laurenluz** [comment]
ok sure, push it then. I just think it's kind of annoying to make Tao Votes and rally people to change it, but I don't have any clear idea when the Terms will be added for the TEC

**Comment by divine-comedian** [comment]
script for reference - I will make the vote shortly on the GIVgarden
```
connect 0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98 disputable-voting.open @context:updating covenant
exec agreement.open changeSetting 0x44e4fcfed14e1285c9e0f6eae77d5fdd0f196f85 false "Giveth Community Covenant" 0x516d506e5a37534b374a7966476b71686e414a3877415076655773337a6568774c754c4459755931444e42477341
```

**Comment by divine-comedian** [comment]
vote is up on the GIV garden! 

https://gardens.1hive.org/#/xdai/garden/0xb25f0ee2d26461e2b5b3d3ddafe197a0da677b98/vote/4
