### ISSUE TITLE
Make config file for purple list and link to it in our documentation for GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#387]
So that users know... only donations in certain tokens are eligible for GIVbacks... but we should make this list editable/accessible by devs

FYI @mateodaza @WhyldWanderer @mohammadranjbarz

**Comment by WhyldWanderer** [comment]
Why only certain tokens? which ones? I thought they were all included?

**Comment by mateodaza** [comment]
> Why only certain tokens? which ones? I thought they were all included?

Maybe some tokens don't have value at all, we can't count those as donations

**Comment by WhyldWanderer** [comment]
>Maybe some tokens don't have value at all, we can't count those as donations

Ohh how many tokens do we accept for donations that wouldnt be eligible for GIVbacks?
Do accept tokens with no value for donations?

**Comment by laurenluz** [comment]
So the GIVbacks token list issue is done: https://forum.giveth.io/t/givbacks-token-list/253
