### ISSUE TITLE
We need Coingecko to know that we have a better link for our Circulating Supply API

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#389]
See https://circulating.dappnode.io/

Ask @eduadiez for support

**Comment by GriffGreen** [comment]
Here are the deets: https://docs.google.com/document/d/1sUm9p-6V0x_2fTJjRiZd4MaUggcwzplChc3h2PJMP4I/edit

**Comment by marthendalnunes** [comment]
@GriffGreen @laurenluz up and running at https://circulating.giveth.io/

**Comment by laurenluz** [comment]
I can't seem to open this... is this an issue on my side? @marthendalnunes 

![image](https://user-images.githubusercontent.com/75490971/148121813-6403567e-8bfa-4bd5-bc72-d50276db49d4.png)

**Comment by laurenluz** [comment]
@GriffGreen this is working now - https://circulating.giveth.io/token-supply

can you contact whoever it is that we need to contact to update it?

**Comment by GriffGreen** [comment]
sent the email
