### ISSUE TITLE
GIVbacks - convert the fabio's code to an endpoint

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#39]

**Comment by mohammadranjbarz** [comment]
@DonnaOftadeh 
It's about converting https://github.com/Giveth/givbacks-scripts to an endpoint?

**Comment by DonnaOftadeh** [comment]
yep - Converting it to an end point

**Comment by DonnaOftadeh** [comment]
here is the link to the full-scope of GIVbacks:
https://www.notion.so/giveth/Spec-GIVbacks-MVP-2d6335964e5b414082e41d7df89f9b3d

**Comment by mohammadranjbarz** [comment]
@DonnaOftadeh 
It implemented and deployed https://givback.develop.giveth.io/api-docs
This is the repository link https://github.com/Giveth/givback-calculation

@divine-comedian 
Could you help me test if the calculations are ok or not, I think it's fine but I need someone who knows the domain and business to test it  and approve me
( feel free to ask question about it from me)

**Comment by divine-comedian** [comment]
I'm running this against the numbers we have captured in amplitude to see if the calculations add up for total donation values in USD.

Looks like things are adding up on the IO side but there seems to be something up with calculations from TRACE, the values captured in Amplitude are MUCH HIGHER than what is shown in the givbacks API. It's hard to tell  whether this relates to the segment tracking we helped to implement or if there is missing information collected from the givbacks program.

 Some useful values to return in the parent object would be the value of donations we have received from each source (IO or TRACE) and what the GIVback rate is for the round - (<= 75% )
 
 Let's look at the numbers being shown in amplitude, their source and test some code @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> I'm running this against the numbers we have captured in amplitude to see if the calculations add up for total donation values in USD.
> 
> Looks like things are adding up on the IO side but there seems to be something up with calculations from TRACE, the values captured in Amplitude are MUCH HIGHER than what is shown in the givbacks API. It's hard to tell whether this relates to the segment tracking we helped to implement or if there is missing information collected from the givbacks program.
> 
> Some useful values to return in the parent object would be the value of donations we have received from each source (IO or TRACE) and what the GIVback rate is for the round - (<= 75% )
> 
> Let's look at the numbers being shown in amplitude, their source and test some code @mohammadranjbarz

I think it would be good if we have quick call together to talk about this issue,
I'll set a time with you in DM

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
I couldn't login to amplitude, are sure you added my email(mranjbar.z2993@gmail.com) to project?
and what is the org URL?( I tried giveth)

![Screen Shot 1400-07-12 at 14.17.36.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/a3f9d59c-ea3c-4895-908b-a102c8f98ec1)

**Comment by mohammadranjbarz** [comment]
@DonnaOftadeh 
I think you can close this issue because the endpoint works now and fabio's script is now ported to js and deployed
we follow up another things in #62
