### ISSUE TITLE
GIVdrop: Weird text overlap

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#390]
<img width="1061" alt="Screen Shot 2021-12-23 at 11 14 42 PM" src="https://user-images.githubusercontent.com/14945613/147319394-3913d87d-4969-45f5-8de7-45bfd530b48e.png">
<img width="296" alt="Screen Shot 2021-12-23 at 11 14 38 PM" src="https://user-images.githubusercontent.com/14945613/147319402-2bc3576f-8a6a-4d1c-a861-0f9e7cb1d8e0.png">

**Comment by mendesfabio** [comment]
Another one! I'm fixing both.

![image](https://user-images.githubusercontent.com/43360747/147352833-6df3b345-4a21-4be3-a790-4c22e5cc5288.png)
