### ISSUE TITLE
100% Staking on GIVfarm not updating

### ISSUE THREAD

**Issue by Danibelle** [Giveth/GIVeconomy#394]
Still shows I have 120,000 to be staked..
![image](https://user-images.githubusercontent.com/39466970/147369941-3d4250e2-c0b9-4e07-a095-486ddf55435a.png)

But the Garden shows correctly that I staked more already:
![image](https://user-images.githubusercontent.com/39466970/147370009-b3f939a2-a152-401d-8878-e8a9e0570a82.png)

**Comment by Danibelle** [comment]
Harvested, that's not updating in the UI either now..

https://blockscout.com/xdai/mainnet/tx/0xbe9aea732776af7eb7b1bda4414ab718c3e6313b27e75a12d420a1367281534d

![image](https://user-images.githubusercontent.com/39466970/147370123-492948bf-bbb4-42a7-90c2-8e6dbf6b5601.png)

**Comment by laurenluz** [comment]
did it update now? I think there were some temporary issue with the graph, but it looks correct for me right now

**Comment by laurenluz** [comment]
related to #397 

Should be working fine if the graph is working fine
