### ISSUE TITLE
Successful harvest from the GIV stream but it is not showing in the UI

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#397]
I harvested my GIVstream rewards
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/ee14982a-634e-4966-8a7e-e49522eef9a4)

I received a transaction confirmed:
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/045fa9fa-9627-4212-9254-9c4efbfce1df)

Blockscout says transaction was successful:
https://blockscout.com/xdai/mainnet/tx/0xce0c9755ec6e1c0b18c28a6f17f7c61c9bdd60e44c7978ed886b21c0f0a8ce52

But my GIVstream page still shwos the same amount claimable
![image.png](https://images.zenhubusercontent.com/5ffdde8079760c4346381d45/c3634483-6fbb-4334-bd4a-fe31b865095a)

**Comment by WhyldWanderer** [comment]
I notice now that it is showing correctly... I think this may have just been a delay in the UI refreshing slowly

**Comment by laurenluz** [comment]
Damn yeah things have been slow on the UI updating....


@mohammadranjbarz @aminlatifi can you investigate?

**Comment by mohammadranjbarz** [comment]
> Damn yeah things have been slow on the UI updating....
> 
> @mohammadranjbarz @aminlatifi can you investigate?

I just have checked the subgraph now, the syncing is good, after few blocks ( less than 30 seconds) our subgraph syncs with network, 
I don't see a problem there
