### ISSUE TITLE
Change "xdai" to "gnosis chain" everywhere

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#402]

**Comment by laurenluz** [comment]
Need to update:
- [ ] logos everywhere
- [ ] "switch to xDai" and instances of "xDai" throughout - should say "Gnosis Chain (formerly, xDai Network)
- [ ] documentation

**Comment by laurenluz** [comment]
@MoeNick would be nice to put this on the list for next sprint

**Comment by laurenluz** [comment]
will postpone to implement in the next version

**Comment by MoeNick** [comment]
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=333%3A41275

**Comment by divine-comedian** [comment]
this this the most common asset I've seen for the gnosis chain symbol - 

![Aatar_green_white](https://user-images.githubusercontent.com/67759413/156195173-ae53745b-df88-4b35-b0c0-6f8018fb1333.svg)

**Comment by divine-comedian** [comment]
I'd love to take on this issue - including adding Gnosis Chain media to the ui-design-system package

**Comment by aminlatifi** [comment]
> I'd love to take on this issue - including adding Gnosis Chain media to the ui-design-system package

@mosaeedi Would you please add this icon to Design System in Figma?

**Comment by divine-comedian** [comment]
PR pending review for ui-design-system 

@MohammadPCh  
https://github.com/Giveth/ui-design-system/pull/45

**Comment by mosaeedi** [comment]
https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=2281%3A59772

**Comment by laurenluz** [comment]
looks goods on v2
