### ISSUE TITLE
Users cannot claim a GIVdrop with their torus account

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#405]
We have many project owners who received a GIVdrop. 
However, these users (and probably others) cannot connect to the claim UI with their torus account.

**Comment by laurenluz** [comment]
@marthendalnunes do you think you could check this one out? lmk if any questions

**Comment by laurenluz** [comment]
@aminlatifi can make a new merkle drop for testing & add team member's torus's accounts for testing

**Comment by laurenluz** [comment]
@WhyldWanderer @MoeNick @divine-comedian @GriffGreen 

Vitor made it so that the user can now claim with Torus wallet. Me, Vitor & Amin all tested it already and it working just fine... but the switch network doesn't work for Torus and neither does the "add to metamask" thing.

Vitor is working on an improvement for this in #439 

You can try testing the claim, but I would actually suggest to hold off until he adds the new fixes so Amin doesn't have to make another new merkle drop and you guys can test it after.

FYI though, the new merkle drop w your torus accounts would be claimable here: https://liquidity-mining-dapp-d-torus.vercel.app/

**Comment by WhyldWanderer** [comment]
I checked it out but when I try to check my torus address i get this
![image](https://user-images.githubusercontent.com/74267818/148293275-09dbe7bf-8545-4a2c-94c5-20e79e2d3eb7.png)

**Comment by aminlatifi** [comment]
> I checked it out but when I try to check my torus address i get this
> 
> ![image](https://user-images.githubusercontent.com/74267818/148293275-09dbe7bf-8545-4a2c-94c5-20e79e2d3eb7.png)
> 
> 

Which url are you using?

**Comment by aminlatifi** [comment]
@WhyldWanderer the deployment accessible by this link has test torus wallets eligible for givdrop
https://liquidity-mining-dapp-d-torus.vercel.app/

**Comment by MoeNick** [comment]
I tried on chrome, everything is good

![image](https://user-images.githubusercontent.com/80677512/148406298-0e5a1ecc-3082-40ef-acd5-26a5186b1b73.png)

![image](https://user-images.githubusercontent.com/80677512/148406389-e9fd5023-2b5f-46d9-aed0-6339575fd4ff.png)

![image](https://user-images.githubusercontent.com/80677512/148406529-d7fd6e65-f7bb-4937-9a57-550fdaf5e375.png)

I dont have some xdai
![image](https://user-images.githubusercontent.com/80677512/148406797-c5b33db1-9bb4-49f0-8da3-81230ffbe55a.png)

![image](https://user-images.githubusercontent.com/80677512/148406931-fe899bc9-9f66-4f4a-b4b6-db6127b313bc.png)

**Comment by WhyldWanderer** [comment]
After confirming.. 
I just get a never ending spinning wheel - the torus transaction pops up... I click confirm. but this is all that happens:
![image](https://user-images.githubusercontent.com/74267818/148466014-401119a9-52a1-46f6-80cc-85e8f2cb164c.png)

**Comment by aminlatifi** [comment]
> https://liquidity-mining-dapp-d-torus.vercel.app/

By using this link? https://liquidity-mining-dapp-d-torus.vercel.app/

**Comment by WhyldWanderer** [comment]
>By using this link? https://liquidity-mining-dapp-d-torus.vercel.app/

Yes

**Comment by WhyldWanderer** [comment]
Seems fixed!!
![image](https://user-images.githubusercontent.com/74267818/148589337-5cdd7f40-9338-4ac6-bffc-79e689a4c556.png)

Thanks @aminlatifi!

**Comment by MoeNick** [comment]
Its a god idea we can send this  web2 users some xdai, right fore they click of claim. 🧐

**Comment by aminlatifi** [comment]
> Its a god idea we can send this web2 users some xdai, right fore they click of claim. 🧐

They have already

**Comment by MoeNick** [comment]
As you may see in my case, I dint have so I could not claim until I sent some to my torus wallet

**Comment by laurenluz** [comment]
yeah, we sent it to everyone eligible for the real GIVdrop. @MoeNick your Torus account was probably not part of the *real* merkle drop (we just added it for this small test), hence you did not have the xdai

**Comment by MoeNick** [comment]
Oh got it, thanks.
