### ISSUE TITLE
Awesome dune analytics dashboard, potential improvements

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#406]
https://dune.xyz/metacrypto/giveconomy

- [x] The Claims in the GIVdrop section seem to include all the small claims from when people harvest, not just the claims from teh Merkle Drop Contract.... I think you could make sure that the Merkle drop contract is the distributor that makes the call and then you would fix it.

Wow.... dud you fixed this before i even made the issue :-P

Confirm that it is also true that only the Merkledrop contract claims are considered for Total GIV Claimed chart.... it looks right tho.

- [x] How are there only 518 holders on xDai, when 896 people claimed? My guess is that it is because a 1000 people are farming with 100% of their holdings...  and a few 100 people got donated a tiny amount on Giveth and don't even know how to farm... i don't think this framing for holders makes much sense.... It should be addresses farming & hodling. Same with mainnet.. I might even just remove this section if an accurate number of holders + farmers is too hard to estimate

![Screen Shot 2021-12-27 at 7 09 05 PM](https://user-images.githubusercontent.com/14945613/147517022-30e90a8c-6d19-40a7-996b-494942b246e0.png)

- [x] LOVE the $GIV 🤑 section! Can we put it at the top? I think it will be more relevant as time goes on than the GIVdrop.
![Screen Shot 2021-12-27 at 7 10 27 PM](https://user-images.githubusercontent.com/14945613/147517061-3dd42ed3-3b67-4e11-9282-72b20614b463.png)

- [x]  I would love to see the GIVgarden have it's own section, outside of the GIVfarm... and it would be really cool if we could pull a number for Effective Supply (aka Total Support, how many people are voting in Conviction Voting) and as a % of people that have gGIV... I will ask Sem how to get that number.
![Screen Shot 2021-12-27 at 7 24 09 PM](https://user-images.githubusercontent.com/14945613/147517666-fc8d2c61-ba99-491b-8cb5-5d8201889bff.png)

![Screen Shot 2021-12-27 at 7 12 18 PM](https://user-images.githubusercontent.com/14945613/147517147-45241cae-7a3e-432a-a48a-a75ca61918cf.png)

- [x] Is there a way to use the WETH price to score the GIV price for the TVL in USD for the xDai pools? If not, then lets put the mainnet pools in $GIV terms too so all the farms can be easily compared in that metric.
![Screen Shot 2021-12-27 at 7 15 59 PM](https://user-images.githubusercontent.com/14945613/147517320-a393b938-7ec6-4f40-a27f-6fc53e2bd602.png)

**Comment by aminlatifi** [comment]
@mendesfabio Awesome dashboard!!!!!

One thing, are you sure about this?
![image](https://user-images.githubusercontent.com/5684607/147555504-c92d6176-7f3a-4cfa-a351-c3c654744418.png)

I doubted because the uniswap pool holds only 56.5 K

![image](https://user-images.githubusercontent.com/5684607/147555611-208e2a70-6ae6-4976-bfb0-1fce8dedd83e.png)

**Comment by mendesfabio** [comment]
@aminlatifi yeah I'm sure about the Uniswap TVL, I confirmed on Etherscan. OTOH the pie chart you sent is weird, but I believe it was outdated, I just ran the query and it shows about 360k $GIV in the Uniswap V3 contract. Thanks for reporting :)

**Comment by mendesfabio** [comment]
@GriffGreen I'm removing GIV holders section in favor of GIVgarden. Moved $GIV section to the top and made all TVL in terms of $GIV -- this is the best for now.
