### ISSUE TITLE
Create staging.giv.giveth.io?

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#409]

**Comment by laurenluz** [comment]
deploy a staging environment! :D @aminlatifi

**Comment by aminlatifi** [comment]
It's done by @geleeroyale ;)

**Comment by laurenluz** [comment]
NICE! So now we should always test here: https://staging.giv.giveth.io/ ??

**Comment by laurenluz** [comment]
Or wait I'm still a little confused here. it looks identical to giv.giveth.io - with the same real GIV tokens staked.

Is there any way we can have the staging site with test tokens/test networks?

**Comment by aminlatifi** [comment]
> Or wait I'm still a little confused here. it looks identical to giv.giveth.io - with the same real GIV tokens staked.
> 
> Is there any way we can have the staging site with test tokens/test networks?

You are right, it's fixed now.
