### ISSUE TITLE
GIVfarm - add "Why is there no harvest button?" & modal

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#411]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/53664b52-21d7-4051-ab6b-bb11391c3c90)

Add "Why is there no harvest button?" and a modal...

The Modal should say:

"This shows you the total rewards that are available to harvest in the GIVfarm on your selected network. If you are staking in multiple pools, a "harvest all" button would lead to several transactions being combined which, on mainnet, may result in excessive gas spending. You can harvest your GIVfarm rewards from each corresponding pool."

@divine-comedian can you QA this modal?

This is issue is as per feedback from #407

**Comment by divine-comedian** [comment]
do you want me to create this modal or QA it? I don't see anyone else assigned to the issue

**Comment by laurenluz** [comment]
We can make the "harvest all" a nice-to-have on xDai & not offer it on mainnet

**Comment by laurenluz** [comment]
can add to smart contracts or have it popup multiple times on frontend

@aminlatifi @paxthemax to determine the best way

**Comment by paxthemax** [comment]
Alas, it is not possible to delegate another address as the beneficiary so a contract based batch call solution isn't really doable (we assume that the user address is the beneficiary).

The most painless solution IMO would be a flow that would guide the harvester through each claim step. That way we would avoid confusion with which transaction is being signed. The harvester would be able to navigate through the flow and choose what she would like to harvest.

That might be too much effort though. An interim solution could be just several tx popups in a row.

**Comment by laurenluz** [comment]
I think that multiple tx popups is kind of unpleasant and confusing and really don't think this is work the extra devving (since we can do a bath call), especially since we would only bother to add this on xDai and not mainnet...

I'm just going to move this to done w/o changing anything. I think it is fine as it is now with no harvest button at the top.
