### ISSUE TITLE
Improve APR modal communication

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#412]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4ff9c8fa-055c-426e-ba48-ca30326e658c)

"Your APR is total the rate of return on your staked tokens. Part the GIV your earn from staking is claimable immediately, and part goes into increasing your GIVstream flowrate. Over time, as the GIViverse expands, more or your total earnings will be claimable immediately and less will add to your GIVstream flowrate.

Today's breakdown:
% of rewards claimable immediately: 10%
% of rewards adding to GIVstream: 90%

Read more <link> "

links to: https://docs.giveth.io/giveconomy/givstream/ 

@divine-comedian can you QA?

This is from Kris's feedback in #353

**Comment by divine-comedian** [comment]
A percentage of the GIV you earn from staking is claimable immediately, and the remaining percent goes into increasing your GIVstream flowrate. Over time, a greater percentage of your total earnings will be claimable immediately following the continued expansion of the [GIViverse](https://giv.giveth.io/givstream)

Current Distribution:
Claimable Immediately: 10% 
Increasing your GIVstream: 90%

`READ MORE`

**Comment by laurenluz** [comment]
@divine-comedian to update this!!

**Comment by divine-comedian** [comment]
pending in PR - https://github.com/Giveth/liquidity-mining-dapp/pull/99

**Comment by laurenluz** [comment]
Looks correct... but... are the 10% and 90% numbers accurate? I feel like it should be at least like 10.1 & 89.9 by now.. .making me think that perhaps these numbers are not being calculated and instead are (incorrectly) hard-coded. @divine-comedian @MohammadPCh - can you check?

![image](https://user-images.githubusercontent.com/75490971/148090730-c9b25796-752c-40ff-aa8a-8b0713125161.png)

**Comment by laurenluz** [comment]
I guess it is rounding to whole numbers.. this is ok... 
![image](https://user-images.githubusercontent.com/75490971/150052157-41b6230d-908b-4c5d-8d7e-8acc9f07c0d9.png)
