### ISSUE TITLE
Make it more clear that GIVbacks become available after the round ends

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#413]
as per #407

Maybe we add a "Round x distirbuted on THIS DATE" somewhere?

We can add a "Why don't I have GIVbacks?"

When clicked, it says:

"GIVbacks rewards corresponding to the current round become available after the round ends. If you donated to a verified project and do not yet have rewards to claim, it is likely that GIVbacks have not yet been distributed for that round, or that you claimed your GIVbacks rewards already."

With a  "Read more" that links to https://docs.giveth.io/giveconomy/givbacks

@WhyldWanderer can you QA / lmk what you think?

**Comment by WhyldWanderer** [comment]
>Maybe we add a "Round x distirbuted on THIS DATE" somewhere?

We can't really promise a certain date... but we could say BY this date. We need time to review for fraud and pass the vote for distribution as well as publish it publicly somehow.

>We can add a "Why don't I have GIVbacks?"
When clicked, it says:
"GIVbacks rewards corresponding to the current round become available after the round ends. If you donated to a verified project and do not yet have rewards to claim, it is likely that GIVbacks have not yet been distributed for that round, or that you claimed your GIVbacks rewards already."
With a "Read more" that links to https://docs.giveth.io/giveconomy/givbacks

Love this! and its well written imo

**Comment by laurenluz** [comment]
Thanks for the QA @WhyldWanderer !!

So.... perhaps we could add that round distributed by x date to the rounds thing? What is the best "distributed by" date? the start date of the following round?
![image](https://user-images.githubusercontent.com/75490971/147784554-f96ce32a-2b10-4129-bce0-e83008b5d477.png)

**Comment by WhyldWanderer** [comment]
At least a week...

**Comment by laurenluz** [comment]
ok I'm just going to leave this open... and not add any date...

we can see how the first few rounds go and how quickly we can get things out.

moving this issue to done.
