### ISSUE TITLE
Improve GIVfarm page with "buy GIV" more prominant 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#415]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/8940af68-005d-4d2b-b96b-8d9a4f9803c1)

**Comment by markoprljic** [comment]
![Image 2022-01-14 at 7 06 08 pm](https://user-images.githubusercontent.com/5704285/149563905-e47a9b4f-d27d-4190-bba2-1896a81b2696.jpg)

[Figma here ](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19%3A17721)


@laurenluz @MohammadPCh @MoeNick

**Comment by laurenluz** [comment]
look great
