### ISSUE TITLE
GIVcuration spec

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#416]

**Comment by laurenluz** [comment]
WIP

https://docs.google.com/document/d/17mjEcS948OAjScZnXinGquGwdRLpWi-1EjGcTg6MeBI/edit

https://www.notion.so/giveth/Spec-GIV-token-staking-for-project-curation-6659b72ff88f4b14bad502cf2d67828e?showMoveTo=true&saveParent=true

**Comment by WhyldWanderer** [comment]
Check out this forum post about GIVcuration and how we can incorporate the use of NFTs:
https://forum.giveth.io/t/givcuration-and-nft-incorporation-ideas-brainstorming/289
