### ISSUE TITLE
Implement  Reward Menu

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#417]
As a user, I want to see the numbers below GIV button in the header like this:
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/303cb141-724b-4e9c-816e-15906cac6212)

The design with responsiveness guides are  available here: https://www.figma.com/file/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=13%3A4

It will load on hover in desktop view and tap in mobile view.

**Comment by laurenluz** [comment]
THIS IS SO COOL
