### ISSUE TITLE
Responsiveness: Header

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#418]

**Comment by laurenluz** [comment]
Well, it looks good but the header doesn't have any links to the regular Giveth homepage... and the "+" is a bit weird. it's not very intuitive that that should open "create a project".

@markoprljic what do you think about this design for mobile? would appreciate your comments.

![image](https://user-images.githubusercontent.com/75490971/150058913-81052d1d-2efd-4a16-9d28-065ccb20221b.png)

**Comment by markoprljic** [comment]
The mobile header should have icon for the menu, this is the original design
![Image 2022-01-19 at 12 20 57 pm](https://user-images.githubusercontent.com/5704285/150120451-d6c240ea-02d7-4361-81c2-14d9635d6cc4.jpg)

@mosaeedi Will have more info on this since he's working on the mobile version.

**Comment by laurenluz** [comment]
@MohammadPCh can you check in with @mosaeedi on this one? add any estimation if it should be added to this sprint or not

**Comment by MohammadPCh** [comment]
when I was implementing the header the menu design was not finished yet. so I postponed it.
I think the story point for implementing this is 3.

**Comment by MoeNick** [comment]
We can do it in V2 and stop implementing new things in the old repo.
