### ISSUE TITLE
Merge staging environments & production of giveth.io & giv.giveth.io 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#425]
next.giveth.io will work with liquidity-mining-dapp for GIVeconomy

we need to merge typescript giveth.io & giveconomy - user is signing in on the dapp & wants to stay signed in when they are connected to giv.giveth.io

needs to be done after typescript version is complete

would be great if these projects were on the same domain...

@MohammadPCh to investigate

**Comment by MohammadPCh** [comment]
I think the best way is to merge projects together. because we can reduce the size of files user needs to download. and the user will download them once. also with this solution, we will prevent duplicate code in different projects.
