### ISSUE TITLE
restructure information for failed transaction modal 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#427]
![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/c98b3ced-65b8-4906-bada-80393241e941)

need to implement some more padding so the text isn't squished against the egde of the modal

change this tx id to a message to give the user more understandable information - a tx id might not be obvious for users

**Comment by divine-comedian** [comment]
pending fix in https://github.com/Giveth/liquidity-mining-dapp/pull/106

**Comment by laurenluz** [comment]
I don't know how to test this... @divine-comedian can you?

**Comment by divine-comedian** [comment]
wot .. that's interesting .. 

![image](https://user-images.githubusercontent.com/67759413/150132679-10ba67b5-304e-45be-bdac-8ad1a9e8de44.png)
