### ISSUE TITLE
Project verification typeform link change

### ISSUE THREAD

**Issue by ForestSoleil** [Giveth/GIVeconomy#437]
The typeform moved to a new address giveth.typeform.com but when users click the link to apply they are shown tbe 'this typeform has moved to a new address' screen. Please just change the link so it directly goes there.

**Comment by laurenluz** [comment]
please be more specific about which link you are referring to.

the one from giv.giveth.io/givbacks is correct, so I assume you are referring to one on giveth.io... in which case, it makes sense to move this to the giveth-next repo so MoeNick or others can see it. 

Also it would be helpful for you to put the link in the issue, for future reference.

Here it is: https://giveth.typeform.com/verification

**Comment by WhyldWanderer** [comment]
There is an issue for this here: https://github.com/Giveth/GIVeconomy/issues/437 https://github.com/Giveth/giveth-next/issues/581

**Comment by WhyldWanderer** [comment]
Where did you click the link from @ForestSoleil ?

**Comment by ForestSoleil** [comment]
I think it was from my project page 'verify your project' but i do not remember. That way now at least seems to he working.
