### ISSUE TITLE
Improve Torus wallet integration

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#439]
As per our conversation in the #giv-economy channel:

@marthendalnunes is working on:
1. determining how easy it is to hide the "add to metamask" button if the user if connected to Torus
2. determining if it is possible to have "switch to xdai" or "switch to mainnet" be a simple link to https://torus.crisp.help/en/article/how-do-i-change-the-network-my-wallet-is-connected-to-76n3qh/ in the case that the user is connected to Torus

**Comment by MoeNick** [comment]
@aminlatifi pls leave your comments here, and remind you the bug if you can help

**Comment by aminlatifi** [comment]
It's probably onboardjs and we have plan to remove it in favor or another libaray.
So @marthendalnunes please don't do anything for it yet

**Comment by laurenluz** [comment]
WOW! Switch network works and it's soooo coool:
![image](https://user-images.githubusercontent.com/75490971/150055085-b4db7efb-2280-4355-b38c-38de643e3c11.png)

However, ran into some other issues, I will move this one to done and create new issues for the bugs
