### ISSUE TITLE
When showing people the GIV economy... they have trouble seeing and navigating between the pages

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#443]
These buttons are just hard to see, they need to be more pronounced and obvious... maybe larger bolder text... and louder colors?
![Screen Shot 2022-01-06 at 6 39 42 PM](https://user-images.githubusercontent.com/14945613/148472608-72b50519-6c1c-4d40-9157-29af0246c40b.png)

**Comment by laurenluz** [comment]
@markoprljic can you help w design?

**Comment by markoprljic** [comment]
Yes, aware of this already. Was watching people struggle. Will fix.

**Comment by laurenluz** [comment]
This will get fixed in #414
