### ISSUE TITLE
GIVbacks analytics dashboard

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#444]
related to #336 @mendesfabio is down to help us make a dashboard to display analytics related to GIVbacks.

This dashboard can live at an external link & we can make blog posts after the GIVbacks rounds to talk about the analytics. Some things it would be nice to show:

- [ ] Total amount of donations to verified projects during each (2 week) round
- [ ] Amount USD of donations during the rounds
- [ ] Top donated-to projects during the round
- [ ] Number of unique donors
- [ ] Amount of GIVbacks distributed (maybe this is separated into streaming amount and liquid amount)
- [ ] Round dates

@WhyldWanderer @GriffGreen @divine-comedian are there any other analytics that would be nice to see?

I think the dashboard having its own page would be super cool. I'd love if we had a GIVbacks blog post at the end of the round and we can shot stats like... how many people donated in those 2 weeks, how much was donated, top 5 projects, how much GIVbacks went out etc

**Comment by WhyldWanderer** [comment]
I think that this information should be included in the GIveconomy dashboard... but we could also embed some of this on the GIVbacks page showing info for the previous round.

It would be nice to have 2 dashboards.. 
 - GIVeconomy info
      This would include all of the info [here](https://dune.xyz/metacrypto/giveconomy) as well as the above GIVbacks info.
 - Giveth DApp info
      This would include things like number of donations, total donations amount, number of projects created, number of unique donors, maybe a pie chart of project categories and number of projects in that category, etc. It should include a functionality to select the data date range.. the default would be since the platform launched in March and you could adjust the dates to see info that is only in a certain date range.

**Comment by laurenluz** [comment]
yeah that might be cool - to add a GIVbacks section to the current dune analytics dashboard that Fabio created. What do you think @mendesfabio ?

That's a cool functionality for the Giveth DApp info thing.. I wonder if this is hard to implement or we just have like bar charts & things where each bar represents a period of 1 week or 1 round. @mendesfabio ?

**Comment by nauzystan** [comment]
I think your ideas concerning the features of the Dashboard is great. However, I think it'd be nice to also include the formula (With each variable well defined) utilized in the distribution of Givebacks on the Post-blog post. I don't know if this is already in the agenda.

**Comment by divine-comedian** [comment]
> I think your ideas concerning the features of the Dashboard is great. However, I think it'd be nice to also include the formula (With each variable well defined) utilized in the distribution of Givebacks on the Post-blog post. I don't know if this is already in the agenda.

We just mentioned this in a call with some of the devs to add to our formal documentation! 

I would agree with @WhyldWanderer  that having two dashboards would be better - there's already lots of information on the GIVeconomy dashboard so it would be good to break it up somehow and have it less intimidating

**Comment by laurenluz** [comment]
The formula for calculating GIVbacks is already in our documentation @divine-comedian https://docs.giveth.io/giveconomy/givbacks

Are you talking about some other formula?

**Comment by divine-comedian** [comment]
> The formula for calculating GIVbacks is already in our documentation @divine-comedian https://docs.giveth.io/giveconomy/givbacks
> 
> Are you talking about some other formula?

we we're talking about gettin the exact script/code that is being ran when we use this function 

https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback

**Comment by mendesfabio** [comment]
hello everyone! I was digging into the data we have in Giveth database and it seems doable to build the metrics you all suggested. Just to put everyone on the same page, I started building these two dashboards.

1. [Dune dashboard](https://dune.xyz/metacrypto/giveconomy). Has all information about GIVeconomy and the data comes from the blockchain. If we want to move some of these charts to GIVeconomy dApp then we could either embed the charts from Dune (super easy but we can't change the style -- might not look very good with the rest of the UI) or create a backend with the data we need and ask for some designs (a ton of work here).

2. [Metabase dashboard](https://giveth-dashboard.herokuapp.com/public/dashboard/5218ea60-42ef-416b-80f0-4b58fc78ef49). This is very very WIP! I started making that in May/2021 but it didn't get much traction. It would be feasible to connect this dashboard to Giveth database (right now I have a dump of it) and add the charts you asked for, but we can't customize them. 

I'd like to know better if we need a dashboard for showing on UI vs answering questions. With that in mind and knowing how much time you're open to waiting will help us choose which way we should follow.

**Comment by GriffGreen** [comment]
Let's get the quick and dirty mvp up that answers questions and then worry about design and UI at a later time.

**Comment by GriffGreen** [comment]
http://dashboard.giveth.io/public/dashboard/4717fd91-a311-42cf-93d9-185ec8c08a04?round_range=2022-02-04~2022-02-18

New dashboard is up!

Any feature requests?

**Comment by GriffGreen** [comment]
I would love to see the dates be easily connected to rounds ... i like the ability to customize too... but it would be great if the rounds were easy to select as well.
