### ISSUE TITLE
Azure Server upgrade and subscription

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#445]

**Comment by laurenluz** [comment]
subscription was for 1 year free, we need to reapply to extend subscription

**Comment by MoeNick** [comment]
@willyogo do you have any updates on this?

**Comment by laurenluz** [comment]
Willy has to log in and apply for the extension. it's in progress.

**Comment by laurenluz** [comment]
we have 39 days left on it and a couple grand worth of credit
