### ISSUE TITLE
Make a Snapshot Instance for Governing our Multisigs

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#447]
https://docs.google.com/document/d/1ZPfwCIzVq5kgQkjCf_uX_jsyIX--z5PPTWU97dv8Cbs/edit

Asking pedro to take it on ;-D

**Comment by laurenluz** [comment]
@pkretzschmar let us know if you have any questions! or if you don't have the bandwidth

**Comment by laurenluz** [comment]
We've got a forum post about it! https://forum.giveth.io/t/snapshot-instance-for-managing-multisigs-and-other-general-governance-questions/344/2

**Comment by laurenluz** [comment]
https://snapshot.org/#/giv.eth/proposal/0x1f46ec458a6f3f898285a6d785effb71e81509fb5078d210bb5397fc2395fc59

Test one is here!!

Still missing the univ3s
