### ISSUE TITLE
change onboard.js with web3-react 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#448]
will need to change onboard.js with web3-react - lighter, more configurable & can enable whichever wallets we want

typescript uses web3-react

this will allow us to easily integrate fortmatic wallet

**Comment by laurenluz** [comment]
I am assuming this is done because the wallet connect looks different on staging than production... @aminlatifi I don't know how else to test this. can I just move it to done?

**Comment by aminlatifi** [comment]
> I am assuming this is done because the wallet connect looks different on staging than production... @aminlatifi I don't know how else to test this. can I just move it to done?

You are right, I move it
