### ISSUE TITLE
Solve the issue of many votes to distribute GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#451]
As per @divine-comedian 's comment in discord:

> ⚠️  We have a problem with GIVbacks! 

Sooo.. we have so many addresses available for GIVbacks that to actually send the function via the agen it exceeds the maximum gas limit for the xdai network.... 

Talking with Sem the solution he proposed was to cut the script into pieces - 200 addresses per script - which works but this means just for this first distro we have 4 different votes that are generated and need to be voted on in order to send GIVbacks - as we scale up with GIVbacks this could become substantially more. It also opens up much more possibilities of human error and attack vectors - Already the GIVbacks distro is very susceptible to human error so we need to find or build a contract or an application that will generate the GIVbacks distro votes with very minimal opportunities for human error or mal intention.

https://discordapp.com/channels/679428761438912522/928813033600475207/930867472926670909

**Comment by divine-comedian** [comment]
chatting with @sembrestels and @WhyldWanderer  we came up with a new solution which will take some smart contract magic

basically we'll have to convert the GIVbacks system into a merkleDrop. This means that every 2 weeks we'll need to generate a merkleFile  from GIVbacks data received at the end of every round. We'll also need to create a merkleDistro contract that will disburse GIVbacks GIV allocated to it from the tokenDistro. The nrGIV agent would still be able to control allocating tokenDistro GIV to the GIVbacks merkleDistro. @aminlatifi  what do you think? How can this become automated as well?

To revise then, under this new system the GIVbacks distro would go as follows 
- Round ends, fraud review and analysis begins
- once the review looks good we vote to allocate 1 Million GIV to GIVbacks MerkleDistro
- final data is used to generate MerkleFile 
- MerkleFile is used to disburse GIV from GIVbacks MerkleDistro (who should be able to do this?)

also tagging @GriffGreen for feedback.

**Comment by GriffGreen** [comment]
> basically we'll have to convert the GIVbacks system into a merkleDrop. This means that every 2 weeks we'll need to generate a merkleFile from GIVbacks data received at the end of every round. We'll also need to create a merkleDistro contract that will disburse GIVbacks GIV allocated to it from the tokenDistro. The nrGIV agent would still be able to control allocating tokenDistro GIV to the GIVbacks merkleDistro. @aminlatifi what do you think? How can this become automated as well?

I don't think we should recreate the wheel.

This proposal isn't bad, but it will need a lot more thought as there will be a different merkle drop contracts for every round, so the user would need to collect from each merkle drop... then we will need some sort of multicall so they can collect from multiple merkle drops all in one tx, instead of a single tx for every merkle drop collection... and so on and so on.

Balancer did something similar to this for a year or so, and then moved to a new system... @mendesfabio works with Markus Koch who led this process... lets just look at what they did and use it as opposed to trying to invent something...

But that said... for the next 3-5 rounds... hopefully we can stick with multiple txs and diligent double & triple checking of our votes that everything is right.

**Comment by divine-comedian** [comment]
Okay Sem came over and dropped some more knowledge 

Instead of allocating tokens from the  tokenDistro to the GIVbacks MerkleDistro we instead pass the GIVbacks data into a generic contract that would generate the multiple txs and send them piece by piece to the tokenDistro -

this generic GIVbacks contract would have tigh permissions basically only accepting data from the nrGIV agent (via a vote) we wouldn't have to change any functionality of the tokenDistro

**Comment by divine-comedian** [comment]
> But that said... for the next 3-5 rounds... hopefully we can stick with multiple txs and diligent double & triple checking of our votes that everything is right. 

There are glaring security issues because there are no way to check the script of a vote being voted on before it is executed. there are also no verbose outputs in the voting context so there's actually no way to be sure what's being voted on, so any nrGIV holder could create a fake GIVbacks distro and slip it in. I really have pushback on creating this mess of votes and we need a good solution that doesn't rely on humans checking unfeasible amounts of data.

**Comment by GriffGreen** [comment]
@paxthemax should throw some ideas here too and help us sort this out

**Comment by GriffGreen** [comment]
Remember also... there is a UX, design, front end and all that to worry about for a change of plans. We can live with trust for our team and some manual checking until we have a real solution

**Comment by paxthemax** [comment]
> Okay Sem came over and dropped some more knowledge 
> 
> Instead of allocating tokens from the  tokenDistro to the GIVbacks MerkleDistro we instead pass the GIVbacks data into a generic contract that would generate the multiple txs and send them piece by piece to the tokenDistro -
> 
> this generic GIVbacks contract would have tigh permissions basically only accepting data from the nrGIV agent (via a vote) we wouldn't have to change any functionality of the tokenDistro 
> 
> 

Let me see if I understood this correctly.

Our goal is to create essentially a **state machine** that would crank out the allocate GIV calls to the token distro? Essentially we have a **transaction buffer** where we fill it on one end and empty it on the other.

The nrGIV agent would start a GIVbacks batch and fill it out with GIVbacks. This _should_ fit into a single trasnsaction, but again there is no guarantee especialy if the number of GIVbacks trends upwards.

Once the batch is filled and sealed (all the GIVbacks for the round are confirmed) anyone can empty the buffer by sending an appropriate number of allocations (to fit in the block gas limit).

So we either do a tight coupling (pass and store exact typed values in the contract), or we do a generic executor that stores preformed calls (similar to an on-chain multisig).

Does this mesh with what you and Sem discussed @divine-comedian?

**Comment by aminlatifi** [comment]
> he nrGIV agent would still be able to control allocating tokenDistro GIV to the GIVbacks merkleDistro

Although it's a clever solution and can solve the issue of multiple transactions, there are a couple of points.
The first thing to notice is that we cannot transfer nrGIV balance to another distributor in tokenDistro. To make it clear, we have assigned some balance to nrGIV to allocate later and that can only be consumed by allocating to a non-distributor. If we have new merkleDistros, we must use some of the unused capacity of tokenDistro (total tokens - total assigned values)
Second, as Griff said this way we need some change in UI/UX and implementation.

**Comment by paxthemax** [comment]
Based on the discussion with @divine-comedian and Sem, another approach may be possible - essentially hack a MerkleDrop in such a way that it allows us to distribute GIVBacks to the token distro.

This would mean that:
1. Before the GIVBacks are sent, the merkle tree needs to be computed
2. The nrGIV agent now sends the **merkle tree root** instead of calling `sendGIVBacks(address[], amount[])`
3. After this, anyone can compute a list of merkle proofs
4. Anyone with a valid merkle proof can call a function that will then call `sendGIVBacks`

The advantage of this system is that there is no need to store the data on-chain (significantly cheaper storage costs).

**Comment by laurenluz** [comment]
@paxthemax to write the final solution in this issue :)

**Comment by laurenluz** [comment]
@paxthemax and @aminlatifi to discuss :)

**Comment by laurenluz** [comment]
PR is pending will resolve this issue - @aminlatifi to review PR

**Comment by laurenluz** [comment]
@paxthemax @divine-comedian any updates on this?

**Comment by laurenluz** [comment]
@mohammadranjbarz please follow up with @paxthemax about this :)

**Comment by mohammadranjbarz** [comment]
@paxthemax 

Now if the address of givers are too many, we separate it to multiple commands and Mitch execute it, now if you changed some contracts just tell me to change response of my endpoint 

This is part of our current response

```
connect 0xA1514067E6fE7919FB239aF5259FfF120902b4f9 token-manager voting:1 act agent:0 0x18a46865AAbAf416a970eaA8625CFC430D2364A1 sendGIVbacks(address[],uint256[]) [0xad9c46a9ab1a96ef80001cc5c153cc4b58232da3,0x5d28fe1e9f895464aab52287d85ebff32b351674,0x069e85d4f1010dd961897dc8c095fbb5ff297434,0x826976d7c600d45fb8287ca1d7c76fc8eb732030,0x6851cab6bfadfa47246dd71528c4d519aeb85fd4,0x05a45e7416c77c822e24e9679af29d1f07589b40,0xe7f3722a36f1a08c4db998122553785d94081ebf,0x1210ba92eb82cc256213c78f0ef9d5212c7034a9,0xdef7845ace3b1f5de05c6d4ad68b6a7cfad66303,0x38f80f8f76b1c44b2beefb63bb561f570fb6ddb6,0x5832834966933bec942bb06a3b55dd1176cbddd2,0x00d18ca9782be1caef611017c2fbc1a39779a57c,0x4ff14c2f19cf78ffd249b22d622e6ee7e25b84d8,0x5299c7d2b73b6a96231081dabfd54dfcc84fedeb,0xec952ed8e7c2aa466cac36fd611d2e87df1243d7,0x2920620b47d51170319a531a2d6d5810610e8c2a,0xb00784c401d42f03ccbe1e85b9f2a4ae056c7251,0xb7562f12e41c762cecda99d62bd6eac7b0c3b4c1,0xca4ad39f872e89ef23eabd5716363fc22513e147,0xe0144fa05a0d32b5b1de10ccee7211616b3e3ef0,0x9f55abf3a9b3ab9401131db5961a1845545dbd47,0x0f46540678c7e6d2ef983b382cc07fa815ab148c,0xda5b2cd0d0bb26e79fb3210233ddabdb7de131c9,0x91b7377a3dd7931ad4757b60d7e859954b939e85,0x9de78b32339df46ab670b0c580bdec9ac68acb76,0x9924285ff2207d6e36642b6832a515a6a3aedcab,0x4318cc449b1cbe6d64dd82e16abe58c79e076c2b,0xe54bee8258a2fe65095516f199034a08c02e35fe,0x7ba7fbebf45a83812f4e9bfe8feba60f2df258e5,0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b,0x677ba04bf43bf5477454a17920d45d3d911873ec,0x4bc0ae26936561cb32b26dada4c2fb0577054100,0xad7575aefd4d64520c3269fd24eae1b0e13dbe7b,0x1a7e76c3bc4006e804842c232d91767d3c5299d2,0x77c3db040f79ae46a91529a667c03ab484b37116,0x5255e33362f533a947ba801f4f3a813d82fa8341,0x1e975f53956d644868f3ea25690b1bbeda658565,0x0474f0a3218c3bb5c9747daafdbe0bcd1b293d55,0xde2be7c9c542c55a7a77489a3a7745493988947f,0x8afc051de5f3941a68d3dbb9c7c96ec773ef494b,0x0ab077ec5a53473d42228395d09063d896a23e39,0x9ce595fc0cda2ccce175aa3527ab713a3c46a0f4,0x86aecfc1e3973108ce14b9b741a99d3466127170,0x289daa70ebc217c5ac4ee255f91bf4d75020ad05,0x90d14877ab33c5b6f876f8775884ea1152bf0ba9,0xb8fb4817f506d3f52e9edd2cedc4f046305c99cf,0x861fe68b2ed28f609c08f66a1c0bcc940b9bdc80,0x45233ff6bbc10f0eb41f430561ac97d78ddfb4cd,0xe4f0e8ae1fd76928a6f586a2ec6a120ccdc50a8e,0x58b699fc551314282126fff02b62d2f3e71d8723,0xf42cfe525388486554f8fc3c2ea2ba3414c4f16c,0x05903affd45da43a14f9a9421605e0e7a4fe2e21,0xc1582c0e57a144131d0546128203e8fc6924b17f,0xc9b0e011aa5b50c14cd0ac1b2097363ce39e6b6a,0x3953017af23ab99a7d40f3d26f1595f27c91345f,0x29cf75f4622dbedbc63354e28f6e734635690f4b,0x7c5361f5bb5e2bb123c95e69bed331f3b0b8f094,0xcc3b8fc85c0db2617b7b64def90976c2a7731945,0xc9069928877b86d224c490b725ce270fcf363aba,0x65ae75ef8c5e7fdde20eecdb14ec1f7a53258f53,0xa4d3316b09125c0d1bbfe757f43d3aae4e4e9d8f,0x0662512cebcc355f8929847e1742b71047c95903,0xf7e7767b5d0368a37a2f98a87caaf6f4932d3a57,0x6a8076e1b8fc43d5e07d03ba090d7a19e1cdafd1,0x6f97da40d29ae94002ca2a62eb472e8ba583fa24,0xb82210ce07439b3125b3e43914e9f0cab438bb69,0xef4fd55584434903aa6fc9baa61eacdde5355da0,0x0853cd6c0a69cc7d544791890b357c013be36038,0xdeb08d04004ea00bb6898d19267f7d3399e2827d,0x206086773f541a810d91bba403b86cd473e39dfd,0x356930cad4554f95f425d5ef8c22bca952c1aed1,0x0ef45a1dffcf0ff582b6ceb9aff3c11f72813125,0x194c9783fa5e984859641f3566ccd77f07a680bc,0xd073b70d1db844953bbfd8206774194bd9b0bca5,0xf57da33ce1c3decff23a7af5aee56dd8c91e6433,0x70b1d9f7cf075a1326374d5c84de877ae9ad2b0c,0x7403aeb52986bf0004b815373e056a7e511f13e7,0x3ec0a2550c32029ba981dc3bd6e8d5a259c12c1a,0xdf34cad4af71f36d0dbb75bdde1ee8628a16187d,0x66339e64c3447f32251a3baf79bc7f4192fd1386,0xd007f68d7370fbceecb4e32df6866011fd535baa,0x049c7f5322d05383c0367c88ecbedd05b4bb7fa9,0x845f2b2e5731a580bcd22043a561870105c36a03,0xcdf08da38f0707e2399fa9eb4327f5c5c0a44da5,0x980c8167a29def069125c53da9659f73ea54f1c7,0x223e18aad8a6be5e7fa1aadf0b8b0a6dc7a0b20a,0x9d142975a28e207cd04b1a6d34ccd6171323953b,0xcac9f312284b2f29af0ea876b2b19aa5664bb159,0xd3c6ce98b17e3d5b2b0511fe75b84f9352e3399d,0xa4d08e73b3ac2582d12a45c5a52643c142dd8d31,0x0e60b5120a37a77e5df8464ff1711425e62e9819,0x85e479fc7d4469344697aa76c5d78b7390427198,0x6579cf814a97fe2c40e23b78547bf3861075ae2e,0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c,0x016377ee37d9a8806aa1a2cd727ac9944688b9f1,0xcf5f9d188178482ab624b58f0a6d03d257a69339,0xa0b2e0ab3fbdd30acf7f253a8df46a802a77e48f,0x4e490d78af8fab214080c0afb73aa74b118f6ecf,0xf7d770b673e5fbb5e339e8f7166618d82a5aed25,0xf41113ad65135685ff9f38a10989cfd619e2f4fc,0x14f98d447e8347dbea408b6c5ec7b803d0cd3f74,0xef8413c1e66c2b1b90aa32929b207a2f24c123ac,0x7553b85a80021c353ca2a75ddc516e3813ddde1e,0xb7c4cd8c786e14738c47612607f09e1d2b175b1c,0x63d1e58fa5fa4e98dc36dbd4615231d8d4b69043,0x028dc919c77af954c2f3ac5ffe9f764d7570b1b8,0x243f5dead21bd50bad298e0efd5ed0e957e8bf0a,0x1510c90c957a839e30be9667eaff20eb7308cacf,0x741defd696606710bbfdcdaac6bb16511e49347e,0x826840dd008d47b42574e30e6fd081d8e125c835,0xcc3e7ca58c2425517397be6691d26240a275c3f4,0x0bd346bb45cb546da543e99f1a14db647c965420,0x86358a2d9a39d34d14f419c4b6345e9e80c0c83d,0x118fec52d93992bbbe9a5b3ec9b5ecd865aff51a,0xba229148320935c4b6a40becde07d854f3348778,0x0d10a3681431c2277fbd72c07ebd5f4a1afc0871,0xccbd75c89ac0d81c0ab4c0e83c4d38027369a86e,0xf55ee4ffcd402e54ea1c79956aae03657fe8cffc,0xfbce959f52860f2a1058fc9a5c0db9912b174e77,0x99c09d7b7a06c30b7af9710eef4991c82bac14cf,0x54fdea47445e321276f1ea3130cfefc83383e89d,0x2953192c139520ba002a0f010c5b4497368b6397,0xc587647c5f96eac5ad37dfc298f02427a07967aa,0x1541ade7e3f6ea94b065de68c53183ef23cd5a6c,0x7b698e8aaa69f6f090e596f0de6259b48a9a95f0,0x7d678b9218ac289e0c9f18c82f546c988bfe3022,0xcf51cf562d1bd5dcbd705039ad7a661f6d12bf85,0x58f16dcd62753cdca01b4f085d71498bb26320de,0x2473fb8eebe46041d5f528a728505c26a81c1158] [1894650000000000200000,1289300000000000000000,750000000000000000000,500080000000000000000,471920000000000000000,341250000000000000000,258589999999999970000,171680000000000000000,166500000000000000000,151880000000000000000,144060000000000000000,129650000000000000000,107510000000000000000,103920000000000000000,86710000000000000000,67500000000000000000,58640000000000000000,51100000000000000000,49760000000000000000,49690000000000000000,48370000000000000000,48010000000000000000,47060000000000000000,45910000000000000000,45820000000000000000,34640000000000000000,30510000000000000000,26670000000000000000,26460000000000000000,25270000000000000000,24970000000000000000,16600000000000002000,15100000000000000000,13350000000000000000,11800000000000000000,11550000000000000000,10220000000000000000,8250000000000000000,7500000000000000000,7500000000000000000,6750000000000000000,6680000000000000000,6450000000000000000,6370000000000000000,6310000000000000000,5920000000000000000,5350000000000000000,5330000000000000000,4810000000000000000,4530000000000000000,4420000000000000000,4130000000000000000,3970000000000000000,3750000000000000000,2700000000000000000,2630000000000000000,2610000000000000000,2560000000000000000,2560000000000000000,2320000000000000000,2250000000000000000,2250000000000000000,2100000000000000000,2020000000000000000,1830000000000000000,1530000000000000000,1510000000000000000,1450000000000000000,1420000000000000000,1050000000000000000,1040000000000000000,900000000000000000,900000000000000000,900000000000000000,900000000000000000,900000000000000000,900000000000000000,900000000000000000,900000000000000000,830000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,750000000000000000,680000000000000000,680000000000000000,680000000000000000,680000000000000000,680000000000000000,680000000000000000,680000000000000000,680000000000000000,580000000000000000,540000000000000060,530000000000000000,520000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,490000000000000000,480000000000000000,480000000000000000,480000000000000000,460000000000000000,450000000000000000,450000000000000000,310000000000000000]
```

You can call it directly to see the response:

'https://givback.develop.giveth.io/calculate-givback?startDate=2022%2F01%2F14-16%3A00%3A00&endDate=2022%2F01%2F28-16%3A00%3A00&givPrice=1&givAvailable=1000000&givMaxFactor=0.75&nrGIVAddress=0xA1514067E6fE7919FB239aF5259FfF120902b4f9&tokenDistroAddress=0x18a46865AAbAf416a970eaA8625CFC430D2364A1&distributorAddress=agent%3A0&maxAddressesPerFunctionCall=200&download=no

 @divine-comedian  please tell me if i missed something

**Comment by divine-comedian** [comment]
With the relayer contract in place, now the agent should send only one transaction, to the relayer contract which contains all of the information for the GIVbacks round distribution. The relayer contract will then process this information and create multiple txs that are forwarded to the tokenDistro - @paxthemax  needs to define how this information is structured so we can modify the `calculate-givbacks` API output

**Comment by GriffGreen** [comment]
AMAZING

**Comment by divine-comedian** [comment]
@paxthemax  do we have any progress on this issue? can you please coordinate w/ mohammad

**Comment by laurenluz** [comment]
w/ the relayer contract thing done... we can close, right @divine-comedian ?

**Comment by divine-comedian** [comment]
yessss
