### ISSUE TITLE
Make account to manage CMC listing

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#454]
And get them to make sure that our circulating supply is updating based on the API we provided.

@ForestSoleil can you take this on? Seems like we need to make some kind of profile. This is our listing: https://coinmarketcap.com/currencies/giveth/

I forwarded you the email they sent me after I applied.

Here's the spreadsheet explaining something about the onboarding process.
https://docs.google.com/presentation/d/1p0-EjHE4ELpLZ8kwzP855L5x3uq941oUpCfIYSraa0g/edit#slide=id.g88e0475fa0_0_3

**Comment by ForestSoleil** [comment]
1. Asset is listed on CMC.

2. Created and verified an account on Coin Market Cap
_**Where is a secure place for me to store the login info for others who may need to access it? I realize github is publicly visible.**__

3. Emailed the support team with our verified email/URL according to our actual domain. 

4 & 5. @laurenluz can you please post the following to twitter?

This is a verification post to register info{at}giveth{dot}io to manage our Giveth.io Coin Market Cap listing & correct it to update our circulating supply based on our API. Https://coinmarketcap.com/currencies/giveth/

6. Lauren please post the twitter link here when done so I can share it with the support team. 

7. Then I will complete the rest of the form and onboarding process with CMC.

**Comment by laurenluz** [comment]
Here you go: https://twitter.com/Givethio/status/1488999036375994373

You can send me the login info in a DM, I think we can put it in the ops channel, just waiting to make sure that it's secure

**Comment by ForestSoleil** [comment]
Thanks, I submit this to support and am working through the lengthy application with them.
