### ISSUE TITLE
Get GIV on Zapper

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#456]

**Comment by laurenluz** [comment]
Chadfi can do it!

@laurenluz to assign

**Comment by laurenluz** [comment]
Hey @chad-fi !

So this issue is to get the GIV token (an our GIVfarms) on https://zapper.fi/dashboard

Here is GIV on coingecko: https://www.coingecko.com/en/coins/giveth

Here are our GIVfarms: https://giv.giveth.io/givfarm

I'm not totally sure how to do this, so the first step would be to investigate that... See the requirements etc. If you find some form or something and need some input on what to put in it, put it in this issue and tag me :)

**Comment by chad-fi** [comment]
Looks like Willy put in a request already to add Giveth to Zapper: https://features.zapper.fi/protocol-requests/p/httpsgivethio

I'll see what I can do to push this forward.

**Comment by laurenluz** [comment]
haha WOW @willyogo you're so cool 😎 

Thanks for looking into it @chad-fi ! Lmk if you have any questions or need support pushing it through

**Comment by chad-fi** [comment]
@laurenluz to push this forward we need people to interact with and vote for the integration (linked above). The number of votes has been more or less stagnant. I work on a post to announcements channel with a funny a meme or something to grab attention. I wanted to make an announcement in the community call but have lots of conflicts on meeting times with my 9-5 :/
