### ISSUE TITLE
Add "Buy GIV token" to GIVeconomy landing page

### ISSUE THREAD

**Issue by markoprljic** [Giveth/GIVeconomy#458]
On the GIVdrop panel add option to Buy GIV tokens. See attached mockup. 

![Image 2022-01-17 at 1.57.41 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/4182494e-0da8-4023-9f13-91bd3671aa1b)

**Comment by laurenluz** [comment]
closing this issue because it is part of $414
