### ISSUE TITLE
Change GIVdrop icon in the GIVstream history table

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#462]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/90d6e097-dbc5-413d-9abe-0afa99b472d3)

It should be, as per @markoprljic 's comment in the discord:

![image](https://user-images.githubusercontent.com/75490971/150051543-72ddd4e6-3ec2-47e0-99fd-062d19e5dde1.png)

@MohammadPCh

**Comment by markoprljic** [comment]
![Image 2022-01-17 at 4 12 39 pm](https://user-images.githubusercontent.com/5704285/150120548-f8f782b2-1d71-48b5-afe0-7a721b2090e5.jpg)

**Comment by laurenluz** [comment]
looks g8
