### ISSUE TITLE
Trying to use Torus wallet with GIVfarm - can't stake

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#464]
I was able to connect just fine, but tried testing using the GIVfarm... I clicked approve, signed the tx... then it got stuck "pending"
![image](https://user-images.githubusercontent.com/75490971/150054897-2acc1304-13fc-47e9-b94b-74a7bcb31f61.png)

**Comment by aminlatifi** [comment]
@laurenluz I tried today and I could. Did you use Chrome?

**Comment by aminlatifi** [comment]
![image](https://user-images.githubusercontent.com/5684607/150074456-957d926d-7074-4e11-b137-0f850e4a9230.png)

**Comment by aminlatifi** [comment]
@laurenluz You are right, sometimes it happens. I have difficulties in staking sometimes, but I consider it Torus internal issue rather than our dapp.

**Comment by aminlatifi** [comment]
Maybe this error cause Torus not work and it's not related to us
![image](https://user-images.githubusercontent.com/5684607/150078019-93f89e93-5c22-42e7-a0fd-8be9e83bd83e.png)

**Comment by aminlatifi** [comment]
Submitted an issue to Torus 
https://github.com/torusresearch/torus-embed/issues/410
