### ISSUE TITLE
Failed transaction shows as successful on UI 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#465]
on staging with brave browser w/ clean cache and cookies 

While testing out issue https://github.com/Giveth/GIVeconomy/issues/427

I manipulated the gas limit to intentionally make the transaction fail in order to QA the modal changes.. however when the transaction failed on MetaMask the transaction successful modal popped up on the GIVfarm UI - seems confusing!?

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/18cdf72a-a939-4686-8e84-2a0b7a171e99)

**Comment by aminlatifi** [comment]
@divine-comedian I cannot reproduce with lower gas prices. Which module and what gas price did you use?

**Comment by divine-comedian** [comment]
these are the settings I used in MM - I just tried it and was able to reproduce the error 

![image](https://user-images.githubusercontent.com/67759413/151174895-73ced1d8-3321-4e7c-9851-a83d6dc8d6ab.png)

**Comment by aminlatifi** [comment]
@divine-comedian Get the point, you had entered lower gas limit and the tx failed due to out of gas.

**Comment by laurenluz** [comment]
looks great

![image](https://user-images.githubusercontent.com/75490971/152078363-02d26c2a-8c19-4fa3-814b-f8e010f9cee0.png)
