### ISSUE TITLE
GIVbacks round #, date and time are not updating!! (FIX ME ASAP)!!

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#481]
We're on round 3 but it still says round 1.... Also the dates are wrong.

This should be updating every 2 weeks. Super important!! @MohammadPCh can you fix this asap?

Also it should be starting ever Friday... now it saying monday.

Right now, for me in Costa Rica, it should say:
GIVbacks Round 3
Start Date: Fri Jan 21, 2022 10:00am
End Date: Fri Feb 4, 2022 9:59am

If the times are too complicated we can remove them and just have the date, but this is super important to fix asap.

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/34f0b9d6-dfb5-42f2-b766-4ef0daba7b6d)

**Comment by MohammadPCh** [comment]
The number is correct when the user connects his wallet.
![Screenshot from 2022-01-25 09-41-35](https://user-images.githubusercontent.com/17097576/150921097-3151582e-3d37-4c77-b9d6-1ae24952a1a2.png)
when the wallet is not connected, it shows the wrong number.
my solution is using hardcoded start and end times when the wallet is not connected.
@laurenluz

**Comment by laurenluz** [comment]
That's great Cherik! Super fast ⚡ 

It looks great now, even when my wallet is not connected

![image](https://user-images.githubusercontent.com/75490971/151073470-68377437-6e2e-4074-9b0d-9c0d77c7812c.png)
