### ISSUE TITLE
UI not updating after harvesting rewards

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#484]
I harvested my rewards this morning... The harvest was successful and the tokens showed in my wallet but the UI still has not updated after 1.5 hours. I was able to wrap my tokens in the garden directly but the GIVfarm page showed no change afterward. I have cleared cache, refreshed, signed out and back in, and still no change.

Dani is also experiencing this here:
https://discordapp.com/channels/679428761438912522/835168432520429578/936633906663403560

**Comment by laurenluz** [comment]
@aminlatifi did you investigate this issue at all?

**Comment by laurenluz** [comment]
I just tested it, and from my side, it is working as expected. Both harvesting and staking are working fine on production...

@WhyldWanderer @Danibelle are you still experiencing this issue?

**Comment by WhyldWanderer** [comment]
I'm not having this issue anymore.
There were also reports in the support channel:
https://discord.com/channels/679428761438912522/835168432520429578/936703831214002186
Seems that it was resolved that day by @MohammadPCh and @MoeNick

**Comment by Danibelle** [comment]
I am resolved!

**Comment by laurenluz** [comment]
weird, I will close it and keep an eye out. Make a new issue if you experience it again. thanks fam!
