### ISSUE TITLE
Set up GIVmatching pool

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#485]
As per https://forum.giveth.io/t/givmatching-mvp-the-now-part/345/8

**Comment by laurenluz** [comment]
@playingleela post the designs for this in here when you have them ready please :)

**Comment by playingleela** [comment]
heyy lauren, here it goes the banner, let me know if this size works and if you need any changes (:
<img width="698" alt="Frame (13)" src="https://user-images.githubusercontent.com/94190369/152191801-e48cc1c1-654b-477d-ad49-a0cfeebf028d.png">
