### ISSUE TITLE
APR on univ3 pool is wrong

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#486]
Reported by a user, it appears that the APR is off by a factor of 10. @aminlatifi would be great if you could investigate this

**Comment by aminlatifi** [comment]
@paxthemax the logic of uniswap apr calculation is here 
https://github.com/Giveth/liquidity-mining-dapp/blob/5da8e097f6d1f67f36c427d839ebd1e9da1548ac/src/context/positions.context.tsx#L237

**Comment by MoeNick** [comment]
Shall you pls update us here? @aminlatifi is calculating the maximum in-progress?

**Comment by aminlatifi** [comment]
> Shall you pls update us here? @aminlatifi is calculating the maximum in-progress?

The minimum APr is obtained and shown on front-end right now. To calculate the maximum apr we need liquidity in price range value which should be followed by this issue #496
