### ISSUE TITLE
Get GIVtoken logo on uniswap

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#488]
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0bb47a1b-1cfd-43f5-a835-6fef0a400d4e)

**Comment by chad-fi** [comment]
UniSwap uses the TrustWallet assest repo to list tokens. Some instructions below. We'll need to pay a fee in BNB or TWT upon submission.

Instructions:
https://community.trustwallet.com/t/how-to-submit-a-token-logo/3863

ERC-20 Repo:
https://github.com/trustwallet/assets/tree/master/blockchains/ethereum/assets

Who would have a high-res logo and which wallet should we use to pay the fee?

**Comment by chad-fi** [comment]
https://github.com/trustwallet/assets/pull/16846

Once again, looks like @willyogo is on top of it! What support can I give you on this?

**Comment by laurenluz** [comment]
@willyogo anything we can do to bump this?
