### ISSUE TITLE
$$$ not showing up in NFT harvest modal

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#489]
![Screen Shot 2022-02-04 at 6 28 24 AM](https://user-images.githubusercontent.com/14945613/152529170-4f55ec50-f18d-4763-8a67-5ee9f6b5d985.png)

**Comment by laurenluz** [comment]
@MohammadPCh @aminlatifi can you look into this? it looks ok for me but Griff was having this issue

**Comment by laurenluz** [comment]
Griff tested and it looks good!
