### ISSUE TITLE
Stake our DAO-owner univ3 LP into the GIVfarm

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#501]
We have a univ3 pool that the liquidity multisig controls. We should stake it! The multisig will need to interact w the farm to stake it.

@divine-comedian can you take it?

https://etherscan.io/tx/0x28e8d81e6077db26bde9818770d8d2c68266b9a0c4c38bd763289b6566454724

^this is the position that was transferred to the multisig

**Comment by divine-comedian** [comment]
We'll have to get wallet connect up and running for the GIVeconomy, this would be the safest way to stake the NFT. I created an issue with some troubles I had getting WalletConnect to work with gnosis-safe. 

https://github.com/Giveth/GIVeconomy/issues/502

**Comment by divine-comedian** [comment]
tx pending - https://gnosis-safe.io/app/eth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/balances

**Comment by divine-comedian** [comment]
DONE! 

https://etherscan.io/tx/0xae28979b6d2654016bed15a55415d5464258b3aacb618cbf2fb305d1c2fc01ff
