### ISSUE TITLE
Single Project Public View: GivBacks toast should change, with a Learn More link to Docs

### ISSUE THREAD

**Issue by MoeNick** [Giveth/GIVeconomy#506]
This is the required design change:

https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=1908%3A67350 

Please link "Learn More" to https://docs.giveth.io/giveconomy/givbacks

**Comment by laurenluz** [comment]
works as described for verified projects on live
![image](https://user-images.githubusercontent.com/75490971/159535290-9afc3228-3d57-4733-a8eb-fbb36fae2754.png)
