### ISSUE TITLE
Analyze subgraph to determine who is providing univ3 liquidity

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#510]
see how many people, how much liquidity... we will pay their rewards if/when we shut off univ3

**Comment by aminlatifi** [comment]
The list of staked positions and their liquidity can be obtained by running the below query here https://api.thegraph.com/subgraphs/name/giveth/giveth-economy-mainnet/graphql

```
{
  uniswapPositions(first:100, where:{staked:true} ){
    id
    liquidity
    staker
  }
}
```
