### ISSUE TITLE
Regen Farms - Create outreach materials for other DAOs

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#516]

**Comment by laurenluz** [comment]
@aminlatifi to prepare a document in hackMD

**Comment by aminlatifi** [comment]
> @aminlatifi to prepare a document in hackMD

https://hackmd.io/@latifi/H1f5_Ctz9

**Comment by divine-comedian** [comment]
@aminlatifi  Reviewed and fixed some grammar! looks pretty awesome

**Comment by laurenluz** [comment]
@aminlatifi @divine-comedian do you think we should add this to our giveth docs? I wrote some basic Regen Farms documentation but left out the technical details

**Comment by aminlatifi** [comment]
Thanks @divine-comedian

**Comment by aminlatifi** [comment]
> @aminlatifi @divine-comedian do you think we should add this to our giveth docs? I wrote some basic Regen Farms documentation but left out the technical details

@laurenluz I couldn't find Regen Farms in docs.giveth.io. BTW, if the new doc covers all of that, can supersede the old one. Otherwise we should merge them together.

**Comment by laurenluz** [comment]
@divine-comedian can you add it as a new section under here?

![image](https://user-images.githubusercontent.com/75490971/161124064-20808fb1-b4a1-4640-8f76-a4bf79da51da.png)

**Comment by divine-comedian** [comment]
live! 
https://docs.giveth.io/dapps/regenFarmContracts

**Comment by laurenluz** [comment]
Thanks Mitch!
