### ISSUE TITLE
Can't unstake from sushiwasp stake

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#517]
<img width="1488" alt="Screen Shot 2022-03-12 at 11 25 27 AM" src="https://user-images.githubusercontent.com/14945613/158026144-fb78712d-f674-4ec6-aff9-4f00a07d2adf.png">

Tried unstaking just half, tried refreshing, changing accounts... I didnt restart the browser or the computer

I'm using brave

**Comment by aminlatifi** [comment]
Remove xdai network from metamask and add it again, you can use network switch capability of giv economy

**Comment by GriffGreen** [comment]
works!
