### ISSUE TITLE
Make the GIV/DAI univ2 pool

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#519]
The people have spoken! Let’s use this 5 ETH from optimism for a GIV/DAI Univ2 on Mainnet. So we need to:

- sell the ETH for DAI (@GriffGreen currently has access to it)
- send the DAI to our multisig
- make the pool on univ2 from our multisig on mainnet (@divine-comedian is our man!)

The forum post:
https://forum.giveth.io/t/where-do-we-put-the-5-eth-from-optimism-which-liquidity-pool/427

I just talked w Griff about this and it would be nice to wait a lil' because ETH is down today

**Comment by GriffGreen** [comment]
Converted the ETH to DAI and Sent the DAI!

**Comment by laurenluz** [comment]
LP is in our multisig!!
