### ISSUE TITLE
Implementing Giving block API

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#52]

**Comment by WhyldWanderer** [comment]
The progress of the implementation can be found in this epic: https://github.com/Giveth/giveth-next/issues/217

**Comment by WhyldWanderer** [comment]
Update: There is still ongoing discussion as to if we will still list Giving Block projects even if they can't accept GIV tokens.

Carlos will have everything ready to go before launch and if we choose to list them, it will just take the push of a button...

**Comment by laurenluz** [comment]
need to add a tweet on the giving block projects that says "ask Gemini to list the GIV token"!

Mateo added GUSD token to pricing library

**Comment by laurenluz** [comment]
ready for testing
