### ISSUE TITLE
Create snapshot of univ3 stakers that are remaining on March 21

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#521]
@aminlatifi we know how to do this right?

**Comment by laurenluz** [comment]
we can take snapshot a block after we turn off the rewards
@GriffGreen to connect @aminlatifi to Jordi for access to an archive node
can get stakers position for subgraph and determine  reward for each one

To turn off:
need to upgrade the smart contract 
@paxthemax and @aminlatifi need to sync on this

Two things:
prepare upgrade by multisig and prepare script for computing the reward

**Comment by paxthemax** [comment]
@aminlatifi FYI this should offer archival services https://www.alchemy.com/supernode

**Comment by GriffGreen** [comment]
I think we have a winner!

**Comment by aminlatifi** [comment]
The code to report staker rewards at a specific block is prepared.

I ran it against an old block and the report is this:
[sample_report_block_14415352.txt](https://github.com/Giveth/GIVeconomy/files/8309039/sample_report_block_14415352.txt)

**Comment by aminlatifi** [comment]
The code is pushed here 
https://github.com/Giveth/uniswap-stakers-report
