### ISSUE TITLE
Distribute outstanding Univ3 rewards via GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#522]
After we shut if off March 21

**Comment by laurenluz** [comment]
We have two ways of doing this:
- multisend 
- GIVbacks trigger

let's use the multisend... they won't need to claim it, it will just show up in their wallet (and will come from token distro)

**Comment by laurenluz** [comment]
Yesterday we said we'd send out the rewards within 60 days, so we *do* have time, but it would be nice to get this out and be done with univ3 asap.

@aminlatifi @divine-comedian can you guys coordinate on setting up the vote to distribute the rewards?

**Comment by divine-comedian** [comment]
@aminlatifi  to confirm we would use the `allocateMany` function within the tokenDistro instead of `sendGIVbacks`? This would directly send GIV to the specified addresses and allocate them a GIVstream? 

tokenDistro contract - https://blockscout.com/xdai/mainnet/address/0x187aAFEd586AbB1A4D114aaE255e8641749d96a7/contracts

**Comment by laurenluz** [comment]
btw I would love it if this allocation to the GIVstream showed up in the history table with the table "GIVfarm"

**Comment by aminlatifi** [comment]
> @aminlatifi to confirm we would use the `allocateMany` function within the tokenDistro instead of `sendGIVbacks`? This would directly send GIV to the specified addresses and allocate them a GIVstream?
> 
> tokenDistro contract - https://blockscout.com/xdai/mainnet/address/0x187aAFEd586AbB1A4D114aaE255e8641749d96a7/contracts

Yes, `allocateMany` exactly does that.

**Comment by aminlatifi** [comment]
> btw I would love it if this allocation to the GIVstream showed up in the history table with the table "GIVfarm"

@laurenluz We can do it after the `allocateMany` tx goes through. We can use the txHas to mark all allocations on that tx as GIVfarm
