### ISSUE TITLE
Update Circulating Supply for CMC

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#524]
Related to #454

**Comment by divine-comedian** [comment]
waiting to get access credentials to the giveth CMC acct - the current ones posted don't seem to be working!

**Comment by laurenluz** [comment]
@ForestSoleil also posted them in the ops channel. try that, if not, hopefully she can send them to you via DM :)

**Comment by oyealmond** [comment]
hey @divine-comedian ? Is this still useful?

**Comment by divine-comedian** [comment]
I think we should icebox it
