### ISSUE TITLE
Frontend fix for univ3 pool after it's off

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#526]
The harvest button should be greyed out and a tooltip that explains the situation

@mosaeedi can you help us w a quick mockup of this? I will answer any questions

**Comment by markoprljic** [comment]
Shouldn't we just remove the card all together? For a time being to inform users we can keep the card and just write info "This pool has ended".

![Screenshot 2022-03-18 at 11.15.46.png](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/076dde63-87ec-409d-9a9e-d359430c2ce2)

**Comment by laurenluz** [comment]
They user should still be able to unstake though. 

The APR will be zero and they will not be able to harvest rewards though.

**Comment by mosaeedi** [comment]
The button disabled and the tooltip added in front of the APR

[Link to figma](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=19%3A17721)

**Comment by markoprljic** [comment]
> @mosaeedi I'd prefer this is more obvious information. We can have it maybe as per my suggestion above with blurred (or faded) and info box saying: Please unstake your tokens and check out other available pools. Just add a button OK which brings up the farm again for user to unstake.

"Please unstake your tokens and check out other pools available."

**Comment by mosaeedi** [comment]
![Uploading Screen Shot 2022-03-21 at 5.18.01 PM.png…]()

**Comment by laurenluz** [comment]
@mosaeedi should say:

"This pool is no longer available
Please unstake your tokens and check out other available pools. 
Got it"

then when the user clicks, the harvest button is inaccessible, but they can still "unstake"

**Comment by laurenluz** [comment]
It would be great if you could send that picture... and then the picture of the univ3 pool with "harvest rewards" greyed out, "stake" greyed out, and "unstake" being the only possible option for users who have NFTs staked.

**Comment by mosaeedi** [comment]
## 1. infobox visible
![Screen Shot 2022-03-21 at 5 28 35 PM](https://user-images.githubusercontent.com/13708322/159283009-2ce6397f-d557-4f88-91ce-e57b7a83b2ae.png)


## 2. Infobox closed, only the "unstake" button is active
![Screen Shot 2022-03-21 at 5 29 14 PM](https://user-images.githubusercontent.com/13708322/159283202-2c77f8e2-717a-4a0a-b5d7-e7cbe4680727.png)
