### ISSUE TITLE
In Credit Card when choosing continue with Transak, I get congratulated on my contribution

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#533]
It's my first issue hope I describe it well.

I am not sure if we are already taking credit cards or not yet.

If we are... it is not asking for my details.

If we are not... I think it should be said explicitly that this feature is coming soon. Meanwhile here are the options...

**Comment by RamRamez** [comment]
It's resolved in PR [#313](https://github.com/Giveth/giveth-dapps-v2/pull/313)
It will be merged on next release.
