### ISSUE TITLE
Check for Reciruclated Scholarships from CS via TRACE

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#536]

**Comment by freshelle** [comment]
Highlighted in red the giver address that was granted with scholarship. This is all based on the financial history file downloaded from the CS Association Trace campaign. So far, the ineligible donations identified are those having the same address with the donation and where the scholarship was granted.

There are instances that the scholarship trace recipient is different from the address of the Trusted Seed member upon application and possibly the trace giver/donor address. Currently coordinating with Yineisy, Trusted Seed gardener, to get more details on TS member addresses.
