### ISSUE TITLE
Investigate if Gemini will accept GIVtokens

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#54]

**Comment by DonnaOftadeh** [comment]
Alex → Ashley: Will setup a call and talk about best approach in this week.

**Comment by WhyldWanderer** [comment]
Franck at Gemini is advocating for us to get listed! We wont be able to do it until after launch... they want to see something live and functioning.

Things they need to see from us in the listing process:

Fill out the listing appliction - @willyogo to take this on
We need to pass their security test
Kyc the founders of Giveth
Their marketing team will do a marketing push
We need to find market makers for this token - maybe wintermute.com?
We need to have a acceptable tech audit done

Franck will keep us in the loop as he talks with the Gemini team and lawyers

**Comment by laurenluz** [comment]
Willy submitted the asset listing request form

**Comment by laurenluz** [comment]
We just have to wait until launch!
