### ISSUE TITLE
Determine Feasibility of using GIVstream for rewards for Rari FUSE pool

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#555]
We want to know if we can give rewards using the GIVstream. Perhaps like we did it for univ3.

@aminlatifi & giantkin to determine feasibility. Can use Hardhat for test scenarios.

would need to set rewards price the same as GIV to have the APR show correctly.

**Comment by giantkin** [comment]
We talked. I hope i helped.  Amin is going to play with a new pool and experiment with that one aspect.  I am not sure if we are able to add more than ONE token to the distrubution or not.   (amin, add the Stream token address, and after you look to see if that works, try to add just the straight GIV token address as well?)

**Comment by laurenluz** [comment]
@paxthemax @aminlatifi just a reminder: in today's call we decided it would be best if you tried to deposit a little FEI into the existing pool & them tested to see if the streaming rewards can work.

Send you addresses to @giantkin so he can whitelist you for testing this.
