### ISSUE TITLE
PRIME <> GIV

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#580]
**Content**: $100k Token Swap with PrimeDAO
**ETA**: TBD

**Comment by chad-fi** [comment]
Please add details as they become available. I will create a Phase 1 ticket once we are ready to draft a proposal.

**Comment by laurenluz** [comment]
Talked to Alp & Ata last week, were happy with $100k, then wanted to use a new product that only does token swaps, wanted to use Karpatkey, want to wait until they have their joint LP product thing up and use GIV / PRIME to test drive it.

ETA 2 months until that's up... They are signalling that they want to do it on mainnet. We'd have to set up a burner multisig to set it up. Will cost a couple hundred bucks in gas.

Mitch checking if they want to do a smaller one now on gnosis chain.

**Comment by chad-fi** [comment]
I filled out the "I'm interested" form on 20 MAY and lucascantsleep reached out to me asking if I was interested in talking more in depth about token swaps in general. Setting up something with him this week.

From Mitch: "PRIME now says they want to create a GIV/D2D pool on balancer mainnet probably between 50-100k".

Mitch is taking the lead with Alp.

**Comment by chad-fi** [comment]
- No update from last week, they want us to use their new token swap.
- First person to deposit gets more LP tokens
- Unresponsive but we will continue to ping

**Comment by chad-fi** [comment]
25k is small, we will do it, but Mitch to push for larger pool (100k/100k). Giveth should make LP first. Must make it explicit that GIV tokens cannot be sold, must be used for goverance or held in treasury.

PrimeDAO is a big supporter of public goods - this will be a great alignment.

**Comment by divine-comedian** [comment]
Talked more with Prime, there are in favour of a 50k token swap on mainnet, we will use their tool Prime Deals to facilitate the token swap. This looks to be ready to move ahead pending community approval.

here's the forum post:
https://forum.giveth.io/t/d2d-giv-50k-token-swap/681

**Comment by chad-fi** [comment]
Prime suggested us putting the D2D into their USDC/D2D pool on Balancer and they would like to put their GIV into the GIV/ETH farm and lock it into the GIVfarm.

This is not an acceptable arrangement. Mitch is pushing for a D2D<>GIV pool.

**Comment by chad-fi** [comment]
Forum post updated: 

Swapped tokens will be bridged to Gnosis Chain and deposited into a 4/6 burner multisig (A multisig made for just this single purpose) where we will create a 50/50 GIV/D2D LP on Honeyswap. Once the LP is made, half of each of the minted LP tokens will be sent to each respective DAO, any remainder will be sent back to the participating DAO (D2D to Giveth and GIV to Prime DAO).

**Comment by divine-comedian** [comment]
deal is up! 
https://deals.prime.xyz/deal/89ywop9pTZjXzKfpDPyYk4

**Comment by chad-fi** [comment]
https://snapshot.org/#/giv.eth/proposal/0x4af189cb6b465d3574a189841fd22082c819ce569d49adcf3b005f081d408ff5

**Comment by chad-fi** [comment]
Deal has passed, next step is funding.

**Comment by cemiddleton1** [comment]
Mitch should get this done this week. We have the tokens just need to create the position.

**Comment by chad-fi** [comment]
Copy Pasta:

Mitch should get this done this week. We have the tokens just need to create the position.

**Comment by chad-fi** [comment]
Funds in the multsig, waiting for PrimeDAO to sign txs. Afterwards LPs split 50/50, then leftover GIV sent to Prime, leftover PRIME sent to us.

**Comment by chad-fi** [comment]
TX Hash: 0x4ea64d491175b0810cc65f93ddfcfafd0b6e3c3b268a835a9481da2d20910d67

Pool: https://info.honeyswap.org/#/pair/0xab3cf2cd00e6a341422000ec90687fbc074e0e85

**Comment by chad-fi** [comment]
For posterity, here is the Giveth x Prime Twitter space: https://twitter.com/i/spaces/1MYxNnggwmoxw?s=20
