### ISSUE TITLE
ANT <> GIV

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#581]
**Content**: Token swap with Aragon
**ETA**: TBD

**Comment by chad-fi** [comment]
From Research Call May 11th: "Kind of interested - Follow up in a few weeks"

**Comment by laurenluz** [comment]
they were interested in a regen farm... I don't think a token swap is a good idea. they have almost no liquidity RN. Cotabe will follow up re: regenFarm in a couple of weeks.

**Comment by chad-fi** [comment]
> 

Got it. I'll close this ticket out for now.
