### ISSUE TITLE
Need to bring a Partner in crime for Ashley in Project Verification :)

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/GIVeconomy#59]
@WhyldWanderer I talked with Heather and she will contact you soon! here is her discord and also telegram handle : hanners717

**Comment by laurenluz** [comment]
Looking to hire another person to support @WhyldWanderer in the project verification process.

**Comment by GriffGreen** [comment]
Maybe with Mia, Donna, Forest, and Dani we have enough firepower... Forest might be a good person to run the timeline and make sure things are all happening on time.
