### ISSUE TITLE
Improve GIVbacks Email Notification to show users Wallet address

### ISSUE THREAD

**Issue by markoprljic** [Giveth/GIVeconomy#603]
When sending user notification to claim their GIVbacks it would be good to include the information of users wallet address with which to claim the GIVbacks and the POAP.

Rationale:
Users may have multiple addresses for donations and are eligible to claim GIVbacks, they may not know which wallet address this notification is related to. 
Additionally, power users have many addresses sometimes each used for a different DApp. It becomes hard to keep track of their activity and they usually have to connect with several addresses to find out which one they used for our DApp. 

It is the 6th principle of usability heuristics: Recognition rather than recall

> Minimize the user’s memory load by making objects, actions, and options visible. The user should not have to remember information from one part of the dialogue to another. Instructions for use of the system should be visible or easily retrievable whenever appropriate.

We can ease the pain here and help them recall the address associated with Giveth by adding this information to the email.
"Wallet address associated with your GIVbacks is: 0x..." (In case of multiple addresses we could list them all?)

<img width="811" alt="Screenshot 2022-05-30 at 07 32 32" src="https://user-images.githubusercontent.com/5704285/170923560-4c6c329b-7a7e-464d-8d08-4c6990d9110c.png">

**Comment by laurenluz** [comment]
This would be quite a hefty task, I think. @WhyldWanderer @divine-comedian I think you would have the best advice on this - wdyt?

**Comment by divine-comedian** [comment]
It was actually pretty easy, we were capturing the info already in segment and I mapped it to autopilot.

now when a user makes a donation we update their contact info with `DonorWalletAddress` 

![image](https://user-images.githubusercontent.com/67759413/171267161-cffacd6e-f3c0-4f0c-920a-92057a3e5ec6.png)

when you draft your emails you'll have to use the 'Merge Tag' feature and add in where you want the user's wallet address to show up in the email. 

![image](https://user-images.githubusercontent.com/67759413/171267463-dfea6d22-5ab1-4104-ba78-055b6963264f.png)

**Comment by markoprljic** [comment]
Thank you @divine-comedian 
Alright, so we can move forward with this issue I guess 🙂

**Comment by laurenluz** [comment]
nice hack @ahmadabugosh! but maybe we say "connect your address" instead of "enter your address"?

I feel like "enter" makes it sounds like you could be copy/pasting it in somewhere.

**Comment by markoprljic** [comment]
Yes they just enter the address.

**Comment by ahmadabugosh** [comment]
Done (please close this issue, I don't have access to)

**Comment by laurenluz** [comment]
did you change "enter" to "connect" right? they don't enter the address anywhere 🤔

**Comment by ahmadabugosh** [comment]
@laurenluz yes, I changed it to "connect" :) 

<img width="1027" alt="Screen Shot 2022-06-08 at 10 11 14 PM" src="https://user-images.githubusercontent.com/4855928/172697817-fcfaa37f-0a42-4b37-bae4-bd958a32f0c6.png">

**Comment by laurenluz** [comment]
great!
