### ISSUE TITLE
TRIBE Token Swap

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#606]
https://tribe.fei.money/t/fip-108-tribedao-giveth-token-swap-collaboration/4319

**Comment by MoeNick** [comment]
@laurenluz is there any issue for this for @mosaeedi to start?

**Comment by chad-fi** [comment]
@MoeNick - Yass is the point person for this.
@laurenluz - would you please give Yass access to our Github? I will give her the same Zenhub crash course you gave me.

**Comment by MoeNick** [comment]
Now we have her @spectoregia I think :)

**Comment by spectoregia** [comment]
Thanks @MoeNick! happy to be here now :)

**Comment by laurenluz** [comment]
> @laurenluz is there any issue for this for @mosaeedi to start?

We got started on designing the farm card for FEI deposits already, but that's a different issue #609. I will check out the figma & keep you posted.
