### ISSUE TITLE
HODL vault

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#608]
This issue has been changed from the ICHI loan to the HODL vault to get more liquidity on main net.

Not necessary for launching vault - but opportunity to make interest.
https://forum.giveth.io/t/ichi-loan-proposal-for-giveth-angel-vault/624

**Comment by chad-fi** [comment]
This is being tabled until Todd's new Regen Pool Incentive post is out, and a positive snapshot consensus is reached from the Giveth community.

**Comment by spectoregia** [comment]
we need to lower the loan amount and if ICHI would be interested to borrow the loan and returning it still with 20% interest.
Yass to check with them.

**Comment by Cotabe** [comment]
This issue has been turned into the HODL vault.

@GriffGreen will create a forum post about it.

**Comment by GriffGreen** [comment]
I won't but @dhtal will :-D

**Comment by laurenluz** [comment]
love that guy!

**Comment by Cotabe** [comment]
It's on the forum <3

https://forum.giveth.io/t/giveth-vault-onegiv-treasury-deposit/904

**Comment by divine-comedian** [comment]
# GIVeconomy research

put giv tokens into a giv/ichi univ3 pool
mostly giv and a bit of ichi - manages liquidity to always create buy side liquidity 

promising return of 15% yearly 
would hold NFT of univ3 pool in 

nice thing is we're not paying them funds - if there is a lot of sell we earn ICHI tokens that we can sell to generate funds 

we get a 1% fee on trades on the liq pool

ichi creates demand for its token, when someone buys GIV they use ICHI

no front-end work it's all going through their site

the routing from angel vault was routing issues with oneGIV and GIV - not many pairs on uniswap
ICHI has clear routing so it should work well with the HODL vault

vault is already launch and anyone can deposit into it right now - just need to do snapshot vote to move GIV held in oneGIV multisig.

need a few more days of advice in forum then move to snapshot

**Comment by Cotabe** [comment]
This proposal passed.
@divine-comedian reported that the initial tests were not routing that well. Is it working good now?

**Comment by divine-comedian** [comment]
We had a meeting with them yesterday - routing isn't working very well on uniswap. This is a uniswap problem we can't really fix. 

Arb bots are still generating volume but there is no practical liquidity for end users. ICHI is creating a custom router on cowswap and also working to provider routes for 1inch as well so that we have effective liquidity through the hodl vault via those dexes.
