### ISSUE TITLE
Find cause of conflicts of donation data between amplitude and givback result

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/GIVeconomy#62]

**Comment by mohammadranjbarz** [comment]
@divine-comedian
I couldn't login to amplitude, are sure you added my email(mranjbar.z2993@gmail.com) to project?
and what is the org URL?( I tried giveth)

![Uploading Screen Shot 1400-07-12 at 14.17.36.png…]()

**Comment by divine-comedian** [comment]
I think the invite expired, just sent you a fresh one!

**Comment by mohammadranjbarz** [comment]
> I think the invite expired, just sent you a fresh one!

Thanks, now I joined.
I can't find the diagrams that you have showed to me, how can I find them?

**Comment by divine-comedian** [comment]
you should be able to view them for both dapps in the appropriate pinned dashboard - look for total donations value USD 

![image](https://user-images.githubusercontent.com/67759413/135898184-4ba64b58-5bd7-4813-96c0-66b355064464.png)

**Comment by mohammadranjbarz** [comment]
@DonnaOftadeh 
I put this to sprint backlog, after resolving #81 I should go back to this issue
