### ISSUE TITLE
Treasury management

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#623]
This epic revolves around preparing Giveth for the 2022 bear market to secure & bolster our treasury.

https://forum.giveth.io/t/giveth-austerity-measures/631

**Comment by chad-fi** [comment]
Fundraising Avenues:
1) BitDAO - see ticket above

2) HV Capital - Berlin-based VC. Pitched Giveth in August. Interested and would like to explore the opportunity further. 2nd call planned for 06.10

3) Grapefruit - originally approached for Market Making but they want to also hear our pitch. Potential angel-size tickets. Pitching on 27.09

4) 1kx - met at EthBerlin. first call planned for 27.09

5) Gravity Team - VC and Market Maker. They liked our pitch, planning a 2nd call to introduce the team/Griff and go deeper into details.

6) Hansa Network - they really liked our application. Want to have a call 1st week of October.

7) Radicle - Mitch had an idea to apply for their grants. Could potentially secure up to 100k USD. Working on it also with MoeNick. Need to iron out a lot of details about our Radicle integration project with Giveth and split it into milestones with funding requirements for each.

8) Optimism - application form and social media push. They do retroactive public goods funding and have grants ready to allocate. Potentially Jake would collaborate on this.

**Comment by divine-comedian** [comment]
@spectoregia is working on the grant proposal for radicle! I am helping with copywriting and technical details

**Comment by chad-fi** [comment]
Yass in conversation with Hansa

**Comment by chad-fi** [comment]
Pursuing Australian investor - Yass and Griff in talks.

**Comment by chad-fi** [comment]
Sturgeon Captial - trad VC, possible interest - to be pursued.
