### ISSUE TITLE
NICE Token

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#624]
Bolster treasury by incentivizing donations of DAI to Giveth.

"A token that would reward those who donated DAI, xDAI or other whiteliested tokens with $NICE"

https://forum.giveth.io/t/nice-token-rewarding-those-who-donate-to-giveth/657

**Comment by divine-comedian** [comment]
can we move this issue into an epic? 

We've solidifed a few points of the NICE token and we can begin development and design while @laurenluz and I argue about the rest of the details.

I'm going to make some github issues for design and backend development based on where there were no objections
https://forum.giveth.io/t/nice-token-rewarding-those-who-donate-to-giveth/657/5?u=mitch

**Comment by divine-comedian** [comment]
related issues:
https://github.com/Giveth/givback-calculation/issues/18

**Comment by chad-fi** [comment]
@divine-comedian do you want a standalone epic just for the NICE token? It's currently lumped in with the Austerity Measures epic.

**Comment by divine-comedian** [comment]
@chad-fi 

yes that would be awesome, likley this project is going to have multiple angles that need to be managed so an epic would be helpful

**Comment by spectoregia** [comment]
ideas on the Nice markup. 
the Nice token exists. 
Next steps: currency relation vs. US dollar. Need a conversion rate that is our markup. 1 nice should equal 1USD and we change the price of each item. We would stop using GLOVE.  People can only use Nice to shop.

**Comment by chad-fi** [comment]
Swag prices are done and shipping prices are set (for now). Plan to launch Friday 7/22

**Comment by MoeNick** [comment]
If you guys need any dev efforts , pls let me know to do release planning for this Epic.
