### ISSUE TITLE
Hedgey

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#625]
Investigate how Giveth can use Hedgey protocol to protect treasury.

https://hedgey.finance/

**Comment by Cotabe** [comment]
I reached out to Willy to hear his perspective on Hedgey.

From what I see there are 2 main tools.

1. DAO2DAO token swaps. We don't have a candidate yet.

2. Locking tokens on an NFT for rewards. I don't think it's the best use case for us. As we incentivize token holding through GIVpower a key milestone in our roadmap.

**Comment by divine-comedian** [comment]
# notes from giveconomy research call
won't be a good fit for us - they have a product for token-swaps
they have a product for locking tokens but we already have givpower

would have been good to use hedgey at some point in time for givpower

gitcoin is using it to sell GTC to investors - they can use it to lock tokens and assign them to investors.
not sure it makes sense but a good option to have it in our minds
