### ISSUE TITLE
GIVbacks Reduction

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#626]
In a 2 week epoch, Givers receive 75% of their donation back (over 5 years, GIVstream), so long as total GIVbacks remain under $1M USD worth of GIV tokens. If total donations in an epoch are significant enough such that the $1M USD token equivalent is reached, the GIVbacks threshold will decrease from 75% linearly as a function of the total donations.

Due to the state of the market, giving has significantly decreased, and will likely remain so for the coming months. 
http://dashboard.giveth.io/public/dashboard/4717fd91-a311-42cf-93d9-185ec8c08a04?round_range=2022-03-02~2022-03-16

Should Giveth reduce the 75% GIVback threshold for new donations to prevent inflating market with too many GIV tokens during the bear market?

**Comment by divine-comedian** [comment]
this proposal was rejected via snapshot
https://snapshot.org/#/giv.eth/proposal/0xbf8fc57194189716b23cfe4d15e02a44c88f3d45c37ad6c59077c6560b15ea9f
