### ISSUE TITLE
UMA Success Token

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#627]
Bolster the treasury with stables from VC investors (OTC Desk).

Draft Proposal:
"Proposal to mint and sell a set of “success tokens” in collaboration with UMA to diversify treasury and raise some stablecoin for operational reasons."

Financials:
https://docs.google.com/document/d/1M_3e-uyog1U_WJuadM7Fyma_rCKEtic21LAyTCOeYxc/edit

**Comment by chad-fi** [comment]
- ShapeShift got investors through this method, coinbase ventures, etc.
- Yass to reach out to Willy to get an introduction / more information / gauge appetite
- OTC desk would ask Giveth to back bonus part, if not redeemed (aka don’t hit strike price), GIV tokens would go back to DAO.
- At minimum they buy spot with no slippage (in the form of success token)
    - upside comes from success token exchange in future if GIV goes up
- Summary: Proposal to be made after appetite for investors is gauged.

**Comment by chad-fi** [comment]
Yass having conversation with Willy today.

**Comment by chad-fi** [comment]
https://docs.google.com/spreadsheets/d/1-NPZAEjYvUvIsCTdh9WiDhZfcTahBd6Nd7ujIeqt_p8/edit#gid=0

Yass is mainly in touch with those at the end of the list, they are more involved in the "impact VC" area.

**Comment by chad-fi** [comment]
Direct updates to be made here

**Comment by cemiddleton1** [comment]
On hold

**Comment by chad-fi** [comment]
Lauren met some VCs at conferences and got Yass in touch. Terms will need to be defined once interested investor is identified.
