### ISSUE TITLE
ICHI <> GIV

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#634]
Need a champion for Ichi swap.

**Comment by chad-fi** [comment]
Moving from ICE to Backlog, let's open this back up after Angel vault launch

**Comment by chad-fi** [comment]
Copy Pasta:

Weekly update calls with ICHI - token swap will get brought up on next week's call.

**Comment by chad-fi** [comment]
ICHI Idea: Do it via Angel Vault - have a UniV3 swap with them, execution is a "?", ICHI team is meeting in Paris this week, more updates to come after they brainstorm.

**Comment by Cotabe** [comment]
Yass will reach out to have a call about the token swap specifically

**Comment by chad-fi** [comment]
Pending - potentially this week.
