### ISSUE TITLE
Adding $NICE banner in the donation flow

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/GIVeconomy#637]
When users donate with Stables (DAI, xDAI) on mainnet or Gnosis Chain, we need to communicate with users that they will receive $NICE token.

![Screen Shot 2022-07-13 at 9 11 48 PM](https://user-images.githubusercontent.com/13708322/178802311-57aa5c7a-3386-4a83-8443-bc00f50193c8.png)

## Design resource

Showing banner on Donation flow -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11127%3A202389)

**Comment by divine-comedian** [comment]
thanks @mosaeedi left a simple comment to update the copy

**Comment by mosaeedi** [comment]
Done

**Comment by divine-comedian** [comment]
> Done

$nice! Is there an FE dev that can put this into the app? @MohammadPCh ?

This modal needs to show exclusively on this project page:
https://giveth.io/donate/the-giveth-community-of-makers

**Comment by MohammadPCh** [comment]
@divine-comedian leave it to me :)
