### ISSUE TITLE
Add $NICE banner on homepage

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/GIVeconomy#638]
We need to let users know when users donate with Stables (DAI, xDAI) on mainnet or Gnosis Chain, they will receive $NICE token.

![Screen Shot 2022-07-13 at 9 13 32 PM](https://user-images.githubusercontent.com/13708322/178802520-6a4da107-7e38-4e95-abc6-82b6161de3a3.png)

## Design resource

Showing banner on homepage -> [Figma link](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=11110%3A201713)

**Comment by divine-comedian** [comment]
thanks @mosaeedi left some comments to update the design and copy

**Comment by mosaeedi** [comment]
@divine-comedian it's updated, please take a look

**Comment by divine-comedian** [comment]
looks like @mateodaza is taking on FE implementation

**Comment by divine-comedian** [comment]
I think there was a few unresolved comments regarding the links, if some should be buttons or remain text links, I made some suggestions to @mosaeedi in the figma
