### ISSUE TITLE
Onboard Project Verification Team

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#65]
@WhyldWanderer is almost finished writing this onboarding guide: https://hackmd.io/T6ldIt0eRDmKf-jrnOEVzA?view

@Danibelle @MiA-Engel @hannahjojo 

We want to do a big project verification push before we launch the GIVeconomy (tentatively November 10). Would love to get you all onboarded to support Ashley in the process of reviewing and verifying projects. You down? :)

**Comment by Danibelle** [comment]
Yase!!

**Comment by ForestSoleil** [comment]
> @ForestSoleil - maybe you'd be down to help with scheduling/organization for the verification rounds!!?
> 
> @WhyldWanderer to setup meeting with team to onboard them

Hi loves! Saw I was tagged in something and checked in here. Sure, that sounds cool! Exciting we are gearing up to launch! My last day of maternity leave should be Nov 22. I imagine a few weeks before then Griff and I or the team and I will start discussing what is the most supportive role for me to return in. Sounds like it would be helpful for me to support with project verification organization? I am definitely up for that.

**Comment by laurenluz** [comment]
Onboard meeting complete
As applications come in during the week, new members will take them on for verification
In the future, may schedule weekly hack session (when there are more projects for verification) & when dashboard is ready could schedule hack session

**Comment by WhyldWanderer** [comment]
Team has been onboarded.. currently exploring ways to improve the verification process
