### ISSUE TITLE
BitDAO Funding

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#651]
BitDAO Forum Proposal:
https://discourse.bitdao.io/t/discussion-bitdao-x-giveth-the-future-of-giving/2487

**Comment by chad-fi** [comment]
Yass to attend AEmbassy Twitter Space for a Q&A.

Proposal has great support thus far (11-0).

**Comment by chad-fi** [comment]
Q&A 6/28 - went well, presented Giveth (Yass + Griff).
Yass in touch with ambassador that is promoting Giveth. Suggested to populate / get votes on proposal. 1-2 weeks after proposal bakes it goes to snapshot. First week of July will likely go to snapshot vote. Seeking suggestions on how BitDAO would like to structure this funding (i.e. 2-3M token swap? allocate BitDAO a stream?) ~brian~

Smallest investment so far has been 6M USD (PlsrDAO).

Need to limit their governance/voting power, be mindful of how much liquid GIV we give them (<50% MC). This is where a 5 year stream makes sense, but where does the stream get pulled from? Let's vote on where, maybe the Garden (33% total supply). Selling off 5% of total supply (50M GIV over 5 years) for 2.5M USD. Should consider anti-dumping agreement e.g. governance only, ask them to lock up initial 20% in GIVpower for a year.

Encouraging research team to do DD on BitDAO before we allocate 5% of Giveth.

**Comment by chad-fi** [comment]
Overview:
https://learn.bybit.com/altcoins/what-is-bitdao/

Vesting Schedule:
https://docs.bitdao.io/litepaper-1/tokenomics

Top Holders (Etherscan):
https://etherscan.io/token/0x1a4b46696b2bb4794eb3d4c26f1c55f9170fa4c5#balances

Looks like Bybit (derivative platform, founded in Singapore/China) owns upwards of 22% of the total 10B BIT token. Bybit seems to have been unaffected by the recent contagion and has a strong business model. We need to be aware that taking funding from BitDAO is essentially proxy funding from Bybit.

The other stakeholders (Peter Thiel, Founders Fund, Pantera, Dragonfly, Spartan) seem to be healthy and it is assumed they do not control a large stake of BIT, although off-chain OTC deals may have been made.

All things considered, I'm open to proceeding.

**Comment by chad-fi** [comment]
We reached out to a lot of ambassadors on Twitter. Their Discord community is very open to Giveth. They suggested getting engagement on the BitDAO forum (Yass actively working on this, looking for a co-author/ambassador lead). We were approached by ambassador that's curating content.

**Comment by chad-fi** [comment]
Arguably the most important thing going on.

Rally CTA in Giveth. Reference Melody's talk. Redirect traffic to CTA. Using .eth.limo, bake website behind that and circulate (e.g. Twitter Spaces). Put something front and center on giveth.io (front page). CTA = vote on Yass's proposal.

Eyes that need to be on this include supporters of BitDAO and Giveth. 

Craft DM (about Giveth, CTA, etc.) and send to all the BitDAO ambassadors - also, go to top users all time and ping them as well. Consider Griff's pitch from Consensus & Twitter Space.

Maintainer.eth reached out to some advertisers for a ~15s video.

@laurenluz

**Comment by chad-fi** [comment]
Blog post circa next week pointing out benefits of partnership - this will be pushed on Twitter to grab attention of bitDAO ambassadors. Yass has been in contact with bitDAO and they are socializing the Giveth proposal to VCs, namely Windranger & Mirana

Next steps (after attention is garnered) is coauthored proposal - this is a near assured homerun after that point.

For Research group - if you are familiar with bitDAO donation recipients (PLSR DAO, EDU DAO, ZK DAO, and Game7), get with Yass on how Giveth is similar so that this can be added to our pitch (i.e. we are supporting the same for good web3 ecosystem, Giveth is from non-profit perspective) ALSO engage with Twitter posts (retweet/like).

**Comment by chad-fi** [comment]
Cotabe to get with EduDAO to see if they are interested in being a Giveth donation recipient on our platform.

**Comment by Cotabe** [comment]
Yass have been working with the team on the BitDAO publications mainly, so the tweet is out, blog post will also get published soon.. can talk more about it on Wednesday

**Comment by chad-fi** [comment]
[Tweet](https://twitter.com/Givethio/status/1558835763697041408)
[Medium](https://medium.com/giveth/giveth-bitdao-a-partnership-to-change-the-world-c9dfcfad6637)

**Comment by spectoregia** [comment]
I have DMed directly 8 members from Windranger and Mirana labs. Shared the tweet/post on BitDAO discord and directly with some community members. Will wait 1-2 days for response. Otherwise, will continue with the fundraising with other Angels/VCs and try to connect it with BitDAO to secure some of the funds with them (I have noticed this is more or less the case with the rest of the projects who were funded by BitDAO).

**Comment by chad-fi** [comment]
- Yass reached out to Game7 who got into BitDAO’s portfolio.
- Cotabe: Reached out to some people in Mirana Venture Firm behind BitDAO. To know more about their investment thesis. EduDAO seems to be very early stage at least.

**Comment by spectoregia** [comment]
We have two members from BitDAO who are actively pursuing our proposal with Windranger and Mirana. They both can put the proposal up for snapshot vote and work with Windranger/Mirana in the background. One was the main driver behind passing Game7 proposal on BitDAO. The other is an active member of Windranger.

**Comment by chad-fi** [comment]
Yass had a call with Jon Allen (Partner in Mirana and Magnus) Sept . Will give updates in Sept 28 research call.

**Comment by chad-fi** [comment]
^Griff rescheduled for tonight (issues with Time Zone, Jon is in Singapore)

**Comment by chad-fi** [comment]
Call on Friday! More updates next call.

**Comment by chad-fi** [comment]
In person meeting in Bogota - details to be published here

**Comment by chad-fi** [comment]
3-way deal (Giveth, BitDAO, Common Stack) in discussion - see Discord Channel for details
