### ISSUE TITLE
update swag shop banner

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#652]
we should update the banner in the swag store to give the user accurate information. 

current banner:
![image](https://user-images.githubusercontent.com/67759413/176497013-ea7ed565-a635-4102-87e2-d95471c7b34b.png)

**Comment by divine-comedian** [comment]
"Get Giveth Swag!"

"Buy Giveth Swag and get it delivered to your door! The Future of Giving, with style. ✨ "

OR 

We make it NICE token specific to give the user better direction, but if we change the swag shop functionality later we might need to change the banner again.

"Got NICE?"

"Spend your NICE tokens to get some stylish Giveth Swag. Thanks for supporting Giveth!"

**Comment by rodricastillo9013** [comment]
![Banner 1 Swag Shop@2x](https://user-images.githubusercontent.com/61791380/176709302-c4b09ac4-b2c6-4ae1-80a3-47d10ced3265.jpg)
 wdyt? @divine-comedian @laurenluz I have to check with @markoprljic if we can use this logo, it is still in WIP.

**Comment by divine-comedian** [comment]
looks great 
@rodricastillo9013 

I'm hoping the token symbol can be updated soon, waiting for updates as marko mentioned.

**Comment by rodricastillo9013** [comment]
I think you can use this banner now! if they agree, we approve the $nice logo @markoprljic @divine-comedian

**Comment by divine-comedian** [comment]
great! when the final banner is finished can you pass it to @laurenluz  to upload to the swag shop

**Comment by rodricastillo9013** [comment]
![Banner 1 Swag Shop@2x](https://user-images.git@laurenluz usercontent.com/61791380/177322211-83e1a50f-03de-40da-9a8c-7b8444cd3493.png)
done! @laurenluz

**Comment by laurenluz** [comment]
I don't actually know how to upload/change the banner. I checked in printful but it doesn't seem to be a setting in there. I think Kristofer would be better for this than me.

**Comment by divine-comedian** [comment]
okay I tagged @kristoferlund in DM for this one.

**Comment by divine-comedian** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/179355816-fd10f705-46b8-432c-98e8-f7afe782b165.png">

DONE! thanks to rodri and kkechy!
