### ISSUE TITLE
User unstaked but still has unharvested giv

### ISSUE THREAD

**Issue by giantkin** [Giveth/GIVeconomy#653]
User unstaked but still has unharvested giv.
userid 204817563840937984  Joshua  in discord.
https://discord.com/channels/679428761438912522/679428761438912525/991875981482676314 link to image of givstream and conversation.

thanks

**Comment by JoshuaDuChene** [comment]
Hiya! To add more context - the GIV/HNY pool was recently archived. But I still had 1,141.45 GIV tokens to be harvested as GIVfarm rewards from that pool. When ticking "Show archived pools" the pool appears, and I'm able to unstake my staked LPs. But the "Harvest Rewards" button is greyed out, so I've been unable to harvest the GIVfarm rewards from the pool.

**Comment by laurenluz** [comment]
@mateodaza @aminlatifi can you guys look into this? I would like it to be possible for the user to still harvest rewards... even from an inactive pool.

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io`

thankfully I still had some GIV/HNY LP still staked on staging.

![image](https://user-images.githubusercontent.com/67759413/179844827-f9565a92-1c41-483c-9480-95a45d90efef.png)

looking at the archived pool I can harvest my rewards and unstake my LPs and I did so successfully. I am not able to stake any LPs to this pool.

this looks to be resolved, moving to DONE
