### ISSUE TITLE
decide swag prices

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#654]
Need to pick some prices for current swag, we have these types of swag (currently)

Hats
Mugs
Big Mugs
Shirts 
Tote Bags

We also need to find the flat fee we want to charge for shipping.

If we should look to a 300-400% markup in order to fully reimburse the cost of swag incurred plus profit then lets try these prices:

hats - 40
mugs - 20
big mugs - 25
shirts - 50
totebags - 20

flat shipping is tough to decide but we shouldn't go over 25 I think. 15 seems like an enticing number but I understand we may incur losses for shipping to further places like india or china.

**Comment by cemiddleton1** [comment]
Can we pass shipping cost to customer? Need to talk to Christopher & team to see what's possible. Griff to ping Tomo.

What are the prices from GIVdrop? 

Minimum 50% gross margin:

flat bill hats (20) - 50
bucket hats (25) - 65
mugs (15) - 30
big mugs (15) - 40
shirts (10) - 60
totebags (20) - 50

**Comment by chad-fi** [comment]
Copy Pasta:

Can we pass shipping cost to customer? Need to talk to Christopher & team to see what's possible. Griff to ping Tomo.

What are the prices from GIVdrop?

Minimum 50% gross margin:

flat bill hats (20) - 50
bucket hats (25) - 65
mugs (15) - 30
big mugs (15) - 40
shirts (10) - 60
totebags (20) - 50
