### ISSUE TITLE
Modify category to support the new structure [Backend]

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/GIVeconomy#655]
We are going to have a new categories structure for the projects,
Right now, we only have a list of categories, but in the new structure, we need to have main categories and then subcategories.

Here is the new category structure:

Main category #1: **Environment & Energy**
↳ Subcategories: Agriculture, Air, Climate, Energy, Land, Oceans, Pollution, Waste, Water, Biodiversity

Main category #2: **Economics & Infrastructure**
↳ Subcategories: Housing, Employment, Finance, Infrastructure, Real Estate

Main category #3: **Health & Wellness**
↳ Subcategories: Food, Nutrition, Health

Main category #4: **Technology & Education**
↳ Subcategories: Technology, Research, Education

Main category #5: **Art & Culture**
↳ Subcategories: Art & Culture, Community, Inclusion

Main category #6: **Non-profit**
↳ Subcategories: --- (We may have subcategories for the Non-profit categories in the future)

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  @alireza-sharifpour 
We added `mainCategory` to search of projects you can see query sample here
https://github.com/Giveth/impact-graph/blob/dec5f9f4f1ba9151d1d8f3e2a62394128037d97d/test/graphqlQueries.ts#L347-L429

And you can get  mainCategories with this new query

```
query {
    mainCategories{
        title
        banner
        slug
        description
        categories {
            name
            value
            isActive
        }
    }
}
```


We didn't merge it yet but I merged it in `develop` so you can test it in  `https://dev.serve.giveth.io/graphql`

**Comment by mohammadranjbarz** [comment]
@MohammadPCh @MoeNick 
It's deployed on staging as well
