### ISSUE TITLE
Empty search result

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/GIVeconomy#660]
If a user searches for something that we can't find any result we show this screen.

![Screen Shot 2022-07-12 at 2.06.58 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/a7d118fd-1dbd-4c71-992b-90431af96439)

### Page structure
![Screen Shot 2022-07-12 at 4.13.56 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/010d2906-59a3-47ce-a8cb-e1be93196991)

## Design resource

[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A201868](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=10923%3A201868)

---

**Comment by mosaeedi** [comment]
@laurenluz We need better examples for the search term that users can try when they land on the empty search result page.

**Comment by laurenluz** [comment]
@NikolaCreatrix or @WhyldWanderer would have a better idea of good search terms for this because they know what kinds of projects we have. Some suggestions off the top of my head:

- open source
- blockchain
- children
- land stewardship
- zero waste
- homelessness
- indigenous
