### ISSUE TITLE
GIVpower small changes 2.0 

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#664]
I know Lauren has already made an issues with some changes to be made. I'm trying not to repeat any other issues.

1. GIVpower card:

1.a Might be confusing that in the card underneath unstake it says the total GIV staked even though not all can be unstaked. IMO, it would be better to have the amount of GIV that can be unstakes, meaning those staked, but not locked.

1.b IMO there should be a link to the locked GIV details in the card.

1.c On the streaming questions mark, this sentence is not understandable to me: "Welcome to the expanding GIViverse! The GIVstream community members with the long-term success of Giveth and the GIVeconomy." I would only keep "Welcome to the expanding GIViverse!" or remove it entirely and only explain How is works.

2 Locked GIV details modal:

2.a Add APR explanation. Example: "This is your average annual rate of return for your unlocked tokens (much lower, huh?)"

2.b Add explanation in total stacked GIV. Example "This is the sum of the GIV you have stacked either lucked or unlocked"

2.c The multiplier shouldn't be rounded because then it shows for example 2 as a multiplier for locking 2,3,4 and 5 rounds.

3. Increase your rewards modal:

3.a I would remove entirely the "I'll do it later" button. Instead, maybe view locked tokens. If they don't want to do it at the moment they can close it.

3.b Remove learn more, till we have the blog about it.

Bonus: 

I think it's important that people can see what their GIVpower at any given time. Maybe between APR and claimable.

**Comment by laurenluz** [comment]
@MohammadPCh

**Comment by laurenluz** [comment]
I made issues for all these, closing this now.
