### ISSUE TITLE
BANK <> GIV

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#665]
BanklessDAO expressed interest at ETHBarcelona. Bankless Academy and Newsletter are several avenues that they are building. Maybe we get a spotlight in the Newsletter with some quotes from Griff and a link to the new BANK<>GIV pool.

**Comment by Cotabe** [comment]
Talked with Tetranome.

Bankless DAO has a TOKEMAK, so that covers part of their liquidity as far as I know. I'm still not that familiar with how they work.

But they are planning to do a token swap with Radical and before with Gitcoin. We can get that ball rolling.

**Comment by chad-fi** [comment]
Giving them option to 1) join BAL pool, 2) BANK<>GIV swap, 3) both

As of this morning, various Bankless sub-DAOs would be interested in onboarding with Giveth. Their next Comms call, we will be brought up.

They are in the pipeline for verification.

**Comment by Cotabe** [comment]
Still give them 3 options.

Check the BANK tokenomics.

**Comment by chad-fi** [comment]
Cotabe created a new telegram group with Bankless

**Comment by chad-fi** [comment]
Had a call with Tetranome and icedcool from Bankless on Sept 27. They did not seem interested in a token swap but wanted to explore partnering in other ways. What is the most beneficial partnership avenue we could seek?

**Comment by chad-fi** [comment]
Possible AMA.
