### ISSUE TITLE
CULT - follow up

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#666]
When rewards are ending for CULT/ETH, we should reach out to ask if they would like to continue the rewards progrma.

**Comment by Cotabe** [comment]
Here are the dates. They are on my calendar already.

CULT regen farm ends GMT: Tue, 15 Nov 2022 15:00:00 GMT
ShapeShift regen farm ends GMT: Sunday, October 2, 2022 16:00:00

**Comment by Cotabe** [comment]
I reached out last week. Will revisit it this week.
