### ISSUE TITLE
Future Features of NICE

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#667]
Incentivizing NICE token use will increase Giveth's POL. This ticket is to track ideas discussed on the forum such as:

1. Do NICE holders get exclusive access to something in Giveth platform? 
2. Do we allow NICE to token holders to stake and earn GIV when certain MC miles stones are met?  
3. Social token w/ collab.land (gated channel tool)
4. NFT minting (PFP whitelist)

Keep in mind - minimum dev is preferable. 

Drop ideas in active forum post!
https://forum.giveth.io/t/nice-token-rewarding-those-who-donate-to-giveth/657

**Comment by chad-fi** [comment]
For POAPs:  nrGIV vote to be created.

[For PFPs: Twitter Teaser](https://twitter.com/Givethio/status/1559525910172389376)

**Comment by chad-fi** [comment]
nrGIV vote to be posted

**Comment by chad-fi** [comment]
POAP vote set to pass today (8/24).

We now have a bounties budget, Cotabe will create bounty proposal.

**Comment by chad-fi** [comment]
https://xdai.aragon.blossom.software/#/nrgiv/0x80446f514aaec7cfb7eb791830a672c5ef047943/

Only ~800 NICE tokens have been minted - how do we pump these numbers up?

**Comment by chad-fi** [comment]
Whitelist for NFT for NICE holders OR NFTs can only be bought with NICE may see a spike in mints.

**Comment by divine-comedian** [comment]
> Whitelist for NFT for NICE holders OR NFTs can only be bought with NICE may see a spike in mints.

I just pinged comms to see if they can shill the pre-mint feature again

**Comment by chad-fi** [comment]
Tweet has been sent, second tweet WIP. Bounty for 1 years worth of POAPs, would be helpful to share the bounty with designers (or via social in general). Bounty is posted on Dework.

Different donation levels are different POAPs.

Gardens vote up for NFTs to get collection - Santi is working to set up smart contracts.
