### ISSUE TITLE
GIVpower total GIVpower

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#668]
@clara-zi locked 750 GIV for 26 rounds. Somehow she got gazillions of GIVpower.

I wasn't able to reproduce this bug

![GIVpower wut.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/7012f39a-13d0-4755-bad9-bac026d988d1
)

**Comment by laurenluz** [comment]
ahh yeah, this isn't her GIVpower... I think this is just some weird other bug. mine looks the same, I made another issue for it :)
