### ISSUE TITLE
Change projects query to support multiple filters and some improvement 

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/GIVeconomy#672]

**Comment by mohammadranjbarz** [comment]
![Screen_Shot_2022-07-27_at_3.39.30_PM.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/bb25f52d-3733-4328-ae2a-a7036b5e77f6)


Now our sorting and filtering is not good because design made us do it in that way, but with new design we should change `projects` query, 
Now filters should be filter ( before it was like sorting) so if you filter by `Accept GIV` you should not get other projects, and you user can send multiple filters together , for instance, projects that are from givingBlock and are givback eligible, ....
other thing like pagination should be as before, filters can be used by mainCategory and category , ...

**Comment by mohammadranjbarz** [comment]
![Screen_Shot_2022-07-27_at_3.39.30_PM.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/bb25f52d-3733-4328-ae2a-a7036b5e77f6)


Now our sorting and filtering is not good because design made us do it in that way, but with new design we should change `projects` query, 
Now filters should be filter ( before it was like sorting) so if you filter by `Accept GIV` you should not get other projects, and you user can send multiple filters together , for instance, projects that are from givingBlock and are givback eligible, ....
other thing like pagination should be as before, filters can be used by mainCategory and category , ...

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  JFYI , @alireza-sharifpour  is the one who is going to implement frontend side, so if you any specific question he can help

@MoeNick  I just mentioned you to stay in the loop

**Comment by MoeNick** [comment]
Issue moved to [Giveth/impact-graph #579](https://github.com/Giveth/impact-graph/issues/579) via [**ZenHub**](https://www.zenhub.com/)
