### ISSUE TITLE
Product request: Impact MAP

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#673]
A lot of donors want to donate to projects that are close to where they are. 

It would be great to have a map with pins that represent the projects where they are geographically.

Here is an example:

https://www.ic.org/directory/

**Comment by Cotabe** [comment]
![map.PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/5abbc449-90f3-465f-94f6-13b36cfdae92)

**Comment by clara-zi** [comment]
I only just saw your issue @Cotabe when I was looking for the 'map' issue that I created. I can take this but for some reason, I can't assign myself. See also:

https://github.com/giveth/giveth-planning/issues/1025

**Comment by Cotabe** [comment]
Awesome. I will close this issue then.
