### ISSUE TITLE
GIVpower Nice to have the locked GIV in unlocking order :)

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#675]
I don't see the logic in which the locked GIVs table is organized. It would be cool to see it from the GIV that will be unlocked first to the latest

**Comment by laurenluz** [comment]
@MohammadPCh how are the locked GIV amounts organized in the table? Are they in order of... date locked? unlock date? something else?

![image](https://user-images.githubusercontent.com/75490971/182488421-2cf41da2-d943-4f92-8a2a-c9261a3da203.png)

**Comment by MohammadPCh** [comment]
as I remember it sorts by date. do you have any suggestions for it?

**Comment by laurenluz** [comment]
hehe I see that you made a PR... I think organizing them by "unlockable at" is best :)

**Comment by WhyldWanderer** [comment]
Tested at https://givpower.vercel.app/givfarm

Looks like it is organizaing them correctly!! 
Good to go!

![image](https://user-images.githubusercontent.com/74267818/182906678-29fa8a8d-0c8a-45cd-904d-b641d144a076.png)
