### ISSUE TITLE
Review Angel Vault Production Launch

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/GIVeconomy#678]
- [x] Unipool Contract distributor should be the notifier
- [x] Unipool contract UNI token address
- [x] Unipool contract distributor to be token distro
- [x] Unipool has Distributoro Role
- [x] Unipool has 6M balance on token Distro
- [ ] Transfer 6M GIV to token distro
- [x] Notify Reward start time should be GMT: Thursday, August 4, 2022 10:00:00
- [x] Notify script cron job

This notion file includes contracts addresses needed
https://www.notion.so/giveth/Deployment-52935e6579034f1b940bbef161e82229
# This will be updated

**Comment by divine-comedian** [comment]
https://gnosis-safe.io/app/eth:0xf924fF0f192f0c7c073161e0d62CE7635114e74f/transactions/multisig_0xf924fF0f192f0c7c073161e0d62CE7635114e74f_0x4a5409ce206d5be3c59e2fadf04adadde82fc177fb74342f24bc05afcbc6f399

**Comment by laurenluz** [comment]
Executed!
