### ISSUE TITLE
Design Nice POAPs

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#682]
Excerpt from Dework Bounty..

> Calling all POAP designers! We’re looking for submissions to design a POAP that we will distribute to eligible donors to Giveth! The winner of this POAP design bounty will receive a contract to design a full set (11-23.. TBD)  that we will continue to distribute to our eligible donors according to established rounds on the Giveth platform.

> This will complement our existing $nice token program, you can read up on it here:https://docs.giveth.io/giveconomy/niceToken/

A full set of 12 POAPs would be good to move forward - I think given the performance of the $nice token 1 POAP every month will be more worth our effort.

More details and assets in the dework bounty;
https://app.dework.xyz/giveth/giveth-dapps-v2?taskId=c334ec87-93ab-46cb-ac7f-a197dbceab7c

**Comment by rodricastillo9013** [comment]
hi @divine-comedian 
<img width="1038" alt="01" src="https://user-images.githubusercontent.com/61791380/201673417-35f061b0-1bf3-489c-a55d-0947ca83039d.png">
<img width="1034" alt="02" src="https://user-images.githubusercontent.com/61791380/201673419-b582c89a-9a3c-41f8-909b-89e595bc7efb.png">
<img width="1034" alt="03" src="https://user-images.githubusercontent.com/61791380/201673421-1e7be5ab-3295-42dc-9d43-0c422415cdc5.png">
<img width="1034" alt="04" src="https://user-images.githubusercontent.com/61791380/201673424-5c5de815-e75e-465a-86b4-bc05f9ffe2df.png">
<img width="1034" alt="05" src="https://user-images.githubusercontent.com/61791380/201673426-5977473f-12fe-4cbe-94f6-d306eb305a1d.png">
<img width="1034" alt="06" src="https://user-images.githubusercontent.com/61791380/201673428-5733db96-bebd-41e8-86a7-cbdd41eea484.png">
<img width="1034" alt="07" src="https://user-images.githubusercontent.com/61791380/201673429-c25b01f9-53ba-487c-8651-e04992c33f9f.png">
<img width="1034" alt="08" src="https://user-images.githubusercontent.com/61791380/201673431-679ecadd-99d3-4c69-bcd1-04dd52d15299.png">
<img width="1034" alt="09" src="https://user-images.githubusercontent.com/61791380/201673432-5a0d031d-63c1-493e-aeb4-55f498d28e64.png">
<img width="1034" alt="10" src="https://user-images.githubusercontent.com/61791380/201673434-384eaf7a-df75-4c47-8021-986320958212.png">
<img width="1034" alt="11" src="https://user-images.githubusercontent.com/61791380/201673440-b1e93fac-d3e0-48b7-9969-1f63b3dbc37d.png">
<img width="1034" alt="12" src="https://user-images.githubusercontent.com/61791380/201673443-82870155-af06-4f96-af52-853dee503107.png">
 here you can leave coments https://www.figma.com/file/LKBHpnxI9sLjde7DzOQIYQ/Giveth-Marketing?node-id=2194%3A19603 thanks :)

**Comment by divine-comedian** [comment]
left feedback in figma, thanks for the awesome designs and update!
