### ISSUE TITLE
Second givpower test env configuration

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/GIVeconomy#694]
@Cotabe Would you prepare this information

1. Start time
2. Round duration

**Note:** In production env, the round duration will be 2 weeks and should be the same GIVback calculation rounds

**Comment by Cotabe** [comment]
Thanks for creating the issue @aminlatifi 

As agreed in the GIVeconomy dev call. Let's keep this params:

1. Start time: Some time today.
2. Round duration: 8 hours.

**Comment by aminlatifi** [comment]
@Cotabe It's done

Init time (start of round 0) is (GMT): Thursday, August 25, 2022 10:00:00
The round duration is 8 hours
Url to test: https://givpower.vercel.app/givfarm
