### ISSUE TITLE
GIVpower - APR (?) after successful staking grammar

### ISSUE THREAD

**Issue by freshelle** [Giveth/GIVeconomy#695]
Add "r" in you.

_"This is **your** rate of return...."_

![image.png](https://images.zenhubusercontent.com/60e263ee73d25c2e2bd82cc4/1fe1cfe8-2ead-4e1e-bf2b-7e4654e5346d)

**Comment by laurenluz** [comment]
looks fixed

![image](https://user-images.githubusercontent.com/75490971/192418555-b0e5dbd0-7c40-4771-89b8-20e85adc9b4d.png)
