### ISSUE TITLE
rGIV: Test assigning new addresses for GIVdrop recipients (rinkeby)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#70]
When we do the GIVdrop, the rGIV DAO (theoretically) will be able to change the claim address for a GIVdrop recipient.

A use case would be, for example, when we didn't have a person's address (who is eligible to claim the GIVdrop)... we're going to assign all these people fake addresses, and then when they get in touch with us we'll change to their real addresses.

We need to use the Rinkeby rGIV DAO to test the feasibility of this. So basically, get one of the addresses from the test GIVdrop that didn't claim it, and try to change it w rGIV.

Need to use Frame for this. Take to @aminlatifi to figure out what functions to call to reallocate tokens.

**Comment by divine-comedian** [comment]
We ran into some problems with assigning the admin on the contract - Amin will work to debug ths issue

**Comment by divine-comedian** [comment]
> > It's not possible to change address of an eligible user later, only owner can claim on behalf of it and define another wallet address as recipient. Owner here can be a multisig wallet or DAO, so we should consider it.
> 
> By owner do you mean owner of the contract? if so then the owner can claim it and then define a new recipient... thats fine.... it's a solution.. but yeah not an easy one, since then we also have to then send them the initial liquid tokens plus the little bit of stream that we get... that seems annoying... so we could just have some part of the rGIV allocation set aside for reassigning addresses?
> 
> > But there is another more important point if we want to have placeholders! As claim function has been written, anyone can claim on behalf of a user. It means a malicious account can claim on behalf of the place holder (e.g. 0x111222333...), then the tokes are transferred to 0x111222333... . It means the tokens will be gone!! In case we want to have placeholders we have to change the MerkleDIstro.sol smart contract. @GriffGreen
> 
> Ok so we don't do place holders... we will have to see what Edu sees as a solution here.

I think if I understood from our work session today that the owner can claim an unclaimed drop to a new recipient using claimTo - this specific method takes parameters 

```
function claimTo(
        uint256 index,
        address account,
        address recipient,
        uint256 amount,
```
@aminlatifi  so as the contract owner can we claim a GIVdrop and send it to a new recipient with this single function? 
account = placeholder address
recipient = updated address 

or did I misunderstand? 

as to the second point from @GriffGreen  the claim method can be called by anyone meaning that if anyone claims the GIVdrop for a placeholder address then the tokens are sent to this null address and become effectively unretrievable. A solution to this could be making the claim method callable by only the affiliated recipient address or by the contract owner.

**Comment by aminlatifi** [comment]
> > > It's not possible to change address of an eligible user later, only owner can claim on behalf of it and define another wallet address as recipient. Owner here can be a multisig wallet or DAO, so we should consider it.
> 
> > 
> 
> > By owner do you mean owner of the contract? if so then the owner can claim it and then define a new recipient... thats fine.... it's a solution.. but yeah not an easy one, since then we also have to then send them the initial liquid tokens plus the little bit of stream that we get... that seems annoying... so we could just have some part of the rGIV allocation set aside for reassigning addresses?
> 
> > 
> 
> > > But there is another more important point if we want to have placeholders! As claim function has been written, anyone can claim on behalf of a user. It means a malicious account can claim on behalf of the place holder (e.g. 0x111222333...), then the tokes are transferred to 0x111222333... . It means the tokens will be gone!! In case we want to have placeholders we have to change the MerkleDIstro.sol smart contract. @GriffGreen
> 
> > 
> 
> > Ok so we don't do place holders... we will have to see what Edu sees as a solution here.
> 
> 
> 
> I think if I understood from our work session today that the owner can claim an unclaimed drop to a new recipient using claimTo - this specific method takes parameters 
> 
> 
> 
> ```
> 
> function claimTo(
> 
>         uint256 index,
> 
>         address account,
> 
>         address recipient,
> 
>         uint256 amount,
> 
> ```
> 
> @aminlatifi  so as the contract owner can we claim a GIVdrop and send it to a new recipient with this single function? 
> 
> account = placeholder address
> 
> recipient = updated address 
> 
> 
> 
> or did I misunderstand? 
> 
> 
> 
> as to the second point from @GriffGreen  the claim method can be called by anyone meaning that if anyone claims the GIVdrop for a placeholder address then the tokens are sent to this null address and become effectively unretrievable. A solution to this could be making the claim method callable by only the affiliated recipient address or by the contract owner.  
> 
> 

Yes that's true

**Comment by divine-comedian** [comment]
This finally successfully executed using the aragon Agent - using the MerkleDistro and MerkleFile 

we called claimTo on a null address (0x0000....) and sent its GIVdrop to a new recipient 

the full transaction can be seen here - https://dashboard.tenderly.co/tx/xdai/0x7c28eda1203c1b4138da0ce306e8b49f2730f3dd2bb450b84e5a3dcdf8256285/contracts
