### ISSUE TITLE
GIVpower Staking Card Tooltip update

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#722]
I think the message coming our of the question mark should be shown on top of the 
Home | Projects | Giveconomy | Community modal

I also suggest editing a bit the text:

"Stacking GIV on this pool grants you voting power on Giveth DAO (gGIV) & support projects with GIVpower. In addition to the APR"

![I1..PNG](https://images.zenhubusercontent.com/6239faf88ad3a4ffddc12d98/0c6e62e7-c892-4b56-ad7e-611556adb050
)

**Comment by laurenluz** [comment]
Some edits to your suggestion:

"Staking GIV in this pool allows you to support projects with GIVpower & grants you voting power in Giveth DAO (gGIV), in addition to the APR."

**Comment by laurenluz** [comment]
@MohammadPCh @RamRamez - super small issue, can we modify this tooltip?

**Comment by RamRamez** [comment]
Fixed on PR [#1569](https://github.com/Giveth/giveth-dapps-v2/pull/1569)
