### ISSUE TITLE
Write migration for changing categories and sub categories

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/GIVeconomy#723]

**Comment by mohammadranjbarz** [comment]
The community WG gave below sheet to @MoeNick 
https://docs.google.com/spreadsheets/d/1DAB5UHCYO4hkw_RLRtz8DLXpGduVDRMHfiW-71H0m8o/edit#gid=0

**Comment by MoeNick** [comment]
@ahmadabugosh can you map the existing cateories and subcategories with the one you suggested?

**Comment by MoeNick** [comment]
These are the currant Main categories that we should map with new ones: 
`{
    "data": {
        "mainCategories": [
            {
                "id": "1",
                "title": "Environment & Energy",
                "banner": "",
                "slug": "environment-and-energy",
                "description": "",
                "categories": [
                    {
                        "id": "9",
                        "source": "IRIS",
                        "name": "agriculture",
                        "value": "Agriculture",
                        "isActive": true
                    },
                    {
                        "id": "10",
                        "source": "IRIS",
                        "name": "air",
                        "value": "Air",
                        "isActive": true
                    },
                    {
                        "id": "11",
                        "source": "IRIS",
                        "name": "biodiversity",
                        "value": "Biodiversity",
                        "isActive": true
                    },
                    {
                        "id": "12",
                        "source": "IRIS",
                        "name": "climate",
                        "value": "Climate",
                        "isActive": true
                    },
                    {
                        "id": "16",
                        "source": "IRIS",
                        "name": "energy",
                        "value": "Energy",
                        "isActive": true
                    },
                    {
                        "id": "20",
                        "source": "IRIS",
                        "name": "land",
                        "value": "Land",
                        "isActive": true
                    },
                    {
                        "id": "21",
                        "source": "IRIS",
                        "name": "oceans",
                        "value": "Oceans",
                        "isActive": true
                    },
                    {
                        "id": "22",
                        "source": "IRIS",
                        "name": "pollution",
                        "value": "Pollution",
                        "isActive": true
                    },
                    {
                        "id": "24",
                        "source": "IRIS",
                        "name": "waste",
                        "value": "Waste",
                        "isActive": true
                    },
                    {
                        "id": "25",
                        "source": "IRIS",
                        "name": "water",
                        "value": "Water",
                        "isActive": true
                    }
                ]
            },
            {
                "id": "2",
                "title": "Economics & Infrastructure",
                "banner": "",
                "slug": "economic-and-infrastructure",
                "description": "",
                "categories": [
                    {
                        "id": "4",
                        "source": "adhoc",
                        "name": "housing",
                        "value": "Housing",
                        "isActive": true
                    },
                    {
                        "id": "15",
                        "source": "IRIS",
                        "name": "employment",
                        "value": "Employment",
                        "isActive": true
                    },
                    {
                        "id": "17",
                        "source": "IRIS",
                        "name": "finance",
                        "value": "Finance",
                        "isActive": true
                    },
                    {
                        "id": "19",
                        "source": "IRIS",
                        "name": "infrastructure",
                        "value": "Infrastructure",
                        "isActive": true
                    },
                    {
                        "id": "23",
                        "source": "IRIS",
                        "name": "real-estate",
                        "value": "Real Estate",
                        "isActive": true
                    }
                ]
            },
            {
                "id": "3",
                "title": "Health & Wellness",
                "banner": "",
                "slug": "health-and-wellness",
                "description": "",
                "categories": [
                    {
                        "id": "2",
                        "source": "adhoc",
                        "name": "food",
                        "value": "Food",
                        "isActive": true
                    },
                    {
                        "id": "7",
                        "source": "adhoc",
                        "name": "nutrition",
                        "value": "Nutrition",
                        "isActive": true
                    },
                    {
                        "id": "18",
                        "source": "IRIS",
                        "name": "health",
                        "value": "Health",
                        "isActive": true
                    }
                ]
            },
            {
                "id": "4",
                "title": "Technology & Education",
                "banner": "",
                "slug": "technology-and-education",
                "description": "",
                "categories": [
                    {
                        "id": "5",
                        "source": "adhoc",
                        "name": "technology",
                        "value": "Technology",
                        "isActive": true
                    },
                    {
                        "id": "6",
                        "source": "adhoc",
                        "name": "research",
                        "value": "Research",
                        "isActive": true
                    },
                    {
                        "id": "14",
                        "source": "IRIS",
                        "name": "education",
                        "value": "Education",
                        "isActive": true
                    }
                ]
            },
            {
                "id": "5",
                "title": "Art & Culture",
                "banner": "",
                "slug": "art-and-culture",
                "description": "",
                "categories": [
                    {
                        "id": "1",
                        "source": "adhoc",
                        "name": "community",
                        "value": "Community",
                        "isActive": true
                    },
                    {
                        "id": "8",
                        "source": "adhoc",
                        "name": "art-culture",
                        "value": "Art & Culture",
                        "isActive": true
                    },
                    {
                        "id": "13",
                        "source": "IRIS",
                        "name": "inclusion",
                        "value": "Inclusion",
                        "isActive": true
                    }
                ]
            },
            {
                "id": "6",
                "title": "Non-profit",
                "banner": "",
                "slug": "non-profit",
                "description": "",
                "categories": [
                    {
                        "id": "3",
                        "source": "adhoc",
                        "name": "non-profit",
                        "value": "Non-profit",
                        "isActive": true
                    },
                    {
                        "id": "26",
                        "source": "adhoc",
                        "name": "other",
                        "value": "Other",
                        "isActive": false
                    },
                    {
                        "id": "27",
                        "source": null,
                        "name": "the-giving-block",
                        "value": "The Giving Block",
                        "isActive": false
                    },
                    {
                        "id": "37",
                        "source": null,
                        "name": "change",
                        "value": "Change",
                        "isActive": false
                    }
                ]
            }
        ]
    }
}
`

**Comment by MoeNick** [comment]
This is the old json which should get mapped to the new suggested one. 
[Main and sub categories](https://drive.google.com/file/d/14oppcbYEPn3sORzqefpnGcNZETrCPiBM/view?usp=sharing)

**Comment by mohammadranjbarz** [comment]
> Hey @MoeNick @mohammadranjbarz , I added a new tab on the sheet here for mapping old categories with the new ones [called **Mapping old categories**](https://docs.google.com/spreadsheets/d/1DAB5UHCYO4hkw_RLRtz8DLXpGduVDRMHfiW-71H0m8o/edit#gid=122470553)
> 
> A few notes on this:
> 
> 1. I added category and subcategory ID's to make it easier to implement.
> 2. I think once this is implemented, we'll still need to go in and check them one by one (this could be maybe a week long project), just to make sure everything was assigned properly.
> 3. I added a catch-all category "Other". This will be for the ones that are not categorized (these of course would need to be cleaned up eventually by the community team).
> 4. For the Giving Block ones, I put them in the "NGO -> Registered Non-profit" category for now, but we may have to change them in the future if we want to better categorize them.
> 5. For Arts & Culture, we had the subcategories combined but I separated them. For now though, maybe put all of them under Art and we can clean them up at a later stage.
> 
> Let me know if you need any more support on this!

Thanks @ahmadabugosh  it's really organized now
@MoeNick I think I can start implementing that, am I right?

**Comment by mohammadranjbarz** [comment]
> Hey @MoeNick @mohammadranjbarz , I added a new tab on the sheet here for mapping old categories with the new ones [called **Mapping old categories**](https://docs.google.com/spreadsheets/d/1DAB5UHCYO4hkw_RLRtz8DLXpGduVDRMHfiW-71H0m8o/edit#gid=122470553)
> 
> A few notes on this:
> 
> 1. I added category and subcategory ID's to make it easier to implement.
> 2. I think once this is implemented, we'll still need to go in and check them one by one (this could be maybe a week long project), just to make sure everything was assigned properly.
> 3. I added a catch-all category "Other". This will be for the ones that are not categorized (these of course would need to be cleaned up eventually by the community team).
> 4. For the Giving Block ones, I put them in the "NGO -> Registered Non-profit" category for now, but we may have to change them in the future if we want to better categorize them.
> 5. For Arts & Culture, we had the subcategories combined but I separated them. For now though, maybe put all of them under Art and we can clean them up at a later stage.
> 
> Let me know if you need any more support on this!

**Change** is another third part like **Giving block** so I think it would be  `NGO -> Registered Non-profit` as well, @ahmadabugosh  do you agree?

**Comment by ahmadabugosh** [comment]
@mohammadranjbarz yes sure I would  put Change under that category NGO -> Registered Non-profit for now (and we can have the community team organize it more in the future)

**Comment by MoeNick** [comment]
@ahmadabugosh @maryjaf, please take a look and QA :)

**Comment by MoeNick** [comment]
@mohammadranjbarz if you agree I moved it back to code review, cause it needs front-end integration to be able to test properly

**Comment by maryjaf** [comment]
> @mohammadranjbarz if you agree I moved it back to code review, cause it needs front-end integration to be able to test properly

befor merge:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111529185/193741907-7daddfa6-d459-477f-a7ac-3c180807bb48.png">

after:
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/111529185/193741834-0971f6b8-1045-4718-9cbc-e5c8a0e704b2.png">
It seems that the project categories are not displayed correctly @mohammadranjbarz 
in order to have a more reliable test, the front changes should be merged and tested together. @MohammadPCh

**Comment by mohammadranjbarz** [comment]
> > @mohammadranjbarz if you agree I moved it back to code review, cause it needs front-end integration to be able to test properly
> 
> befor merge: ![image](https://user-images.githubusercontent.com/111529185/193742347-ea67ee1a-d688-4069-b6d6-a0e6955afadf.png) after: <img alt="image" width="1438" src="https://user-images.githubusercontent.com/111529185/193741834-0971f6b8-1045-4718-9cbc-e5c8a0e704b2.png"> It seems that the project categories are not displayed correctly @mohammadranjbarz in order to have a more reliable test, the front changes should be merged and tested together. @MohammadPCh

@maryjaf  I changed categories to what Ahmad said, then I made all other categories `isActive:false` then I didn't return non active categories in project info , so you can see them there, if you want to see them  you just make those categories active in admin panel then you will see them in project page

About testing with frontend it's ok, we can wait till that time, but I think they did most of the thing in another branch so they can merge it or you test on the preview of that branch, anyway I'm ok with postponing the tests

**Comment by maryjaf** [comment]
> @maryjaf I changed categories to what Ahmad said, then I made all other categories `isActive:false` then I didn't return non active categories in project info , so you can see them there, if you want to see them you just make those categories active in admin panel then you will see them in project page

Thanks @mohammadranjbarz I check it.

**Comment by maryjaf** [comment]
Based on the active subcategories in the admin panel
The display of project subcategories in the project detail section is correct.
Just one question, in the search category section, inactive categories are now displayed, is this correct? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> Based on the active subcategories in the admin panel The display of project subcategories in the project detail section is correct. Just one question, in the search category section, inactive categories are now displayed, is this correct? @mohammadranjbarz

No it's not correct, let me check it, I will update you

**Comment by maryjaf** [comment]
> > Based on the active subcategories in the admin panel The display of project subcategories in the project detail section is correct. Just one question, in the search category section, inactive categories are now displayed, is this correct? @mohammadranjbarz
> 
> No it's not correct, let me check it, I will update you

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/111529185/194105887-709cb8e5-b680-4ffb-919f-0475d0c717ff.png">
And in this page

**Comment by maryjaf** [comment]
> > > Based on the active subcategories in the admin panel The display of project subcategories in the project detail section is correct. Just one question, in the search category section, inactive categories are now displayed, is this correct? @mohammadranjbarz
> > 
> > 
> > No it's not correct, let me check it, I will update you
> 
> <img alt="image" width="1396" src="https://user-images.githubusercontent.com/111529185/194105887-709cb8e5-b680-4ffb-919f-0475d0c717ff.png">
> 
> And in this page

Do we have an update on this? @mohammadranjbarz
