### ISSUE TITLE
Giveth Data reporting and dashboard

### ISSUE THREAD

**Issue by spectoregia** [Giveth/GIVeconomy#729]
We initiated this discussion a while back in a smaller group so I'm creating this issue to have all the ideas, questions and problems related to this project in one place and follow up on the progress.

The issue, to sum up, is Giveth has plenty of dashboards and data sources but often times the data do not match from different dashboards, or they are not regularly updated or structured. 
From my side I would love to have data to present the following:

1) DAO and Treasury info
2) Donations info

---------
1) DAO and Treasury info: 

- Total treasury #
- Treasury Balances by Token (pie chart)
- GIV circulating supply per each liquidity pool #
- top 500 GIV hodlers (pie chart)
- GIV token hodlers split yearly/quarters (line chart)

*Optional (nice to have): would be awesome if we can get listed on https://deepdao.io/organizations and get our DAO KPIs added there as well. Metrics like: governance token holders #, active members #, proposals #, votes#

2) Donations info

- Total donation amount (split per month/year)
- Total # of donors (split per month/year)
- Total # of projects (split per month/year)
- Total donation by category - I recall this is particularly a problem since every project can get more than 2 categories assigned. During one call we agreed it's a good idea to ask project owners to pick 1 main category for their project going onwards; with the option to assign as many sub-categories they want. We need to also agree on the main category tags. What I used for the deck are as follows: Web 3.0, Art-Culture, Environment, Food, Health, Humanitarian, Inclusion, Agriculture, Education

**Comment by spectoregia** [comment]
I don't think I have assigning rights so I am tagging @mendesfabio and @GriffGreen

**Comment by mohammadranjbarz** [comment]
@spectoregia
About **Donations info** you want live data for that (I mean do you want somewhere to get that updated information whenever you want), or you need it one time ?

**Comment by clara-zi** [comment]
@clara-zi tagging myself to follow and learn and help where I can

**Comment by franculio** [comment]
@spectoregia I've been working on listing Giveth on [DeepDAO](https://deepdao.io/organizations). They have all of our treasury info and have uploaded it into our profile. 

There seems to be a problem on their end and the treasury data is not yet reflected on the graphics. I've messaging them regularly and they are working on it. I'll post an update here once we have those graphics up, in the meantime you can check the DeepDAO Giveth profile [here](https://deepdao.io/organization/a46c1c7d-2785-4b6d-b4a3-9e1b9ace2c3f/brainstorm).

**Comment by spectoregia** [comment]
thanks @franculio !
@mohammadranjbarz I can't recall whether we discussed it in the chat over the discord group but ideally a live version would be helpful. Or a data source that would at least pull the data 1-2 per month and update the dashboards

**Comment by RamRamez** [comment]
@spectoregia Please check this dashboard. It has:

Total donation amount (split per month/year)
Total # of donors (split per month/year)
Total # of projects (split per month/year)
Total donation by category

https://analytics-dashboard-blue.vercel.app/

I can change it as you wish and I can add different charts and plots.
@spectoregia If you have spare time, we can have a talk on Discord.

JFYI: @MoeNick @CarlosQ96

**Comment by RamRamez** [comment]
This dashboard reflects the staging data. @CarlosQ96 is preparing it to have a release on backend (just for these new four queries). After that, I can switch app to real data.

**Comment by MoeNick** [comment]
Thanks @RamRamez for providing this, the point is the data should be on a monthly basis.

**Comment by spectoregia** [comment]
thanks for this dashboard @RamRamez ! really helpful. happy to chat on discord anytime today or tomorrow. here's my handle: Yass#3392

one question regarding the dashboard (just to confirm if the data is correct). When I was going through the raw data on spreadsheets back in summer, the total # of (unique) donors that I managed to add up came to be around 4,168.
in this dashboard it shows 58. (time range selected: 2021-11-07 - to date)

**Comment by divine-comedian** [comment]
Let's break off the discussion for DAO treasury info in #817 

I also made many issues for different governance streams in the epic #809
