### ISSUE TITLE
Couldn't vote on Snapshot- Explanation doesn't mention GIVs

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#730]
Hey dev team, I went to try and vote on this snapshot proposal  below

https://snapshot.org/#/giv.eth/proposal/0x3d300579fe8ead589e31b4e6dc88a9381291db78b98dcf4776e777e9468e5c6e

and found out i wasn't able to.
![Screen Shot 2022-10-05 at 14.41.54.png](https://images.zenhubusercontent.com/62e67acf25afa784ea8ed4f1/eb752e3f-1c3a-44e9-9d07-7154d9a98728)

when i clicked on (i) info button it took me to this page:
https://github.com/snapshot-labs/snapshot/discussions/767

but nowhere does it mention I need GIVs to vote, so I think it would still be confusing to users how to vote.

It also fails to tell me how I can get GIVs and claim them, so I really feel like users would benefits by having this more clearly laid out. 

What do you thinK ?

**Comment by laurenluz** [comment]
This is snapshot's UI, not ours. If you felt like finding their github repo or discord & making a suggestion you could do it. but this isn't really someting our dev team can do.
