### ISSUE TITLE
Get our GIV token on all the token lists so it easily shows up on Uniswap and other DEXs

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#733]
So important!

**Comment by SnakeGH** [comment]
Updates from CoW swap: 

Master CoW - "Hey thanks for reaching out for the moment we aren't updating the cow token list as it's giving us some problems. That said, we are looking into making a new one which can have this feature."

So I will follow up with them in a month about the "new feature" @ahmadabugosh @GriffGreen

**Comment by spectoregia** [comment]
hey guys, I've been checking the process and I think most of the work is on our side. Here's what I've found so far:

According to Uniswap, anyone can create and maintain a token list, as long as they follow the specification. In short, we need to manually or automatically update a JSON blob that contains a list of ERC20 token metadata for use in dApp user interfaces. 
Here's a description how: https://github.com/Uniswap/token-lists

To manually author token lists an editor that supports JSON schema validation is needed.
For automated token listing, e.g. by pulling from a smart contract, we should use a npm package (also shared on the github link).

**Comment by ahmadabugosh** [comment]
@spectoregia @SnakeGH How about we make an "Impact DAO" or "Regen" token list? We can also make a nice marketing promotion out of it and include existing and potential partners (Gitcoin, Fox, TEC etc.).

**Comment by SnakeGH** [comment]
@ahmadabugosh I think that's a brilliant idea, why don't you start a google shared excel (since at this point, it will be more used than the CRM for tracking haha, even though Ill continue to put all my notes in Hubspot for my accounts) and we can add any token with updates on outreach. 

Plus I'm sure @Cotabe @divine-comedian @laurenluz @GriffGreen will also have some tokens to contribute for outreach

**Comment by spectoregia** [comment]
agreed. it's an excellent idea. 
regarding the technical aspect of this, who is the relevant person to talk to? is it @MoeNick ?

**Comment by MoeNick** [comment]
@aminlatifi I think this is for you.

**Comment by ahmadabugosh** [comment]
@chad-fi is this something you can take lead on (creating a Regen / Impact DAO token list we can submit to DEX's)?

**Comment by SnakeGH** [comment]
I'm also adding Kleros to this list and created a separate GH issue #1039

**Comment by SnakeGH** [comment]
After speaking with @GriffGreen today, I am going to look into these other swaps too

1inch, Dharma, Mycrypto, Uniswap labs default, Kyber and Zerion

**Comment by SnakeGH** [comment]
@spectoregia any new updates on Uniswap? because I was going to look into Uniswap labs default, unless you'd like to and keep both uniswap's under your belt

**Comment by SnakeGH** [comment]
Can someone help me turn this into an epic? When I try I get the error "something went wrong. please check your permissions" and so does @c0ric0ri 

Maybe @ahmadabugosh or @GriffGreen could try, as I believe one of you created the original issue?

**Comment by ahmadabugosh** [comment]
hey @SnakeGH can you also follow up on creating a Regen / Impact DAO token list ? It would be a nice marketing initiative

**Comment by SnakeGH** [comment]
My man @ahmadabugosh exactly why i need this to be an epic. Griff and I tailored a target list and i will be adding each one as an issue under this epic brother

**Comment by ahmadabugosh** [comment]
@SnakeGH awesome! I'm not an admin on this repo so unfortunately can't help with that. Maybe @laurenluz can help make this an epic?

**Comment by spectoregia** [comment]
Hey @SnakeGH yes! I need to get approval from Uniswap. Before submitting anything I need the following information about our toke. I asked the members on GIVeconomy chat but so far no response. Is any of you have any ideas please let me know:

Token Address: 
Token Name (from contract): 
Token Decimals (from contract): 
Token Symbol (from contract): 
Uniswap V2 Pair Address of Token:

**Comment by GriffGreen** [comment]
Token Address: 
0x900db999074d9277c5da2a43f252d74366230da0

Token Name (from contract):
Giveth

Token Decimals (from contract):
18

Token Symbol (from contract):
GIV

Uniswap V2 Pair Address of Token:
0xbeba1666c62c65e58770376de332891b09461eeb

But we migrated our liquidity to UniV3 so that pool is very small, UniV3 pools are here:
0x9e3f0082c321617c30662c53504be9d9e8b061d1
0xc763b6b3d0f75167db95daa6a0a0d75dd467c4e1

**Comment by SnakeGH** [comment]
@GriffGreen @ahmadabugosh @spectoregia since this issue is giving me so many problems and I am not able to change it into an epic, I have opened #1072 and added each token list we are interested in be present on as individual issues in that epic. Griff, please close this issue, #733
