### ISSUE TITLE
Optimism Grant Proposal

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#735]

**Comment by chad-fi** [comment]
If approved, likely allocated OP tokens (fairly valuable and liquid). Updates to be added in fundraising channel on Discord

**Comment by chad-fi** [comment]
Need to scope the effort - how much will this cost us?

**Comment by chad-fi** [comment]
Done & finalized - looking for committee members from OP to help review/push through. DevCon may serve as an offline chat for all parties.

**Comment by chad-fi** [comment]
From Discord Chat: Direct investment in Giveth doesn't seem like the most likely scenario. But the possibility of making public goods focused economies could have legs if we partner with the Commons Stack and work with their DAOs... either way we will learn a lot more by talking with them at Devcon.

**Comment by chad-fi** [comment]
Griff/Yass working on edit of proposal, then gets posted for review from Tooling group, negotiations to follow.

$300k in OP tokens - liq pool on Optimism for GIV - add OP to option for donations, ie. GIVbacks on OP.

**Comment by GriffGreen** [comment]
Proposal is up: 

https://gov.optimism.io/t/draft-gf-phase-1-proposal-giveth-cycle-8/3735
