### ISSUE TITLE
Radicle Grant

### ISSUE THREAD

**Issue by chad-fi** [Giveth/GIVeconomy#736]
Updates for Radicle Grant to be added here

**Comment by chad-fi** [comment]
Yass working on model with Mitch. Fees, GIV supply in circ., market share of crypto donations, etc. being distributed.

**Comment by chad-fi** [comment]
Giveth Devs working on roadmap synergy with this, Yass in talks with Moenick. Proposal to follow.

**Comment by laurenluz** [comment]
@chad-fi @spectoregia what is this about?? I'm being looped in on the radical partnership issue from comms and am totally confused... are we asking for a grant as well? a token swap?

**Comment by spectoregia** [comment]
hey @laurenluz - yes, Mitch brought to my attention that Radicle is also issuing grants. So for this integration, we are trying to put together a grant proposal so the cost is covered by them. 
https://github.com/radicle-dev/radicle-grants/blob/main/grants/applications/template.md

**Comment by laurenluz** [comment]
I'm not sure that the Radicle is going to give us a grant just to use drips on our dApp... usually they would give grants for something that would give drips extra utility outside of this one use case. How are you planning to frame the proposal?

**Comment by laurenluz** [comment]
@spectoregia as discussed in today's call - having this grant pass is a critical first step if we wish to perform this integration.

The main benefits for radicle, which we should explain are:
- new use case for drips to directly support nonprofits
- use in combination with GIVbacks means that donors who use drips will get GIV for doing so (basically we'll be subsidizing people to use drips)

If we can't do it on gnosis chain, we could do it on mainnet - open to discussion... maybe you can talk w/ your contact from them - or add me to a group DM w/ them?

Also! If they are not willing to give us RAD simply for this work, we are happy to use the RAD for this grant for a GIV/RAD liquidity pool (i.e. we wouldn't sell it, we'd use it for liquidity on mainnet).

Once we've got the proposal sorted, please post a draft here and I can take a look. Our comms-related partnership is pretty contigent on this passing so let's get this done as soon as we can.

**Comment by chad-fi** [comment]
Step 1: Grant proposal, who owns this?
Step 2: How will Drips integration get done

**Comment by laurenluz** [comment]
@spectoregia - can you post the proposal in here?

**Comment by laurenluz** [comment]
nevermind, I found it. https://radicle.community/t/grant-application-giveth/3102

**Comment by Cotabe** [comment]
More info was required by the Radicle team.

Yass fulfill this info on 11/08/22

**Comment by spectoregia** [comment]
update from Radicle:
the plan is still to use grants 2.0, but this will only happen in march so the plan is to fund things retroactively. The retroactive funding amount will be defined through quadratic voting. So I wouldn't know how much would that be. 

The Wonderverse team is taking this path because they want/need to integrate with drips. If this is the case for you guys as well, retroactive funding could be a good option, or you can wait till we start using grants 2.0.
