### ISSUE TITLE
Handling GIVpower for projects that lose their verified status & unverified projects

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#739]
I should ONLY be able to boost veriied projects.

This project is rank Giveth/GIVeconomy#3... but it says it is not verified:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/5b9c2e4a-9ce0-4646-a4d9-d4b3a459df50)

I am the owner, so the project page looks like this:

![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/0ebd631b-4d03-45b3-bd0b-3b3624b0a412)

**Comment by aminlatifi** [comment]
@laurenluz It seems this condition was not asked at the beginning. We can do it, mostly a frontend job @MohammadPCh @alireza-sharifpour.

Just a question! Is it possible a verified project become unverified in the future? what will happen to its ranking then?

**Comment by laurenluz** [comment]
@WhyldWanderer would love your input on this...

Projects who were verified and had GIVpower on them could at some point become unverified.
In this case, I think we should make it so that, when the project becomes unverified, the user's GIVpower on that project becomes 0 and it is redistributed to proportionally to their other projects.

We should also, at this point, send an email to the people boosting the now unverified project, letting them know.

Do you think this is acceptable?

**Comment by WhyldWanderer** [comment]
I think it is acceptable!

I think it will be hard to send emails to the people boosting... 
do users need to create a profile in order to boost or can you boost anonymously?

**Comment by laurenluz** [comment]
you can boost anonymously 😕 

@aminlatifi @MoeNick do you think we should make some prompts to encourage the user to fill out their profile during boosting? I think it would be a nice addition... I can create a new issue and it can be a fast-follow

**Comment by WhyldWanderer** [comment]
I like being able to boost anonymously..

And maybe if we communicate what happens when a project becomes 'unverified' *ie. their GIVpower will be dispersed proportionally across their other chosen projects) maybe we dont need an email to go out every time it happens.. theres isnt really a call to action at that point.

**Comment by laurenluz** [comment]
ok deal, we can just put that explanation in the docs.

@aminlatifi - can you make it so that you can only boost verified projects, and if a project loses their verification status, any GIVpower that was on that project gets distributed to their other boosted projects (i.e. it's as if they choose to boost that project with 0%).

An edge case: if the user was using 100% of their GIVpower on the project that becomes unverified, their GIVpower should then go back to them... as if they have not used it yet.. and the very *next* project they boost is as if it were their first project (i.e. it gets 100%).

does that make sense?

**Comment by aminlatifi** [comment]
> ok deal, we can just put that explanation in the docs.
> 
> @aminlatifi - can you make it so that you can only boost verified projects, and if a project loses their verification status, any GIVpower that was on that project gets distributed to their other boosted projects (i.e. it's as if they choose to boost that project with 0%).
> 
> An edge case: if the user was using 100% of their GIVpower on the project that becomes unverified, their GIVpower should then go back to them... as if they have not used it yet.. and the very _next_ project they boost is as if it were their first project (i.e. it gets 100%).
> 
> does that make sense?

We must implement the logic both in the frontend and the backend.

**Comment by aminlatifi** [comment]
> > ok deal, we can just put that explanation in the docs.
> > @aminlatifi - can you make it so that you can only boost verified projects, and if a project loses their verification status, any GIVpower that was on that project gets distributed to their other boosted projects (i.e. it's as if they choose to boost that project with 0%).
> > An edge case: if the user was using 100% of their GIVpower on the project that becomes unverified, their GIVpower should then go back to them... as if they have not used it yet.. and the very _next_ project they boost is as if it were their first project (i.e. it gets 100%).
> > does that make sense?
> 
> We must implement the logic both in the frontend and the backend.

@MohammadPCh says the feature is implemented in the front-end. In the backend we have to add conditions to set API and also a corn job to find boosted unverified projects and make their boosting zero.

**Comment by MoeNick** [comment]
1- Can be as a cronjob? when? 
2- find all users's boosted this project
3- allocate the givpower proportionally to other boosted projects.

**Comment by laurenluz** [comment]
As per GIVeconomy dev call, we have decided not to remove the givpower from an project that becomes unverified... instead it becomes "dead GIVpower"... we need to add something to the frontend for this.

updates following the call

**Comment by laurenluz** [comment]
This issue is now pending design in #751 - we will keep the GIVpower unused on the newly verified project & show the user that their GIVpower is not useful in "My account".

@aminlatifi can you verify from the backend perspective that this will be easy to implement?

**Comment by aminlatifi** [comment]
> This issue is now pending design in #751 - we will keep the GIVpower unused on the newly verified project & show the user that their GIVpower is not useful in "My account".
> 
> @aminlatifi can you verify from the backend perspective that this will be easy to implement?

@laurenluz You mean the newly unverified project, right? I have implemented that in the backend (unverified project power is zero even if it's boosted). The frontend thing also looks straight forward, am I right @MohammadPCh @alireza-sharifpour

**Comment by laurenluz** [comment]
Hey @aminlatifi I think there was a bit of confusion. Based on our conversation in the last GIVeconomy dev call, we decided that it is better not to remove the GIVpower from an unverified project... although we *do* remove their ranking.
- Newly unverified project keeps all GIVpower, but it does not show on the project page
- The unverified project has no rank, so visible GIVpower page, no verification label
- The ranks of all projects below this "unverified project" increase by one to replace the newly unverified project.
- Any user who boosted the newly unverified project will see in "my account" that their GIVpower is being wasted (#751)

@aminlatifi is this congruent with our backend right now?

**Comment by aminlatifi** [comment]
> Hey @aminlatifi I think there was a bit of confusion. Based on our conversation in the last GIVeconomy dev call, we decided that it is better not to remove the GIVpower from an unverified project... although we _do_ remove their ranking.
> 
> * Newly unverified project keeps all GIVpower, but it does not show on the project page
> * The unverified project has no rank, so has no GIVpower tab, no verification label, no boost button
> * The ranks of all projects below this "unverified project" increase by one to replace the newly unverified project.
> * Any user who boosted the newly unverified project will see in "my account" that their GIVpower is being wasted ([GIVpower Boosting | Design upgrade for when a project loses its verified status #751](https://github.com/Giveth/GIVeconomy/issues/751))
> 
> @aminlatifi is this congruent with our backend right now? We decided this to ultimately make it easy for us to "re-verify" the project, and have the project _not_ have lost it's GIVpower from before.

Yes, it's what we aim for and the backend is changed to achieve this result. Technically, the givpower amount of an unverified project is zero regardless of how much users delegate to it. So it will not occupy a position in the ranking (they have the lowest value which is hidden, so should be at the bottom of the list)

**Comment by laurenluz** [comment]
perfect!
