### ISSUE TITLE
rGIV: Test all functionality on xDai

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#74]
After we test that the rGIV can manage its own treasury (i.e. do all the things on Rinkeby), we need to deploy on xDai and test it all there before launch.

Related to #70 #71 #72

**Comment by laurenluz** [comment]
@divine-comedian to work on deploying this TEST DAO on xdai today... it's a reputation DAO, needs 2 agents (one needs to be added w crisper), needs all execute roles... use whatever version 1hive lets you create. shouldn't be able to mint tokens (just to voting app can mint tokens)

Griff has the spreadsheet with all addresses & tokens... so we can give the right amout tokens to each person

Make vote duration 12 hours
Make quorum small as well

**Comment by laurenluz** [comment]
Need to test:
- changing addresses of recipients
- allocating GIVbacks

**Comment by divine-comedian** [comment]
successfully changed recipient address of GIVdrop using the aragon agent and the MerkleDistro deployment on xdai - 

you can see the vote transaction and more details here - 

https://dashboard.tenderly.co/tx/xdai/0x7c28eda1203c1b4138da0ce306e8b49f2730f3dd2bb450b84e5a3dcdf8256285/contracts

**Comment by laurenluz** [comment]
NICE!

**Comment by divine-comedian** [comment]
@paxthemax this is the relevant issue here

Trying to use cancelAllocation within the TokenDistro contract using an Aragon Agent - 
I used https://evm-crispr.blossom.software/ to create the evm script to be executed by the agent (the agent is the owner/should be the admin of the tokenDistro proxy) 

normally this function should change the GIVbacks allocation from one address to another 

I receive an error while trying to execute the successfully passed vote on aragon to call this function via agent 

https://blockscout.com/xdai/mainnet/tx/0x9b4557171bedf3328b0ec3d85036617768aeea9cffa305573773b0266fc820ec

this is the proxy address for the tokenDistro 

https://blockscout.com/xdai/mainnet/address/0xf11aC05c97F8845f6b974e9e327129d36683cC90/contracts

any idea why this is failing?

**Comment by laurenluz** [comment]
Motch: how can we generate the script of who gets GIVbacks? 
Mohammad: we have a script for calculating the GIVbacks, not calling the smart contract
Motch: to distribute, we need an array of addresses & matching amoubts
Mohammad can change the output to a written response

@divine-comedian to send syntac to @MohammadPCh to figure this out

Successful tests for:
- [x] changing addresses of GIVdrop recipients
- [x] sending GIVbacks
- [ ] Make sure money is actually sent to our second agent and we can use it to pay salaries - allocate GIV tokens to a second agent & vote to pay out liquid tokens... this should be done at deployment by Amin.. we need to make sure we can actually spend money out of that agent

Allocate function assigns a stream.
SendGIVbacks function should be called by a distributor
AllocateMany function is a different function...

**Comment by divine-comedian** [comment]
successfully tested sending GIV from tokenDistro to second agent via first agent (distributor)

https://blockscout.com/xdai/mainnet/tx/0x9f1d3d320354a673053d270a9b06953f7aceb55dbb0e04fb15f7c9b5e6e1ee78

**Comment by divine-comedian** [comment]
> Motch: how can we generate the script of who gets GIVbacks? Mohammad: we have a script for calculating the GIVbacks, not calling the smart contract Motch: to distribute, we need an array of addresses & matching amoubts Mohammad can change the output to a written response
> 
> @divine-comedian to send syntac to @MohammadPCh to figure this out

I think she meant @mohammadranjbarz FYI

**Comment by mohammadranjbarz** [comment]
> Motch: how can we generate the script of who gets GIVbacks? Mohammad: we have a script for calculating the GIVbacks, not calling the smart contract Motch: to distribute, we need an array of addresses & matching amoubts Mohammad can change the output to a written response
> 
> @divine-comedian to send syntac to @MohammadPCh to figure this out
> 
> Successful tests for:
> 
> * [x]  changing addresses of GIVdrop recipients
> * [x]  sending GIVbacks
> * [ ]  Make sure money is actually sent to our second agent and we can use it to pay salaries - allocate GIV tokens to a second agent & vote to pay out liquid tokens... this should be done at deployment by Amin.. we need to make sure we can actually spend money out of that agent
> 
> Allocate function assigns a stream. SendGIVbacks function should be called by a distributor AllocateMany function is a different function...

Idont know about how sending givbacks, but with https://givback.develop.giveth.io/api-docs/#/default/get_calculate_givback
we calculate how much givback we should pay

**Comment by divine-comedian** [comment]
Nice! I see I can retrieve the script directly from the function -
