### ISSUE TITLE
Research Capital Deployment Strategies on Gnosis Chain

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#742]
Investigating opportunities for capital deployment on gnosis chain

Agave is still up and running, allowing to earn an APR on some stables and assets such as WBTC and WETH
https://app.agave.finance/#/markets

could be worth some time to write a script or "strategy contract" that could add some leveraging to stable deposits and also a function that would automatically cash out agave rewards if we so choose. 

I am reaching out to see the status of AGAVE, if it's being actively developed or seems like an abandoned project..

---

swapr has some farming programs as well - looks like they have finite durations which may make them difficult to manage
https://swapr.eth.limo/#/rewards?chainId=100

---

Autofarm has also been around for a while and has a few farms on gnosis chain - some interesting stable farms too
https://autofarm.network/vaults/

---

curve is also deployed on xdai and has some pools for GNO and stables - would need an autocompounding contract
https://xdai.curve.fi/

**Comment by divine-comedian** [comment]
Autofarm has also been around for a while and has a few farms on gnosis chain - some interesting stable farms too
https://autofarm.network/vaults/

**Comment by divine-comedian** [comment]
also check out ethichub yields

**Comment by oyealmond** [comment]
can we close this @divine-comedian?
