### ISSUE TITLE
Research Capital Deployment Strategies on Mainnet

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#743]
@GriffGreen maybe you want to loop Kirch into this one?

**Comment by divine-comedian** [comment]
- ethic hub
- yearn.finance
- badgerDAO
- element.finance
- balancer managed pools
  - allows a basket of assets and can assigner a manager to set algorithmic rules for controller to implement changes
- aura boosted balancer pools
- ENS has lots of money, has so much ETH flowing in, looking for treasury management group - watching those offers
- orangeDAO could treasury management 

scoopytrooples - alchemix - could reach out to him 

defisafety

**Comment by Cotabe** [comment]
Also:

https://app.goldfinch.finance/earn

**Comment by oyealmond** [comment]
Can we close this @divine-comedian ?
