### ISSUE TITLE
Notification Center | Design to notify a user when the project they are boosting becomes unverified

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#749]
Related to #739 - it would be nice to let the user know that their GIVpower is going to waste.

Maybe we should include this in the notification centre

**Comment by laurenluz** [comment]
We have changed strategy via #739 

now the user's GIVpower will not be taken-off... but they should be notifiied when a boosted project becomes unverified... @MoeNick please keep this in mind for noticiation centre.

**Comment by mohammadranjbarz** [comment]
> I can't test scenarios about boostin on this branch (https://notification-center-13.vercel.app/) @mohammadranjbarz
@maryjaf 

You should boost a project  on giveEconomy branch, then unverify it by admin bro, then you will see the notification in https://notification-center-13.vercel.app ( because becakcend of givEconomy and this branch are the same)

**Comment by maryjaf** [comment]
I tested again
**verification form page in admin bro:**
changed verification form  status from submitted into rejected 
notif:ok
email: ok
changed verification form  status from verified into rejected : impossible
------
**project edit page  in admin bro:**
changed verify  status from verified into unverified 
notif:ok
email: ok

**project list  in admin bro:**
changed verify  status from verified into unverified 
email: not ok
notif:ok
 @mohammadranjbarz @MoeNick

**Comment by mohammadranjbarz** [comment]
> I tested again
> 
> **verification form page in admin bro:**
> 
> changed verification form status from submitted into rejected notif:ok email: ok changed verification form status from verified into rejected : impossible **project edit page in admin bro:** changed verify status from verified into unverified notif:ok email: ok
> 
> **project list in admin bro:** changed verify status from verified into unverified email: not ok notif:ok @mohammadranjbarz @MoeNick

@maryjaf 
 I can't understand why you have tested the email, the issue just says creating notification not sending emails, and in all 3 items that are related to creating notifications you have written ok, so you mean we are cool?

**Comment by maryjaf** [comment]
> **project list in admin bro:**
> changed verify status from verified into unverified
> email: not ok
> notif:ok

project list in admin bro:
changed verify status from verified into unverified
email: not ok
notif:ok

when I unverify a verified project from list I didn't receive email but from project verification form(submitted-->unverified) and edit page (verified-->unverified) the email is sent

**Comment by mohammadranjbarz** [comment]
> > **project list in admin bro:**
> > changed verify status from verified into unverified
> > email: not ok
> > notif:ok
> 
> project list in admin bro: changed verify status from verified into unverified email: not ok notif:ok
> 
> when I unverify a verified project from list I didn't receive email but from project verification form(submitted-->unverified) and edit page (verified-->unverified) the email is sent

I mean we should not send email for those users who boosted project, neither when unverifying from edit page nor from list
We would have a call tomorrow for talking about this

**Comment by maryjaf** [comment]
I think these are the remaining items from notification center @aminlatifi @mohammadranjbarz 
1- I don't receive notifications when I  change the boost of projects or someone boost my project
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/111529185/209633089-4a71305e-8b90-438c-b256-338fee8fa55c.png">

2- The same for Giveback and Reward
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/111529185/209633499-d9bb285c-cebb-4181-9009-099d2a0a9128.png">


3- It was decided not to send a notification to Lock and it is necessary to change its text @MoeNick 
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/111529185/209633089-4a71305e-8b90-438c-b256-338fee8fa55c.png">
