### ISSUE TITLE
Choose params for the GIVgarden

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#76]
The Giveth technocracy shall choose params for conviction voting and tao voting to use in the GIVgarden. We'll use the CCD from the TEC!

This is what Bright DAO chose: https://docs.google.com/document/d/1vmLLEPe0ApDklJxSOBwgC3uYrviYcJaYnSWszzvtVFA/edit#heading=h.bs786n2d9y7w

FYI - Bright DAO stuck with most of the suggest params from 1hive. We will tweak them mostly likely, especially things like quorum.

**Comment by divine-comedian** [comment]
let's schedule an in person hack and we can slam these out!

**Comment by laurenluz** [comment]
Is it possible to click "harvest" in gardens UI and end up at the popup? We can send them to the GIVgarden page!

**Comment by laurenluz** [comment]
New params have been chose - in the forum for advice process: https://forum.giveth.io/t/givgarden-parameters/152/7

Closing this friday if there's not major feedback
