### ISSUE TITLE
The Graph

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#767]
The Graph Foundation 
https://www.notion.so/The-Graph-Foundation-e822e66d7b614fdd899a647f5db51a68

Accepting applications for wave VI
Apply here: https://thegraph.typeform.com/applynow

12/26
Status
    - Confirmed, just need to fill KYC and a form.
    - 50K GRT (3K USD)
Blockers:
    - KYC - Cotabe can do it
    - form - Griff/Yass review
Updates
    - Very close to the finish line.
Next steps
    - Griff will review if Yass isn’t around.

**Comment by Cotabe** [comment]
Updates:
- Form submited.
- KYC failed, will get support on the week.

**Comment by Cotabe** [comment]
Updates:
- KYC ready

They sent me the docusign. I reviewed it and I want to go through a few things.

Would be great to have someone with legal background go through it again.
