### ISSUE TITLE
Moonbeam

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#768]
https://moonbeam.foundation/grants/

Level 1: Expedited Grants
Amount: up to $50k
Approval Process: 2 of 5 Community Grants Committee members, with at least one Moonbeam Foundation Committee Grants Committee member approval
Fund Distribution: USD or USDC

Level 2: Larger Grants
Amount: $50k to $150k
Approval Process: 3 of 5 Community Grants Committee members, with at least one Moonbeam Foundation Committee Grants Committee member approval
Fund Distribution: USD, USDC, or GLMR

Level 3: Ecosystem Grants
Amount: $150k to $3 million
Approval Process: Community Grants Committee approval AND community voting approval
Fund Distribution: USD, USDC, or GLMR

Projects applying for grants will have a greater chance of success if they can demonstrate:

Well-researched and tested ideas with examples of prior work
Ideas differentiated from competitors or ideas that implement technology that does not yet exist in the ecosystem
A team with strong technical background and experience in the project’s concept and the ability to deliver on set milestones
A team that demonstrates an ability to maintain and grow the project
A high-quality application with clear milestones and details
A reasonable grant amount request
Responsiveness throughout the application and diligence process
Commitment to the Moonbeam ecosystem, ideally through demonstrated collaboration efforts
Use of a connected contracts implementation approach
Alignment with Moonbeam Guiding Principles and Moonbeam’s Code of Conduct

**Comment by spectoregia** [comment]
**first response:**
thank you guys for taking the time to speak to us. The grants committee reviewed your application - given current market conditions the foundation has cut back significantly on grants, so unfortunately they wont be able to support with one right now. We can definitely revisit that discussion further on once circumstances change.

Regardless, the consensus internally is that Giveth is still a cool project so in the meantime we want to support your team as much as possible when it comes to technical matters, marketing and ecosystem development support.

Alberto the head of devrel is already in this group in case you need to troubleshoot something or have technical questions about moonbeam.

In terms of marketing, we're also open to support with an announcement and other initiatives in case you decide to deploy to moonbeam.

We’re also glad to help your team as much as possible in terms of BD and ecosystem development in general when it comes to making connections with other teams so you can get plugged into the ecosystem.

**our counter:**
We appreciate you taking time to review our application. I certainly hope 2023 will have a more positive outlook on the crypto market with more funds available for our projects to grow and scale even faster. 

I would like to ask if there is a chance to revise some of the elements of our request. For us the bigger component of this grant is the incentivization of projects onboarding to Moonbeam which is already a part of our grant proposal.

On top of that, a more valuable element would be to create an LP against GIV to allow GIV to have a secondary market on Moonbeam. We’d need to create a sizable LP with Moonbeam for this. Therefore we are happy to reduce the amount requested for development work to 40% of the original amount and instead focus on creating an LP with $300K USD worth of GLMR against GIV. This would allow people who get GIV tokens to turn them into GLMR if they want to (which would create an upward price action on Moonbeam).
This  GLMR will not be sold, it will simply be held in a multisig for perpetuity.

The 2 components above would be a big support to kickstart the donation culture on Moonbeam and effectively incentivize the process on this chain.

 If this is something that could be acceptable to the community, I'd love to also invite Griff and perhaps have a call with him and discuss this in more detail.

**final response:**
tbh the foundation has received many requests like this to provide liquidity towards a given pool - they prefer to not act as liquidity providers on the network so they are quite limited in terms of the support they can provide in that regard.

I suppose we can consider it as closed...
