### ISSUE TITLE
Polkadot

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#769]
https://wiki.polkadot.network/docs/grants

**Comment by brichis** [comment]
https://docs.google.com/document/d/1IZykdp2cyQavcRyZd_dgNj5DcgxgZR6kAqGdcNARu1w/edit

Are you interested in submitting a treasury proposal to the Polkadot council to fund your project?

Proposals may consist of (but not limited to):
Infrastructure deployment and continued operation;
Network security operations (monitoring services, continuous auditing);
Ecosystem provisions (collaborations with friendly chains);
Marketing activities (advertising, paid features, collaborations);
Community events and outreach (meetups, hackerspaces);
**Software development (wallets and wallet integration, clients and client upgrades).**
**Cross-chain application development**

**Comment by brichis** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScooHpV-WlB7nxu59IXvZnyN2uprleZgpcQPyUxe-nPEnrVNw/viewform

**Comment by brichis** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScooHpV-WlB7nxu59IXvZnyN2uprleZgpcQPyUxe-nPEnrVNw/viewform

**Comment by brichis** [comment]
Griff coment

**Comment by brichis** [comment]
Griff commented will be really difficult to get the Whitelabel idea with Polkadot because of the differences in technologies used
