### ISSUE TITLE
Kava

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#773]
kava website: https://www.kava.io/

https://medium.com/kava-labs/kava-grants-ac458a4c1808

Apply here: https://docs.google.com/forms/d/e/1FAIpQLSeRqFXFftslD0a9Pn5HoKhySh8qOfSjcb6VuEuuHOUug-eMWw/viewform

**Comment by oyealmond** [comment]
hey @Cotabe! 
¿podrías ayudarme a revisar si alguno de estos issues tiene sentido aún? Y si no, ¿podrías cerrarlos por fi?

**Comment by Cotabe** [comment]
Not sure if this could still be a lead, but I'm transcribing it to another doc & closing the issue.

**Comment by Cotabe** [comment]
Here is the doc: https://docs.google.com/document/d/1nL475Jlwb2w5VtGsB_ha4xtSgBr8xZjChaDM0WZaBHk/edit?usp=sharing
