### ISSUE TITLE
Fuze

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#775]
https://docs.fuse.io/aboutFuse/about-fuse/things-you-can-do-on-fuse/grants-and-bounties

Apply here: https://form.typeform.com/to/OfCHzmOY?utm_source=xxxxx&utm_medium=xxxxx&utm_campaign=xxxxx&utm_term=xxxxx&utm_content=xxxxx&typeform-source=hbfigtycii9.typeform.com

**Comment by SnakeGH** [comment]
@tropicalmangos and super weird, I'm logged in but not able to assignee myself to this one. Could you do it for me please and I will start the process on it :)

**Comment by SnakeGH** [comment]
- The Fuse Future Dev Pool is especially interested in new high-potential payment centric communities, DAO initiatives, applications for new crypto users, NFTs, DeFi apps, projects that support current projects, and new categories we haven't even thought of yet
- Although the grant process is not set in stone, the way it currently functions is that we announce bounties on an ongoing basis based on the project category
- Grants are paid in FUSE tokens and max seems to be $10,000

Not sure if this the same Grant or a different one with FUSE but…

- Fuse Builder Grants Program: Build an NFT App on Fuse Network from June 2021
- To qualify for a grant, an application has to focus on NFTs. You can port existing NFT-related Solidity smart contracts from an EVM-based chain or create a brand new NFT-related Solidity smart contract to be launched on Fuse Network.
- Potential use cases may include: An NFT minting app. An NFT-focused web app or mobile app. A decentralized NFT auction system, or a game with NFT collectibles or NFT assets, such as virtual real estate. Financial NFT applications such as financial bonds.
- Grant amount - Proposals are eligible to receive either $10,000, $5,000, or $2,500 in FUSE tokens

Opinions.

- Let’s keep the asks for larger grants for now. Maybe min 50,000 K
- NFTs outside of Ethereum doesn’t seem to be reap.
