### ISSUE TITLE
Gnosis Ecosystem Fund -> Gnosis DAO

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#778]
Gnosis Ecosystem Fund - discontinued but can now apply through Gnosis DAO 
https://github.com/gnosis/GECO
https://forum.gnosis.io/t/readme-gnosisdao-governance-process/736/3

Medium: https://blog.gnosis.pm/unveiling-the-gnosis-ecosystem-fund-7353926bfb65
Proposal submission template: https://github.com/gnosis/GECO/blob/master/Proposals/ProposalTemplate.md

https://docs.ethhub.io/other/funds/geco/

https://www.cypherhunter.com/en/p/gnosis-ecosystem-fund/

**Comment by spectoregia** [comment]
the idea for the grant with Gnosis would be to offer a whitelabeled Giveth DApp to Gnosis to create their charity arm.
The proposal can be found here: https://docs.google.com/document/d/1q93bnl8uKLf5BOEsTh1-YGOhC9qttvgcc33N7n-4vIU/edit
Awaiting feedback from the @MoeNick and @WhyldWanderer on the development and maintenance estimation before submitting it on their forum. 

Also, if anyone has any contacts in Gnosis with whom we can review the proposal please get us in touch! :) I tried reaching out to Reiner but he seems to be offline for a while.

**Comment by spectoregia** [comment]
also adding @GriffGreen here who is proofreading the overall proposal
