### ISSUE TITLE
ETH Project Grants

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#780]
A Project Grant might be a good fit if any of the following apply to your project:

More complex, or larger in scope: the proposed work has multiple components or stages, a longer project timeline, or will require you to make new long-term hires.
Higher-cost: your expected budget exceeds $30,000.
A mature idea: you have thought deeply about your goals and strategy, asked yourself difficult questions to validate your approach, and thoroughly researched the state of the art in your chosen domain.

https://esp.ethereum.foundation/applicants/project-grants

**Comment by oyealmond** [comment]
hey @Cotabe! 
¿podrías ayudarme a revisar si alguno de estos issues tiene sentido aún? Y si no, ¿podrías cerrarlos por fi?

**Comment by Cotabe** [comment]
This is currently being pursued & tracked on the Grants Tracker Master doc. I'm closing this issue.
