### ISSUE TITLE
ETH Community Fund

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#781]
About: https://ecf.network/

Apply: https://ecfnetwork.typeform.com/to/nSA6Id?typeform-source=docs.ethhub.io

**Comment by oyealmond** [comment]
hey @Cotabe! 
¿podrías ayudarme a revisar si alguno de estos issues tiene sentido aún? Y si no, ¿podrías cerrarlos por fi?

**Comment by Cotabe** [comment]
Currently being pursued. This is being tracked on the Grants Tracker Master doc. I'm closing the issue.
