### ISSUE TITLE
Tachyon (Consensys)

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#782]
Tachyon is an accelerator for early-stage startups utilizing blockchain and Web 3.0 technologies. 
Part of the @ConsenSysMesh https://twitter.com/ConsenSysMesh
Community: http://bit.ly/3x7WtH7](https://t.co/FUGGMYxtK9

Tachyon Accelerator: https://tachyon.xyz/accelerator/

Website: https://tachyon.xyz/

Application form: https://airtable.com/shrpjixUESt0ZZJ34

**Comment by oyealmond** [comment]
hey @Cotabe! 
¿podrías ayudarme a revisar si alguno de estos issues tiene sentido aún? Y si no, ¿podrías cerrarlos por fi?

**Comment by Cotabe** [comment]
Not sure if this could still be a lead, but I'm transcribing it do another doc & closing the issue.
