### ISSUE TITLE
Waves Grant

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#785]
https://camp.waveslabs.com/#why-waves

Apply here: https://share-eu1.hsforms.com/1zu7mgxQFSlm5LGikvK40HAfhup6

**Comment by oyealmond** [comment]
hey @Cotabe! 
¿podrías ayudarme a revisar si alguno de estos issues tiene sentido aún? Y si no, ¿podrías cerrarlos por fi?

**Comment by Cotabe** [comment]
Not sure if this could still be a lead, but I'm transcribing it do another doc & closing the issue.
