### ISSUE TITLE
Web 3 Foundation Grant

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#786]
https://web3.foundation/grants/

Apply here: https://github.com/w3f/Grants-Program#web3-foundation-grants-program

**Comment by brichis** [comment]
Software Development
Web3 Foundation funds development work driving advancement and adoption of decentralized software protocols. We support projects that make it easier for developers to build useful applications using these protocols.

We are particularly interested in funding projects that build out layers of the Polkadot Stack.

**Comment by brichis** [comment]
Grants recipients: 

- Quadratic Funding Pallet - https://dorahacks.com/

**Comment by brichis** [comment]
Yass Feedback:
well, the web3 foundation has also this 3rd level. maybe we can apply the funds to develop GIVfi and other upcoming projects and also do the VC calls from their intro!
we could split it in 2, so sell the whitelabel idea to Polkadot and apply for the 3rd lvl grant/funding with the foundation

**Comment by brichis** [comment]
Application:
Please read our FAQs, category guidelines, announcement guidelines and Terms & Conditions to familiarize yourself with the subtleties of grants, applications and the program as a whole.
Fork this repository.
In the newly created fork, create a copy of the application template (applications/application-template.md). If you're using the GitHub web interface, you will need to create a new file and copy the contents of the template inside the new one. Make sure you do not modify the template file directly. In the case of a maintenance application, use the maintenance template (maintenance template) instead. In the case of a research application, use the research template (research template) instead.
Name the new file after your project: project_name.md.
Fill out the template with the details of your project. The more information you provide, the faster the review. Please refer to our Grant guidelines for most popular grant categories and make sure your deliverables present a similar same level of detail. To get an idea of what a strong application looks like, you can have a look at the following examples: 1, 2, 3, 4. Naturally, if you're only applying for a smaller grant that only consists of, say, UI work, you don't need to provide as much detail.
Once you're done, create a pull request. The pull request should only contain one new file—the Markdown file you created from the template.
You will see a comment template that contains a checklist. You can leave it as is and tick the checkboxes once the pull request has been created. Please read through these items and check all of them.
Sign off on the terms and conditions presented by the CLA assistant bot as a Contributor License Agreement. You might need to reload the pull request to see its comment.

**Comment by brichis** [comment]
We have a strong technical project that adds value to the ecosystem ✅ 
Can we demonstrate that the project will be maintained after completion of the grant (additional funding sources or an existing business model) ❔ 
Our team has proven experience with the relevant languages and technologies and/or a strong technical background ✅ 
All our code produced as part of a grant will be open-sourced ✅ 
Our application is not about a specific token ❔ 
Software development and research activities ✅ 
We never had a token sale ✅ 
GIVfy is a project "driving advancement and adoption of decentralized software protocols [and] that make it easier for developers to build useful applications using these protocols."? ❔ 
Are we an individual company developing our private infrastructure? ❔

**Comment by brichis** [comment]
Search projects similar to Giveth

**Comment by brichis** [comment]
Tip or Donate KSM Embeddable Button - Shard Labs https://github.com/w3f/Grants-Program/blob/master/applications/KSM-embeddable-tip-or-donate-button.md

Quadratic Funding Pallet - DoraHacks (https://dorahacks.io/)
https://github.com/w3f/Grants-Program/blob/master/applications/dorahacks-quadratic-funding.md

Decentralised reputation systems and social networks - ZeroDAO
https://github.com/w3f/Grants-Program/blob/master/applications/ZeroDAO_Network.md
(Similar to Praise?)

**Comment by brichis** [comment]
Griff asked if they received some funds?
