### ISSUE TITLE
Kraken Grant

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#791]
Fund Your Dream Development Project
At Kraken, we know that our work wouldn’t be possible without the countless hours spent on innovative ideas by passionate open-source contributors. 

Bitcoin and other cryptocurrencies simply would not exist without these unsung heroes. 

That’s why we’ve started an open-source grant program designed to highlight and elevate great work that’s crucial to helping cryptocurrencies reach their potential.

Below you’ll find information on how to apply for a Kraken grant, as well as examples of the work that has inspired our giving in the past. 

We look forward to expanding financial freedoms together. 

Grant Categories
Kraken is open to considering grant opportunities in the following protocols, though we may consider opportunities in areas not listed below: 

Bitcoin (BTC)
Ethereum (ETH)
Lightning (LN)
Monero (XMR)
Other public cryptocurrencies 
Rust
Grantee Requirements
Kraken grants are awarded without obligation.  

Grantees will have the opportunity to submit quarterly updates on the impact of their work, discuss their work at Kraken events and on Kraken social media.

Ready to apply?
If you're interested in applying for an open-source grant, please reach out via email by clicking the link below. Feel free to include materials about your project and/or organization, or you can simply reach out to start a conversation.

We look forward to hearing from you!
[Email Us](mailto:grants@kraken.com)

**Comment by spectoregia** [comment]
I have emailed Kraken asking for more info and to connect. I'll wait until Jan to see if there's a response, otherwise will try again via their discord.

**Comment by spectoregia** [comment]
managed to get in touch with their support. they suggested sending another email describing the grant proposal in detail.
Already done: whitelabel idea 
https://docs.google.com/document/d/1E9TivUg81bL-Dl6VRENsBrF_r4SPo3yS4J6f8Frux50/edit#
