### ISSUE TITLE
Balancer

### ISSUE THREAD

**Issue by tropicalmangos** [Giveth/GIVeconomy#796]
https://quark-ceres-740.notion.site/Balancer-Grants-938f1b979810427f8d903a904315da41

**Comment by spectoregia** [comment]
balancer whitelabel grant request submitted:
https://docs.google.com/document/d/1s_CYDq9spDc_bvwbqEh70dAypt34N3gYLBABPpwQyvA/edit#

**Comment by spectoregia** [comment]
contacts to follow-up on our grant:
grants@balancer.community
Mitch Burns - @burns#2854 & Zen Dragon - @Zen Dragon#2923

**Comment by SnakeGH** [comment]
on January 3rd - 

"Thank you for showing interest in building within the Balancer ecosystem.

After careful consideration, we feel that other applicants are a better match for this program.

As you know, the crypto sphere is a bustling community and has many opportunities out there. We wish you best of luck in finding the right fit for your project.

Kind regards,
The Balancer Grants Committee"

**Comment by spectoregia** [comment]
after speaking with Griff about this, we can put it on hold until we have progressed with GIVfi further and then there might be an angle to reapply for Balancer and utilize their pools with GIVfi,
