### ISSUE TITLE
Project Verification Process

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#80]
Need to create an organized project verification process and team prior to GIVeconomy launch.

Right now, it takes about 2 weeks to verify, and the GIVback rounds will be 2 weeks long each... so the process is about 4 weeks.

This is the guide for onboarding members: https://www.notion.so/giveth/Project-Verification-Process-and-Guidelines-7772e953beb24a929c5ea6be902cc3bb

@WhyldWanderer can you work on creating a process for verifying projects? after you have a team of project verification people, it would be good to have a coordinated/organized system for ensuring that projects get verified in a timely manner.

**Comment by WhyldWanderer** [comment]
> @WhyldWanderer can you work on creating a process for verifying projects? after you have a team of project verification people, it would be good to have a coordinated/organized system for ensuring that projects get verified in a timely manner.

Sounds like a good plan! Once we have the team aligned, we can discuss the best method for ensuring that things happen in a timely manner within the structured rounds of GIVback calculations.

**Comment by laurenluz** [comment]
@ForestSoleil is coming back the week of November 23!! She's going to connect with Ashley to support project verification process and organization

**Comment by WhyldWanderer** [comment]
Forest and I had an in-person meeting yesterday to discuss what is needed for project verification as well as community support

**Comment by WhyldWanderer** [comment]
![image](https://user-images.githubusercontent.com/74267818/143145007-5579bc86-6de1-4adb-a91b-050da9062f3f.png)

**Comment by laurenluz** [comment]
https://www.notion.so/giveth/Project-Verification-Process-and-Guidelines-7772e953beb24a929c5ea6be902cc3bb
