### ISSUE TITLE
Forum statistics

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#812]
we use https://forum.giveth.io/ for deep discussion on proposals, ideas, features and tough decisions.

some useful stats to track would be: 
- amount of active unique users from the last 30 days
- amount of topics created in the last 30 days
- amount of comments in the last 30 days
- top 5 most active topics from the last 7 days (most comments and likes)

**Comment by clara-zi** [comment]
I think this data could be captured using Orbit - I can investigate unless anyone has a better suggestion @divine-comedian

**Comment by clara-zi** [comment]
@divine-comedian 
Top 3 points above are easy to capture with Orbit
Top 5 most active topics from the last 7 days (most comments and likes) should be possible but will need a bit of playing about with the data.
There are some other metrics available in Orbit for the forum: like most active days, most active categories, as well as tracking new member posts and returning member stats.

Orbit also currently produces reports for Discord, Twitter, GitHub. 
Just got us a free upgrade to one of their premium plans for non-profits to get more enriched reports.

**Comment by clara-zi** [comment]
I'll check.

**Comment by clara-zi** [comment]
Orbit are working on an embed but no indication as to when it will be available: it is not currently possible to embed reports into website.
Getting top 5 topics is not currently possible: the most granular I can get is by 'category' ie 'Proposals', 'Givernance', 'Platform' etc. 
Orbit will take a look at adding topics to the functionality of reporting.
It is relatively easy to hook up the reports for each platform - I'm just looking at the best ways to present info on one dashboard across platorms.

**Comment by oyealmond** [comment]
hey @divine-comedian do we still need this, is it a hight priority? Should we close the issue, move it to ice box?

**Comment by divine-comedian** [comment]
close it!
