### ISSUE TITLE
snapshot statistics

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#813]
we use snapshot to take in general community signalling 
https://snapshot.org/#/giv.eth

we should consider tracking some statistics

- total amount of votes in snapshot 
- average quorum
- total eligible voting supply
- average amount of participating tokens vs. total eligible voting supply (look at strategies) - gives percentage

**Comment by oyealmond** [comment]
Let me know what's the state of this issue. @divine-comedian
