### ISSUE TITLE
nrGIV statistics

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#814]
we currently use nrGIV for most of the decisions within the core team
https://xdai.aragon.blossom.software/#/nrgiv/

some useful statistics to track would be 
- who holds nrGIV and how much
- total amount of nrGIV votes - there's 2 voting apps
- how often each nrGIV holder votes
- average quorum across votes

**Comment by oyealmond** [comment]
close this @divine-comedian ?
