### ISSUE TITLE
DAO treasury info

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/GIVeconomy#817]
@franculio worked on collecting the treasury info for reporting to DeepDAO
@freshelle regularly updates our DAO holdings on a monthly basis - she has a good idea of where our holdings are kept. 

We'll need to find where these holdings are - calculate the value of their holdings, including the value of liquidity positions and how to add this info to the dashboard.

**Comment by oyealmond** [comment]
closing this @divine-comedian ?
