### ISSUE TITLE
FLII Create a proposal to insert Giveth within the buyer's journey.

### ISSUE THREAD

**Issue by Cotabe** [Giveth/GIVeconomy#824]
We have an open door to nudge FLII attendees (Latinamerican Forum for Impact Investing) to donate through Giveth to for good projects, live the experience & maybe even present results at a talk. The audience is about 1/3rd impact investors, 1/3rd ecosystem enablers, 1/3rd entrepreneurs.

The proposal will have to be approved by the FLII team, but we have a lot of good will.

The proposal needs to be created fast and be easy to implement. While at the same time trying to maximize the number of donors that would use it and hopefully stick with the platform.

The tickets are already being sold. Therefore, inserting a CTA into the sales journey might be complicated. But inserting CTA's into their communications might be easier.

Ideas to make the journey more compelling:
1. Match their donation with the matching fund's pool, the FLII or other partners.
2. Create a POAP

Journey idea:
1. Create a simple CTA in the FLII's communications. 
"Make a donation with an upside... FLII has partnered with Giveth to allow our community to donate $10 USD to non-profit projects. They will get $20 USD and donors would get up to $15 USD worth in the GIV token... learn more about how to invest in non-profits with Giveth [link to a form]"
2. FORM: 
2.a. Maybe create a short explanation video. 
2.b. Get key info (name, organization, email), 
2.c Ask if they have a wallet 
2.c.I. If they do ask for their wallet for a POAP 
2.c.II If they don't, teach them the easiest way (maybe metamask and fund it in the wallet). Then ask for their wallet for a POAP.
2.d. Teach them how to make a donation.
2.e. Congratulate for becoming a donor.

**Comment by Cotabe** [comment]
I also think Caro from the FLII would be stoked to have something like this https://twitter.com/myNFT/status/1590690370484338695?s=20&t=8wC3W6d8hZBIjSCE5mFLQw

**Comment by SnakeGH** [comment]
Sounds like an amazing opportunity for Giveth in a time that we are really pushing for an impact investor and additional donors. You've answered the questions, "how to attract both investors & donors from this event to our platform" with both financial and POAP incentives, as well as a marketing campaign along with it. No additional feedback at this time from me. On the right track...
