### ISSUE TITLE
No way to delete all your previous booted projects

### ISSUE THREAD

**Issue by Santigs** [Giveth/GIVeconomy#825]
When trying to delete your previous boosted projects you always have to leave one open to allocate the 100% of your power.
Although I see the tech reasoning behind it, I see it confusing for a user who wants for instance to delete its previous boosted projects and replace them with other ones. At the time he/she tries to delete them all, it will not be possible.

**Comment by laurenluz** [comment]
We added a copy change to help make this more clear. This is actually by design to make it so that 100% of voting power is always in use
