### ISSUE TITLE
GIving Tuesday Tweet

### ISSUE THREAD

**Issue by c0ric0ri** [Giveth/GIVeconomy#826]
@oyealmond had the idea for Giving Tuesday to invite our Twitter community to share their favorite project, and we will RT them all day. We can use the #GivingTuesday hashtag to participate in the trend tomorrow.

I like the idea a lot as it engages more with the community, we can create a new meme for it.

For reference: https://www.givingtuesday.org/

They also offer logos and GIFs here to use! https://www.givingtuesday.org/logos/

**Comment by laurenluz** [comment]
Let's do it! @oyealmond or @c0ric0ri can you make a draft tweet as well? And keep an eye on the twitter tomorrow then to do those RTs?

**Comment by c0ric0ri** [comment]
Yes for sure. Thanks for the quick feedback!

@oyealmond for some reason I cannot assign you, Github is acting weird today!

**Comment by oyealmond** [comment]
Hey @c0ric0ri @laurenluz ! 
Could you help me w your feedback on [this #GIVersTuesday tweet](https://docs.google.com/document/d/1WSdY_ghmJU5iZo1hJfk00x8gIJ7RIY4lI5pQG187hIs/edit?usp=sharing) please? 

I tried it to keep it simple :)  

I will be checking all tweets tomorrow to make sure we don't miss a RT

**Comment by laurenluz** [comment]
Hey @oyealmond can you make it comment access?

Also why "GIVersTuesday"?  It's an awkward one to type, tbh.

GIVingTuesday?

**Comment by c0ric0ri** [comment]
@laurenluz mentioned we could add tweets to this thread, that quote retweet our last few verified projects tweets. That way we are linking to a bunch of our past tweets and also highlighting a bunch of latest verified projects for people to explore

**Comment by oyealmond** [comment]
ready @laurenluz ! 
I thought #GIVingTuesday too, but, Idk if the Twitter algorithm will identify the Capital letters. Im afraid Tweets getting lost

**Comment by oyealmond** [comment]
Maybe we could ask to "add #GIVingTuesday and mention @Givethio too for us to RT"

**Comment by laurenluz** [comment]
What about just #GIV? then we can use it more often too? I think Stee was suggesting that.

We should definitely ask for them to tag Giveth.

**Comment by oyealmond** [comment]
"Choose the projects you love and tweet them using #GIVingTuesday. Don’t forget to include links & tag us too."

I think if we asked them to tag us, I can make sure to not miss one Tweet using #GIVingTuesday . I like the # v much for tomorrow :) & I agree, definitely we should start using #GIV. wdyt?

**Comment by laurenluz** [comment]
sounds good!

**Comment by laurenluz** [comment]
nice job @c0ric0ri @oyealmond ! I made some edits & set up to go out at 6am ET :)

**Comment by oyealmond** [comment]
https://twitter.com/Givethio/status/1597546681058336768
