### ISSUE TITLE
ETC Grants DAO

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/GIVeconomy#842]
website: https://etcgrantsdao.io/home

**Comment by SnakeGH** [comment]
In contact with Bob Summerwill (lead steward) and he mentioned some announcements at the end of January 2023

**Comment by spectoregia** [comment]
They have opened a new round of grant applications. Jake was approached by their team encouraging us to apply for a grant.
We've prepared a draft here: https://docs.google.com/document/d/1NPSG4CYLRXtIDf6FrBHD7TBeQdfaTIeupZcUz4n1ifY/edit#

**Comment by SnakeGH** [comment]
@spectoregia can you drop the grant submittal for ETC grant here pretty please. Thank you!

**Comment by spectoregia** [comment]
@SnakeGH https://github.com/Giveth/GIVeconomy-fundraising/tree/main/ETC
