### ISSUE TITLE
Giveth stats

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/GIVeconomy#843]
## Note

This is part of the **Why Giveth** section and as we may use this on other screens, we also shared the separated row here as well.

To check the **Why Giveth** section please go to issue #1992

## Responsive guides

**(>1280)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245528&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245528&t=HA0MWRVrAq4gj0Hq-4)

**(>1024- <1279)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245549&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245549&t=HA0MWRVrAq4gj0Hq-4)

**(>768 - <1023)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245570&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245570&t=HA0MWRVrAq4gj0Hq-4)

**(Mobile)**
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245591&t=HA0MWRVrAq4gj0Hq-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17980%3A245591&t=HA0MWRVrAq4gj0Hq-4)

--- 

![Screenshot 2023-01-10 at 4.12.15 PM.png](https://images.zenhubusercontent.com/61dd85b9a1419a0fc83f15d1/4ba9df16-63f8-4aad-b061-ada00daaab4e)

**Comment by MoeNick** [comment]
Issue moved to [Giveth/giveth-dapps-v2 #2025](https://github.com/Giveth/giveth-dapps-v2/issues/2025) via [**Zenhub**](https://www.zenhub.com/)
