### ISSUE TITLE
GAME7 

### ISSUE THREAD

**Issue by SnakeGH** [Giveth/GIVeconomy#845]
website: https://game7.io/

Application: https://grants.game7.io/technology

**Comment by spectoregia** [comment]
Game7 was funded (massively) by BitDAO. We were seeking funding from BitDAO until they changed their strategy to fund the existing projects in their ecosystem and fewer new ones. After continuous discussions with BitDAO guys, the agreement was that we should find a way to support their projects with our tools or anything else that we can offer as a value add and they will fund us for that. 
General Magic is the best candidate that can do that and we have decided that Giveth can not really add much here.

I would consider there isn't much we can do here with Giveth unless anyone has some ideas. Until then I'll close this issue.
