### ISSUE TITLE
Notifications Menu

### ISSUE THREAD

**Issue by mosaeedi** [Giveth/GIVeconomy#848]
### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17997%3A234222&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=17997%3A234222&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245289&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A245289&t=huSwZsLxPMwnLBB2-4)

---

### Light
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247230&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247230&t=huSwZsLxPMwnLBB2-4)

### Dark
[https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247285&t=huSwZsLxPMwnLBB2-4](https://www.figma.com/file/nVoinu0tgJ565enN5R4WDE/Giveth.io-%26-GIVeconomy?node-id=18047%3A247285&t=huSwZsLxPMwnLBB2-4)

**Comment by MoeNick** [comment]
Issue moved to [Giveth/giveth-dapps-v2 #2039](https://github.com/Giveth/giveth-dapps-v2/issues/2039) via [**Zenhub**](https://www.zenhub.com/)
