### ISSUE TITLE
Public Goods Router 

### ISSUE THREAD

**Issue by spectoregia** [Giveth/GIVeconomy#849]
Idea: Leveraging high volume liquidity pools, like curve, save, yearn. Asking them if they wanted to add a public good fees (1% for the planet kind of thing) maybe to fund the matching pool.

- CoW swap, wanted to approach to this in a bit of a more complicated way.
    - Donate part of a positive slippage.
    - Pursue with CoW swap at least.
    - @SnakeGH will handle it.

@GriffGreen and/or @SnakeGH to setup a TG group to agree on the details. 
@spectoregia will follow on to use the info and continue with Aave and Balancer since the communication channels are open.

**Comment by spectoregia** [comment]
@divine-comedian will connect us with Luuk or Fabio from Balancer. 

@spectoregia and @SnakeGH will look into 1inch, idle DAO, curve.

**Comment by brichis** [comment]
Only to follow-up this issue... Did Griff setup a TG group with you @SnakeGH already and agree with the details? If not, to ask that on his to-do list :D

**Comment by spectoregia** [comment]
Yes there is a discord group: https://discord.gg/3zvJCdM9
this link will expire so if anyone wants to join past that, just DM me or Jake. :)

**Comment by SnakeGH** [comment]
> Only to follow-up this issue... Did Griff setup a TG group with you @SnakeGH already and agree with the details? If not, to add this on his to-do list :D

@brichis No, we didn't set up a TG group, I just went ahead and emailed my contact at CoW swap. So you can remove it from Griff's to do list :)

**Comment by SnakeGH** [comment]
@spectoregia you may want to turn this into an epic now and add Idle, Curve, 1inch and any other's we want to try for.

**Comment by spectoregia** [comment]
related issue (1inch): https://github.com/Giveth/GIVeconomy/issues/853

**Comment by divine-comedian** [comment]
> @divine-comedian will connect us with Luuk or Fabio from Balancer.
> 
> @spectoregia and @SnakeGH will look into 1inch, idle DAO, curve.

I reached out to Luuk, he doesn't work for Balance anymore - he sent a message to Balancer on our behalf - have not heard back.
