### ISSUE TITLE
Delete "check out" from the link description

### ISSUE THREAD

**Issue by brichis** [Giveth/GIVeconomy#852]

**Comment by brichis** [comment]
@laurenluz @RamRamez FYI I'll create this issue in the correct repo (dapps) and I'll close this one because I made a mistake jeje

**Comment by laurenluz** [comment]
@brichis - instead of duplicating... you can transfer the issue to the correct repo. 

the way you did it is inconvenient because I had made a comment on this one which now I have to copy into the other.

it's fine, just take a note for next time.
