### ISSUE TITLE
1inch Public Goods Router 

### ISSUE THREAD

**Issue by spectoregia** [Giveth/GIVeconomy#853]

**Comment by spectoregia** [comment]
form submitted: https://docs.google.com/forms/d/1ZeGCXe2_WTSn0lo1b-bDSjb_9XIJvjUA_8gicUnFpzA/viewform?edit_requested=true

**Describe why the partnership fits the "win-win" vision 

(expected output / benefit for 1inch — please describe exactly which KPIs like number of users, transaction volume, etc you are looking to achieve)**
Giveth is a donation platform built on Ethereum, rewarding and empowering those who give to projects, to society, and to the world. We are building a business model, which provides value in the nonprofit sector and public goods. 
Our proposal for 1inch is to bring the donation culture into their community and platform by adding a simple UX feature where 1inch users could donate up to 1% (TBD) of the transaction to Giveth - this could be a fee from slippage or a voluntary donation.

**Comment by SnakeGH** [comment]
Started a TG group with Natalia to discuss in more detail, as they use to have a "donate here" button with The Giving Block before

**Comment by spectoregia** [comment]
draft: https://docs.google.com/document/d/1nX0ARvNW7JoIG1kzWks3vhEypdYJpL4PA7s9RkP3SJ4/edit#
currently awaiting feedback.

**Comment by GriffGreen** [comment]
I reviewed and edited
