### ISSUE TITLE
NFT Reserarch platforms

### ISSUE THREAD

**Issue by Santigs** [Giveth/GIVeconomy#859]
This is to add everything related to potential partner platforms for NFT minting

**Comment by Santigs** [comment]
After Initial research we are focussing in three platforms:

[Zora.](https://zora.co/)
[Thirdweb.](https://thirdweb.com/)
[Unlock Protocol.](https://unlock-protocol.com/)

Have reached Zora and Unlock. The second ones are quite open to having a meeting and discussing a potential collaboration. 
Trying to arrange a meeting with them during eth Denver. Zora has not shown too much interest after contacting with them. They charge 5% if you use their SDK to mint and sell your collections.

**Comment by brichis** [comment]
Hey @Santigs! I don't know If this is what you're searching for: https://www.bueno.art/
But If it is, I can connect you with them :)

**Comment by Santigs** [comment]
Thank you @brichis we are actually looking for partners which do not add any cost for the minting.
I know Bueno and they are a cool tool for anyone who is not intending to develop.

**Comment by Santigs** [comment]
The needs we are interested in to create an NFT collection deployer are:

NFT contract factory to deploy contracts 
Image loader
Metadata generator.
Minting page creator
Opensource code


Additionally, a secondary market would be nice, although any collection can use the most common NFT market as Opensea.


**Zora**

Well-developed platform with a nice front-end App to launch a collection.
Minting iframe embed tool available.
They take 5% of sales.
Need external tools for image upload and metadata.
Discord support.
Only supports mainnet, Polygon and testnets.
It is more a SAAS for creators but code is opensource.



**Unlock Protocol**

They have a contract factory to create and deploy smart contracts, which they call locks.
Their platform runs on most EVM chains including Gnosis.
They do not take any sales commission if collectors use crypto to pay
They take commissions if collectors use their credit card ramp to pay but we could implement ours.
Their solution adds collection customization changes after launch.
Their solution adds burning NFTs, but there is a way to "disable" that if needed.
Discord Support
[Here’s a guide describing how to use their tool + bueno + pinata to launch a collection.](https://unlock-protocol.com/guides/how-to-use-different-images/)


**ThirdWeb**

Offers collection and edition contracts
Has an sdk and is well documented
OpenSource with no commission
Has splitter and marketplace contracts on top of NFT drop and Edition drop
Supports several EVM’s but not Gnosis chain

**Comment by Santigs** [comment]
We are working on a meeting with Unlock Protocol during  Eth Denver.
Unlock has also added their smart-contract in Thirdweb directory so we might even have a direct link to Thridweb through them.

**Comment by laurenluz** [comment]
This is from the GIVeconomy call notes. Just pasting them here, for reference:

Also @Santigs - what's the staus with this? would love to breathe more life into this project, it's been too many weeks without much happening.

- Unlock protocol
    - adds option of adding a date to NFT, this helps to use NFT as a ticketing solution or membership solution - can make it expirable or renewable
    
- Zora
    - Zora only uses mainnet and polygon and they take 5% off the top.
    
- Third Web
    - Cool but they don’t work with Gnosis

- [[Create3webdapp](https://createweb3dapp.alchemy.com/)](https://createweb3dapp.alchemy.com/)
    - easy to launch a collection
    - Integrating NFTs w/ IOS wallet & android wallet so you can IRL check if someone has an NFT and give them a pass to enter some place
    - little by little, more & more tools are launching
    
- Alchem
    - [[Ethereum pass](https://www.ethpass.xyz/)](https://www.ethpass.xyz/) - we can use for example to allow people to enter the Giveth house

**Comment by Santigs** [comment]
Unlock is offered directly on their web but also integrated into thirdweb so plenty of support from them although their solution targets more a ticketing/subscription service. Great documentation. Not too many new additions to their tool

**Comment by Santigs** [comment]
After jumping deeply into most of the tools out there, there are basically two groups; Those which offer development tools to create your dapps (ThirdWeb, Alchemy) and those that offer you their platform to launch collections.

Thirdweb is very well developed and documented, they have raised money and keep adding tools every other week. They have also created a way to use their SDK with smart-contracts created by third parties. Alchemy just launched their Web3 dApp Creator tool which seems very promising. Their platform is also full documented.

Then there are a bunch of specific tools you can use to launch a collection to the market, or offering specific services around NFTs, as Dappback where you create gamification programs offeing tokens and NFTs for those users executing specific tasks, or EththerScore which is basically a soulbound minter.

Finally, there are several services offering ways to create token-gated content.

We have to decide if we want to jump into tools such as Thirdweb/Alchemy and create our own "NFT collection factory" tool to offer to project owners as a way to mint and raise funds for their projects and also decide if we want to try any of the service tools for Giveth as a way to promote our own service/collection.

**Comment by Santigs** [comment]
I've created this doc describing what could be an initial basic NFT application for Giveth projects
https://docs.google.com/document/d/1qX77dX1NXfTYO0H9eladlT20PPjznh0dKOG1c4tEwCA/edit?usp=sharing
