### ISSUE TITLE
Create a Gnosis Safe on Mainnet to have ownership privileges over the token economy there 

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#86]
rGIV will have most of the power... as most of the action is on xDai... but we will be launching the Token on Mainnet and we will want to have minting powers controlled by this multisig, as well as the GIVstream and Liquidity Mining powers... all these things will start with the devs deploying the smart contracts as the owner, but all the powers will need to be transferred to the multisig once everything works right.

- [ ] Figure out who wants to be on it (I would suggest a 5 of 10)
- [ ] Deploy the safe

**Comment by laurenluz** [comment]
https://forum.giveth.io/t/join-some-giveth-multisigs/168/19

**Comment by laurenluz** [comment]
@aminlatifi multisigs will need to have admin privileges after launch - will need to be "owner" of the deployment
