### ISSUE TITLE
Review and help update fundraising deck

### ISSUE THREAD

**Issue by danelsuga** [Giveth/GIVeconomy#860]
with @GriffGreen and @spectoregia

**Comment by danelsuga** [comment]
@spectoregia I can't seem to move this issue to Q&A. Did you see my additions?

**Comment by c0ric0ri** [comment]
@danelsuga has this been reviewed?

**Comment by danelsuga** [comment]
yes.

**Comment by laurenluz** [comment]
@danelsuga  can you add the link in here?

**Comment by danelsuga** [comment]
https://docs.google.com/presentation/d/1OAkiIIgHYQln9ov8A8SLlF6dKmkCu3Mpa_Xfk2kgcCo/edit#slide=id.g158c393ab0c_1_15
