### ISSUE TITLE
Unable to unstake from the GIVfarm

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#866]
I should be able to unstake GIV from the farm but am unable to.
![image](https://user-images.githubusercontent.com/74267818/229208617-c40cee92-5845-4ae6-a681-5c5d8d987cef.png)
![image](https://user-images.githubusercontent.com/74267818/229208623-37882ae2-173c-4717-af46-beae138a87de.png)

**Comment by WhyldWanderer** [comment]
Also in the Regen Farm
![image](https://user-images.githubusercontent.com/74267818/229209235-d5b2ca52-6d07-484f-a7c5-765bcc71242d.png)
![image](https://user-images.githubusercontent.com/74267818/229209246-cf00c82a-f8e3-4c2b-893a-145c8c6e39c0.png)

**Comment by MohammadPCh** [comment]
@WhyldWanderer You are right, the amount was wrong. it's fixed now. Thanks.

**Comment by maryjaf** [comment]
Thanks @MohammadPCh @WhyldWanderer 
It has been resolved on production

**Comment by WhyldWanderer** [comment]
Confirmed! It is working now
