### ISSUE TITLE
Instant Boost

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#868]
<img width="642" alt="Screen Shot 2023-02-10 at 11 56 22 PM" src="https://user-images.githubusercontent.com/14945613/218136866-98ea009e-2b40-43cc-a4dc-f449ff4aa7cb.png">

Given the situation in turkey... it would be awesome if GIV holders could impact the rankings in real time....

Would love to prioritize this!

**Comment by laurenluz** [comment]
To clear up confusion around this issue, I made a mini-spec for it: https://www.notion.so/giveth/Instant-Boost-Mini-Spec-cea340e1bbf2456f8c7b237c07e5f8aa

Hopefully that helps.
