### ISSUE TITLE
Hack session to ask people for addresses

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/GIVeconomy#87]
After we have all the numbers for the GIVdrop, and we have consolidated all the amounts, we need to go and ask like 200 people for their addresses... many people we will have trouble finding but we don't have to find them all... Bowen did this for a lot of people...

**Comment by laurenluz** [comment]
Hannah & Griff to meet tonight about finalizing GIVdrop recipients... need people to hunt down the missing people:
- who do we leave out
- who do we NEED
- who are nice-to-haves

Will split up the list among the team

**Comment by laurenluz** [comment]
To schedule 1hr call with @GriffGreen @bowensanders Algene @geleeroyale @Danibelle @krrisis to try to get as many of our missing addresses in the GIVdrop as possible up-to-date

**Comment by GriffGreen** [comment]
Doodle made and distributed to a few contributors
:-D

https://doodle.com/poll/sxa4vpz2achtr75q

**Comment by laurenluz** [comment]
hack sessions are on today! will get a GIVdrop list to Amin by the end of the day tonight!!!

**Comment by laurenluz** [comment]
call is at 2pm Costa Rica time
