### ISSUE TITLE
The Unlocked notification on OP has not been sent on STG

### ISSUE THREAD

**Issue by maryjaf** [Giveth/GIVeconomy#887]
I locked some GIV on Pptimism Goerli on staging for 1 round until 10 Sep,  but I didn't receive any notification after unlocking
@aminlatifi

**Comment by aminlatifi** [comment]
The root cause is your position is not unlocked. I think the devops team has not deployed givpower-bot for staging env yet.
@mhmdksh

**Comment by maryjaf** [comment]
Thanks, this issue has been resolved
[Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaldXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2720bfd21d6d1f10c862b5b974e84835f0b1f4c3/image.png)

**Comment by mhmdksh** [comment]
> Thanks, this issue has been resolved [Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaldXIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2720bfd21d6d1f10c862b5b974e84835f0b1f4c3/image.png)

@maryjaf Yes the givpower bots have been deployed :)
