### ISSUE TITLE
Update token info on optimistic.etherscan.io

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/GIVeconomy#889]
Now that we have GIV on Optimism, we should update the token details... it looks a little shady.

![image](https://github.com/Giveth/GIVeconomy/assets/74267818/8f3a65c5-48b6-4d92-b9df-522ba784e443)

Can we add the token symbol and the social links? website link? etc?

I tried to do it but I am not the contract owner so I was unable to.

**Comment by laurenluz** [comment]
@divine-comedian are you the contract owner for GIV on Optimism?

**Comment by divine-comedian** [comment]
guys, add links to things!!! helps so much when trying to jump into issues

**Comment by laurenluz** [comment]
you're the best @divine-comedian !

**Comment by divine-comedian** [comment]
Done! 
https://optimistic.etherscan.io/token/0x528cdc92eab044e1e39fe43b9514bfdab4412b98
