### ISSUE TITLE
Check what % of GIV rewards for GIVpower stakers is being restaked, and what % dumped

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#897]
As per [this forum post](https://forum.giveth.io/t/givpower-summary-requesting-giv-for-incentives-update-q4-2023/719/30) it would be great to do some research on the stats of what % is being dumped.

We maybe want to lower, or discontinue staking rewards if it's a lot. In any case this data can help us strategize.

@divine-comedian volunteered to do some digging on the blockchain!

cc @GriffGreen

**Comment by divine-comedian** [comment]
https://docs.google.com/spreadsheets/d/1c-eBvBb0mrhz-GJ1WH6KPX90tzq3zetaH9ik0gqwLic/edit?usp=sharing

**Comment by oyealmond** [comment]
I think this is done, no @divine-comedian?

**Comment by divine-comedian** [comment]
We can leave this one plz @oyealmond
