### ISSUE TITLE
No Volumen Uniswap LP on Mainnet -  FOX/GIV Mainnet

### ISSUE THREAD

**Issue by wmb81321** [Giveth/GIVeconomy#914]
## Description
There is no volume with a   UniswapV3 LP on Mainnet - FOX/GIV.
Here is the link: https://app.uniswap.org/explore/pools/ethereum/0xad0e10df5dcdf21396b9d64715aadaf543f8b376?chain=base

**Comment by wmb81321** [comment]
We are sending a request form : https://support.uniswap.org/hc/en-us/requests with the following request:

_Our address 0x9d1E4A6b3361abcCC90C7F8788ac246d194303 deployed following LP on Mainnet with UniswapV3, but the following link (https://app.uniswap.org/explore/pools/ethereum/0xad0e10df5dcdf21396b9d64715aadaf543f8b376?chain=mainnet) doesn't show any volume, this is ok? Something happened?_

**Comment by laurenluz** [comment]
Hey @wmb81321! thanks for following up on this! Is it relevant to share the address that deployed the liquidity? just wondering.

I guess they would want to know if the DAO owns it? 🤔 also is our liquidity in-range? can you check that too? if it's univ3 maybe we need to keep track.

**Comment by wmb81321** [comment]
Yes, they answered to the email i sent last week.

Looks like we dont meed TVL, volume, and liquidity requirements for Uniswap on that pair.

![Screenshot 2024-07-29 at 16 03 09](https://github.com/user-attachments/assets/27a9ca7d-f04e-4cb3-9295-391773003add)

**Comment by wmb81321** [comment]
I asked about which are those requirements and just answered they don't share that info for gamification.

![Screenshot 2024-07-29 at 16 04 44](https://github.com/user-attachments/assets/514275b3-ecb3-4b3f-b210-686988dd860f)

**Comment by wmb81321** [comment]
This is strange because our MATIC/GIV https://app.uniswap.org/explore/pools/ethereum/0x46ad345fff4aec9990a4f20e829c50fbf291db0e Has lower liquidity and it's showing up normally. Maybe is something related with Daily Volume.

**Comment by laurenluz** [comment]
@wmb81321 as discussed in the GIVeconomy call, can you look to see if we should move the FOX/GIV LP to another DEX? Since it's being wasted in Univ3.

Perhaps look at other places that FOX has liquidity and see if we can add the GIV/FOX LP over there and have it be routed?

**Comment by wmb81321** [comment]
Im creating an spreadsheet with [FOX pairs on Mainnet](https://docs.google.com/spreadsheets/d/1kSUGqSgT3Uh-IMB9WndNio5JdwdaWfsbk_5_RWxpoIQ/edit?gid=0#gid=0)

- Looks like FOX only have WETH/FOX on Mainnet
- WETH/FOX Uniswap Analytics Page is looking good (https://app.uniswap.org/explore/pools/ethereum/0x470e8de2ebaef52014a47cb5e6af86884947f08c)
- They have a big LP on Mainnet, TVL $3.1M

**Comment by wmb81321** [comment]
@laurenluz @GriffGreen If we are considering moving out FOX/GIV on Mainnet to another DEX, we could move out to **Balancer or Sushiswap could be a practical option**. 

This is based on stats of DEXs on Mainnet with Defillama: https://defillama.com/dexs/chains/ethereum

DEX Sorted by volume 24hrs, a DEX option could be: Curve, DODO and **Balancer.**
![Screenshot 2024-08-14 at 10 04 27](https://github.com/user-attachments/assets/7bc68e61-f60a-4027-9cda-ac770213f4f5)



DEX Sorted by TVL, a DEX option could be: Curve Finance, **Balancer**, Sushiswap
![Screenshot 2024-08-14 at 10 05 44](https://github.com/user-attachments/assets/f7be05b1-5ef2-4087-9457-923ab3e8599e)

**Comment by wmb81321** [comment]
**Balancer**
- Top 4 by Volumen 24hr and Top 3 TVL locked
- Allows Mainnet, Optimism, Gnosis and Polygon ZKEVM
- we have an LP (WETH/GIV) with Balancer on Mainnet, but now has very low TVL of ≈ 3,5K : [0x7819f1532c49388106f7762328c51eE70EdD134c](https://app.balancer.fi/#/ethereum/pool/0x7819f1532c49388106f7762328c51ee70edd134c000200000000000000000109)

**Sushiswap**
- Position 12 by Volumen 24hr and Top 4 TVL locked
- Allows Mainnet, Optimism, Gnosis and Polygon ZKEVM 
- We have a LP WETH/ETH on Gnosis with ≈ $7.5K TVL: [0x55ff0cef43f0df88226e9d87d09fa036017f5586](https://www.sushi.com/pool/100%3A0x55ff0cef43f0df88226e9d87d09fa036017f5586)

**Curve Finance**
- Top 2 by Volumen 24hr and Top 2 TVL locked
- Allows Mainnet, Optimism, Gnosis. _Does not have Polygon ZKEVM._
- We dont have any LP with them.

**Comment by wmb81321** [comment]
We succesfully we move out GIV/FOX on Mainet from Uniswap to Balancer.

Here is the link on notion about details: https://www.notion.so/giveth/FOX-GIV-e5c888f88a7d47019bda7a5f129f25d6?pvs=4
