### ISSUE TITLE
Add links to bridge from xdai to mainnet in UI

### ISSUE THREAD

**Issue by laurenluz** [Giveth/GIVeconomy#98]
On the GIVfarm & on the GIVdrop

**Comment by GriffGreen** [comment]
https://omni.xdaichain.com/bridge

@markoprljic can you make a quick mock up?

**Comment by markoprljic** [comment]
![Image 2021-12-23 at 4 42 58 pm](https://user-images.githubusercontent.com/5704285/147264671-7aa9925f-51c7-406b-8190-f2dea252c853.jpg)
